### ISSUE TITLE
EOF while proxying

### ISSUE THREAD

**Issue by pantera329** [bluenviron/mediamtx#1153]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Error returned: RTSP source: fix EOF error that happens when using TCP with some cameras (https://github.com/aler9/rtsp-simple-server/issues/548)

*Works correctly from 0.17.10 to version 0.17.14 inclusive, from version 0.17.15 to 0.20.0 results in a permanent error

Sep 15 09:45:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:45:54 INF [RTSP] [conn x.x.x.x:50674] opened
Sep 15 09:45:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:45:54 INF [RTSP] [session 848144299] created by x.x.x.x:50674
Sep 15 09:45:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:45:54 INF [RTSP] [session 848144299] is reading from path 'cam240', with UDP, 2 tracks (H264, PCMA)
Sep 15 09:46:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:46:54 INF [path cam240] [rtsp source] stopped
Sep 15 09:46:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:46:54 INF [path cam240] [rtsp source] ERR: EOF
Sep 15 09:46:54 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:46:54 INF [RTSP] [session 848144299] destroyed (terminated)
Sep 15 09:47:00 vm-bd11e44c rtsp-simple-server: 2022/09/15 09:47:00 INF [RTSP] [conn x.x.x.x:50674] closed (session not found)

## Describe how to replicate the issue

1. start the server
2. publish with api
3. read with player, connection drops after ~132 seconds

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Please provide a network dump as clearly stated in the issue tutorial, otherwise it's impossible to replicate the issue.

**Comment by aler9** [comment]
This can't be solved without the author help.
