### ISSUE TITLE
API Security / API Keys or User/Pass

### ISSUE THREAD

**Issue by t3therdev** [bluenviron/mediamtx#1284]
## HTTP API Security

How can we secure the HTTP API other than firewall/IP security?

Can we get a field for a custom API key or string value that needs to be authenticated prior to using the API? Or a username/pass, similar to RTST path authentication?

**Comment by aler9** [comment]
Linked to #1341

**Comment by saket424** [comment]
From my testing, it appears username/password authentication already works for the webrtc feed just like it does the rtsp feed

**Comment by aler9** [comment]
this was fixed by #3081
