### ISSUE TITLE
MaxClients Configuration

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#1286]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/1185

<div type='discussions-op-text'>

<sup>Originally posted by **DnzDmR** October 11, 2022</sup>
Is there a configuration where I can specify the maximum number of users to connect? Like the MaxClients parameter in ffserver.</div>

**Comment by derricck** [comment]
Hi any change this feature getting added?

**Comment by aler9** [comment]
implemented with #2154
