### ISSUE TITLE
A problem about hls

### ISSUE THREAD

**Issue by lystormenvoy** [bluenviron/mediamtx#1294]
## Which version are you using?

v0.20.3

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I publish the stream to server use ffmpeg.
The command like:
````
ffmpeg -re -ss 0 -stream_loop -1 -i "I:\1.mp4"  -vcodec h264 -acodec aac -f flv "rtmp://192.168.37.176:1935/hls/streamname"
````

Then I try to play hls in vlc.

It is normally when hlsVariant is mpegts.
When I change the hlsVariant to lowLatency. VLC play with black screen, the progress bar start with 00:30 and can increase continuously.
![image](https://user-images.githubusercontent.com/6795312/207016449-9cfd1e86-d1b7-4d9e-a637-3e42d34de6cc.png)

## Describe how to replicate the issue

1. start the server
2. publish with ffmpeg
3. read with vlc

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i tried replicating the issue but in my case i was able to read a low-latency stream with VLS perfectly.
Keep in mind that VLC doesn't support gap segments, that in case of LL-HLS are put at the beginning of the stream, since iOS always require 7 segments at least, therefore you'll have to wait ~30secs before reading the stream:

```
ale@alex:~/ALE_CLOUD/sample_videos$ curl -k https://localhost:8888/stream/stream.m3u8
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-TARGETDURATION:8
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=0.58325,CAN-SKIP-UNTIL=48
#EXT-X-PART-INF:PART-TARGET=0.2333
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="init.mp4"
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-GAP
#EXTINF:8.23333,
gap.mp4
#EXT-X-PROGRAM-DATE-TIME:2023-01-22T18:57:56.952Z
#EXT-X-PART:DURATION=0.23327,URI="part0.mp4",INDEPENDENT=YES
...
```

Anyway, please provide the playback file (1.mp4) in order to allow to replicate the issue.

**Comment by lystormenvoy** [comment]
> Hello, i tried replicating the issue but in my case i was able to read a low-latency stream with VLS perfectly. Keep in mind that VLC doesn't support gap segments, that in case of LL-HLS are put at the beginning of the stream, since iOS always require 7 segments at least, therefore you'll have to wait ~30secs before reading the stream:
> 
> ```
> ale@alex:~/ALE_CLOUD/sample_videos$ curl -k https://localhost:8888/stream/stream.m3u8
> #EXTM3U
> #EXT-X-VERSION:9
> #EXT-X-TARGETDURATION:8
> #EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=0.58325,CAN-SKIP-UNTIL=48
> #EXT-X-PART-INF:PART-TARGET=0.2333
> #EXT-X-MEDIA-SEQUENCE:1
> #EXT-X-MAP:URI="init.mp4"
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-GAP
> #EXTINF:8.23333,
> gap.mp4
> #EXT-X-PROGRAM-DATE-TIME:2023-01-22T18:57:56.952Z
> #EXT-X-PART:DURATION=0.23327,URI="part0.mp4",INDEPENDENT=YES
> ...
> ```
> 
> Anyway, please provide the playback file (1.mp4) in order to allow to replicate the issue.

Hi,
I find that maybe it just because VLC does not support ll-hls, it work with hls.js

**Comment by aler9** [comment]
We can assume that this issue is closed.
