### ISSUE TITLE
WebRTC Ingest / WHIP Support

### ISSUE THREAD

**Issue by mpisat** [bluenviron/mediamtx#1429]
## Describe the feature

It would be nice to have WebRTC ingest (with WHIP, even better) support. Considering you use pion, it should be possible in theory?

https://github.com/Glimesh/broadcast-box
uses Pion for WebRTC ingest and playback for example.

**Comment by iesv** [comment]
+1

**Comment by mfchiz** [comment]
I would love this feature. +1

**Comment by sujoshua** [comment]
+1

**Comment by Janxinka** [comment]
.github/workflows/release.yml
