### ISSUE TITLE
Add option to change muted autoplay to press to play but default audio enabled

### ISSUE THREAD

**Issue by DJFPaul** [bluenviron/mediamtx#1525]
## Describe the feature

I'd love to see a config option that allows to change from current autoplay with muted audio, to press to play but default enabled audio.

I personally prefer this mode as especially on mobile devices it's much more preferabler to tap mid screen to play the stream and have audio be default on instead of auto playing with muted audio.
It's also less confusing to less tech savvy audience who can easily be confused of the missing audio, but will intuitively press the play button.

**Comment by aler9** [comment]
Thanks to #2145 it's now possible to un-mute audio by adding `?muted=0` to the URL:

```
http://localhost:8888/mystream?muted=0
```
