### ISSUE TITLE
Stream unstable when unplugging 1 usb camera

### ISSUE THREAD

**Issue by zambranohally** [bluenviron/mediamtx#1568]
## Which version are you using?

v0.21.6

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I add two usb camera and add to path for rtsp streaming. The stream is working fine until I unplug one of the camera. The other camera stream went black then stream again, went black again then stream, this is repeating scenario. When I plug the other camera it is working fine again. 

## Describe how to replicate the issue

1. Plug 2 usb cameras
2. Add it to path and 2 cameras are streaming
3. Unplug 1 of the camera

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, please provide a couple of informations that allow to replicate the issue, in particular:

* server configuration
* server logs

**Comment by aler9** [comment]
closed since author didn't provide enough data to replicate the problem.
