### ISSUE TITLE
Request for API to get single path

### ISSUE THREAD

**Issue by tbnguyen1407** [bluenviron/mediamtx#1577]
## Describe the feature

Currently there is only API to get all paths. To get a single path, the whole json needs to be parsed which gets slower and slower with increasing number of paths.

Suggestion to add an API to get just a single path so that query performance is constant regardless of number of paths.

**Comment by tbnguyen1407** [comment]
Hello, any update on this? With pagination added in v0.23.0 it is even harder to find a path using path name when there are lots of paths.

Suggestion to add

```
GET /v1/config/paths/get/$name
```

**Comment by aler9** [comment]
Hello, you are right about the API - the pagination feature was a last minute addition to a major release and I should have thought better about all the implications. I will add the /get endpoints and fix any issue ASAP.

**Comment by aler9** [comment]
Fixed in in v0.23.1
