### ISSUE TITLE
Unicam timing out - RPiCam not publishing

### ISSUE THREAD

**Issue by b3ddy** [bluenviron/mediamtx#1654]
## Which version are you using?

v i.d.k aler9/rtsp-simple-server:latest-rpi pulled 04/04/23

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [:zero:] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I'm running the latest-rpi docker image I get a warning about a mismatch between Unicam and CamHelper, and when I go to view the stream in my browser I get a 404 page not found. I also noticed when I go back to the log after requesting stream in the browser it's saying [muxer cam] destroyed (no one is publishing to path 'cam'). I turned on the legacy interface for the RPiCam and ran vcgencmd get_camera and the pi shows the cam supported and detected. Went back and turned off the legacy interface restarted the Pi and reran the docker image to only still got the same error. 
 

## Describe how to replicate the issue

start the RPi

run the container image
"docker run --rm -it \
--network=host \
--privileged \
--tmpfs /dev/shm:exec \
-v /run/udev:/run/udev:ro \
-e MTX_PATHS_CAM_SOURCE=rpiCamera \
aler9/rtsp-simple-server:latest-rpi"

## Did you attach the server logs?

yes 
![Screenshot of launch.](https://i.imgur.com/Vdje6RJ.png)

![Screenshot of full log.](https://i.imgur.com/4wsS7df.png)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, what is the output of command `libcamera-still` ?

**Comment by b3ddy** [comment]
https://i.imgur.com/6HS9k6M.png

https://i.imgur.com/5DnC0ck.png

https://i.imgur.com/MacvIkq.png

ran the libcamera-still with and without the docker container running to show both outputs. 

Other steps I've tried:
- Changing the PI config to specify IMX219 for the rpiCamv2
- turning off camera-auto-detect in the config, both setting it to =0 and # commenting out the line entirely
- enabling glamor 
- setting the GL driver to GL (Full KMS)

**Comment by aler9** [comment]
If `libcamera-still` or `libcamera-vid` don't work with your specific camera, there's nothing that can be done in the server, since the server uses the same backend (libcamera). When adding support for the camera into the server, we chose to use the libcamera backend since the legacy one is deprecated.
Contact the maintainers of libcamera and describe your issue.
