### ISSUE TITLE
Support MP4A-LATM format for audio in HLS and RTMP

### ISSUE THREAD

**Issue by wbtcpip2** [bluenviron/mediamtx#1694]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
using gstreamer as rtsp encoder h264+aac - the audio codec is not recognized from mediamtx and the hls server on port 8888 only serve the video track

## Describe how to replicate the issue

1. start the server
2. publish with gstreamer
gst-launch-1.0.exe -e videotestsrc ! mfh264enc bitrate=1024 ! video/x-h264 ! rtspclientsink name=mux location=rtsp://192.168.1.201:8554/live audiotestsrc ! audioconvert ! audioresample ! audio/x-raw, rate=48000 ! mfaacenc bitrate=128000 ! audio/mpeg ! mux.

Mediamtx log:
2023/04/12 16:13:01 DEB [RTSP] [conn 192.168.1.202:50101] [c->s] ANNOUNCE rtsp://192.168.1.201:8554/live RTSP/1.0
CSeq: 2
Content-Length: 628
Content-Type: application/sdp
Date: Wed, 12 Apr 2023 14:13:14 GMT
User-Agent: GStreamer/1.22.1.1

v=0
o=- 3736019951 1 IN IP4 192.168.1.202
s=Session streamed with GStreamer
i=rtspclientsink
t=0 0
a=tool:GStreamer
m=audio 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 MP4A-LATM/48000
a=fmtp:96 cpresent=0;config=40002310
a=control:stream=1
a=ts-refclk:local
a=mediaclk:sender
a=ssrc:3350472162 cname:user3404783220@host-19bf6e68
m=video 0 RTP/AVP 99
c=IN IP4 0.0.0.0
a=rtpmap:99 H264/90000
a=framerate:30
a=fmtp:99 packetization-mode=1;sprop-parameter-sets=Z2QAFKwrYKD9gIgAAB9AAAdTAHjhFw==,aO48sA==
a=control:stream=0
a=ts-refclk:local
a=mediaclk:sender
a=ssrc:4171762370 cname:user3404783220@host-19bf6e68

2023/04/12 16:13:03 INF [RTSP] [session 91addd57] is publishing to path 'live', with UDP, 2 tracks (Generic, H264)
2023/04/12 16:13:03 DEB [RTSP] [conn 192.168.1.202:50101] [s->c] RTSP/1.0 200 OK 

4. read with a browser ip:8888/live/ only video is server.
5. the same pipeline works fine when streaming to wowza
6. also changing codec to opus works fine on mediamtx

## Did you attach the server logs?

yes 
[mediamtx.log](https://github.com/aler9/mediamtx/files/11212430/mediamtx.log)

## Did you attach a network dump?

no

**Comment by wbtcpip2** [comment]
i have more informations about this issue

if i try with ffmpeg

ffmpeg -f lavfi -i smptebars -t 30 -f lavfi -i "sine=frequency=1000:duration=50000" -ac 2 -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -c:a aac -b:a 128k -f rtsp rtsp://localhost:8554/fflive

everything works fine and i see

2023/04/13 11:43:19 DEB [RTSP] [conn [::1]:61892] [c->s] ANNOUNCE rtsp://localhost:8554/fflive RTSP/1.0
CSeq: 2
Content-Length: 494
Content-Type: application/sdp
User-Agent: Lavf59.27.100

v=0
o=- 0 0 IN IP6 ::1
s=No Name
c=IN IP6 ::1
t=0 0
a=tool:libavformat LIBAVFORMAT_VERSION
m=video 0 RTP/AVP 96
b=AS:600
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z0LAFNoFB+wEQAAAAwBAAAAMg8UKqA==,aM48gA==; profile-level-id=42C014
a=control:streamid=0
m=audio 0 RTP/AVP 97
b=AS:128
a=rtpmap:97 MPEG4-GENERIC/44100/2
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=121056E500
a=control:streamid=1

the difference with gstreamer is 

ffmpeg = a=rtpmap:97 MPEG4-GENERIC/44100/2
gstreamer = a=rtpmap:96 MP4A-LATM/48000

would it be possibile for mediamtx accept MP4A-LATM from gstreamer?

**Comment by aler9** [comment]
Hello, as you have already noticed, there are two formats for streaming AAC through RTSP: MPEG4-generic, which is defined in RFC3640, and MP4A-LATM, which is defined in RFC6416. Both can be used for publishing and reading AAC to/from the server with RTSP, but only the former can be used to read AAC with HLS or WebRTC.
In the future, the server may be improved to support MP4A-LATM, but in the meanwhile my advice is to switch to MPEG4-generic. There's surely an option in GStreamer to perform the switch.

**Comment by aler9** [comment]
fixed in v0.23.4
