### ISSUE TITLE
Server returns 404 when using RunOnDemand sshpass to publish with a remote host

### ISSUE THREAD

**Issue by jandersonai** [bluenviron/mediamtx#1710]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

In previous versions (confirmed this works in v0.19.3 and prior) I was able to use RunOnDemand to initiate a stream through a remote host (reachable to RTSP-S-S via a VPN connection) using an sshpass ffmpeg copy command sent to the remote host to "push" the remote camera stream outside of the VPN to the Simple Server public IP address rather than pulling the stream all way back through the VPN.

This is necessary for my use case because the camera isn't directly accessible via the server, it sits in a LAN behind the remote host. Also stream performance is higher (the remote host is a cellular device) without the VPN overhead.

stdout of the remote device (ffmpeg logs) also used to come back to the Simple Server log using this method (it was great!).

EX:

[simple server] --sshpass--> [remote host] --ffmpeg copy--> [remote camera stream] --public ip--> [simple server]

source: publisher
RunOnDemand: sshpass -p redacted ssh -o StrictHostKeyChecking=no root@10.98.0.9 '/root/files/restream-1.sh'

This method no longer functions with RunOnDemand, but executing the sshpass command manually from inside the docker with exec does work.

## Describe how to replicate the issue

1. 'apk add sshpass' to the docker container during build
2. Start the server
3. Attempt to RunOnDemand launch a stream via a remote host's ffmpeg copy shell command. You'll find that the Simple Server ex: https://www.example.com:8888/test (or https://www.example.com:8888/test/index.m3u8 in an external HLS player) immediately returns '404' and the sshpass command is never sent to the remote client.

## Did you attach the server logs?

No, there's nothing interesting to find. Just '404'.

## Did you attach a network dump?

No, not necessary.

**Comment by aler9** [comment]
Hello, wrap your command into `sh -c`:

```yml
runOnDemand: sh -c "sshpass -p redacted ssh -o StrictHostKeyChecking=no root@10.98.0.9 '/root/files/restream-1.sh'"
```

The reason why it worked in previous versions is that previous versions ran external commands in the shell (sh for Alpine, bash for Ubuntu), while newer versions run external commands directly, which is faster. You can switch back to the old behavior at any time by manually launching the shell (`sh -c`).
