### ISSUE TITLE
Feature suggestion: Fallback - proxy streams instead of sending 301

### ISSUE THREAD

**Issue by sgofferj** [bluenviron/mediamtx#1730]
## Describe the feature

At the moment, fallback simply sends a 301 Moved permanently if a stream is not available.

I would like to suggest to change this (configurably) to internal handling and redirecting of the stream, i.e. don't send a 301 but transparently proxy the fallback stream to the uri.
My main reason for the request is that if a client receives a 301, it won't try again. Some clients might even cache the 301. Transparently proxying gives a more seamless experience as the fallback would be replaced immediately if anybody would publish to the uri and come back immediately once the publishing ends.

**Comment by aler9** [comment]
replaced by the more versatile #2214
