### ISSUE TITLE
ECONNREFUSED when calling api from node.js script

### ISSUE THREAD

**Issue by deyceg** [bluenviron/mediamtx#1733]
## Which version are you using?

v0.22.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [X] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am trying to call the api from a node.js script but for some reason any http library I use results in a ECONNREFUSED error.

I can successfully `curl` from the terminal as well as `curl` using a child process so it is not a problem of connectivity.

I can also use the http library for other urls without error.

There is a a known issue with node.js v17+ whereby you need to use `127.0.0.1` instead of `localhost` to hint ipv4 though in all examples the workaround is being used.

## Describe how to replicate the issue

1. start the server with `api: yes`
2. `curl -v http://127.0.0.1:9997/v1/paths/list` -> PASS
3. `await axios.get("http://127.0.0.1:9997/v1/paths/list");` -> FAIL
4. ` await axios.get("https//www.google.com");` -> PASS
5. `exec("curl -v http://127.0.0.1:9997/v1/paths/list");` -> PASS

## Did you attach the server logs?

no - nothing relevant in logs

## Did you attach a network dump?

no - all inside docker container

**Comment by deyceg** [comment]
Actually I think this related to `puppeteer` shimming the underlying http agent. Will report back once I've managed to do some more testing.

**Comment by aler9** [comment]
not a server issue.
