### ISSUE TITLE
Feature suggestion: runOnUnready

### ISSUE THREAD

**Issue by sgofferj** [bluenviron/mediamtx#1735]
## Describe the feature

I'd like to suggest a runOnUnready configuration directive which triggers when a stream that was ready becomes unready, i.e. the publisher has stopped publishing to the path. The purpose for that would be to enable calls to webhooks or similar if a stream becomes unavailable, e.g.
```
runOnReady: curl -X POST -d "$RTSP_PATH" http://server/api/start
runOnUnready: curl -X POST -d "$RTSP_PATH" http://server/api/stop
```

**Comment by aler9** [comment]
duplicate of #1464
