### ISSUE TITLE
Feature request - raspberry pi camera <1fps

### ISSUE THREAD

**Issue by skaface** [bluenviron/mediamtx#1743]
## Describe the feature

I am fairly certain the raspberry pi camera can be set to capture at less than 1fps. Is this a feature that can possibly be implemented to capture low frame rate and high exposure video at night? At the moment the lowest framerate that can be set is 1fps

**Comment by aler9** [comment]
Hello, i changed the FPS type from integer to decimal (float); in this way it should be possible to use a decimal number as FPS, for example 0.5, 0.3, 0.2, etc.
FPS is passed to libcamera. I don't know if libcamera supports FPS lower than 1 fps, but anyway, this is all we can do here.

**Comment by aler9** [comment]
I tested the fix with a Raspberry Camera, and FPS lower than 1 are working.

**Comment by aler9** [comment]
fixed in v0.23.4
