### ISSUE TITLE
Add Docker ffmpeg tags

### ISSUE THREAD

**Issue by alpe12** [bluenviron/mediamtx#1771]
## Describe the feature

Can you add an nightly docker tag with faster updates?
The last update on docker was 21 days ago. And a few days ago a commit was made which I think may fix an issue I'm having.

An ffmpeg tag that included ffmpeg would be nice too.

Thanks anyway.

**Comment by aler9** [comment]
Hello @alpe12, i can't add nightly docker tags since Docker Hub has limits on the overall size of images, but i will add FFmpeg tags.

**Comment by alpe12** [comment]
Thanks.
