### ISSUE TITLE
cant use full resolution of pi fisheye cam

### ISSUE THREAD

**Issue by Avatarsia** [bluenviron/mediamtx#1802]
## Which version are you using?
v0.22.2

## Which operating system are you using?
- [x ] Linux arm64 standard

## Describe the issue
I cant get an uncropped immage

## Describe how to replicate the issue

                   **Camera Identification**
$ libcamera-raw --list-cameras
0 : ov5647 [2592x1944] (/base/soc/i2c0mux/i2c@1/ov5647@36)
    Modes: 'SGBRG10_CSI2P' : 640x480 [58.92 fps - (16, 0)/2560x1920 crop]
                             1296x972 [43.25 fps - (0, 0)/2592x1944 crop]
                             1920x1080 [30.62 fps - (348, 434)/1928x1080 crop]
                             2592x1944 [15.63 fps - (0, 0)/2592x1944 crop]

                           **ISSUE**
with 1920x1080 i get an cropped immage and a running stream 
with 2592x1944 i get an uncropped image with 
sudo libcamera-jpeg -o test.jpg -t 2000 --width 2592 --height 1944
but when i write the resolution into the configuration the log always look like this 
                                            
                                         **Part of the log**
May 16 15:22:08 lasercam mediamtx[3236]: [0:38:56.626977640] [3236]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
May 16 15:22:08 lasercam mediamtx[3236]: [0:38:56.694090911] [3237]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media0 and ISP devi>
May 16 15:22:08 lasercam mediamtx[3236]: [0:38:56.694937183] [3236]  INFO Camera camera.cpp:1028 configuring streams: (0) 2592x1944-YUV420
May 16 15:22:08 lasercam mediamtx[3236]: [0:38:56.695219978] [3237]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/ov5647@36 - Selected sensor format: 2592x1944-SGBRG10_1X10 - S>
May 16 15:22:08 lasercam mediamtx[3127]: 2023/05/16 15:22:08 INF [path cam] [rpicamera source] ERR: encoder_create(): unable to activate output stream
May 16 15:22:13 lasercam mediamtx[3240]: [0:39:01.799829514] [3240]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
May 16 15:22:13 lasercam mediamtx[3240]: [0:39:01.849606796] [3242]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media0 and ISP devi>
May 16 15:22:13 lasercam mediamtx[3240]: [0:39:01.850459957] [3240]  INFO Camera camera.cpp:1028 configuring streams: (0) 2592x1944-YUV420
May 16 15:22:13 lasercam mediamtx[3240]: [0:39:01.850742178] [3242]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/ov5647@36 - Selected sensor format: 2592x1944-SGBRG10_1X10 - S>
May 16 15:22:13 lasercam mediamtx[3127]: 2023/05/16 15:22:13 INF [path cam] [rpicamera source] ERR: encoder_create(): unable to activate output stream

## Did you attach the server logs?
partly above

## Did you attach a network dump?
no

edit found in the syslog 

May 16 15:37:38 lasercam kernel: [ 3266.802779] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -3

**Comment by aler9** [comment]
Hello, this is not a server issue. Raspberry Pis can't encode in H264 streams with a resolution greater than 1080p, it's an hardware limitation that will probably be overcome when the next model cames out. However, you can set `rpiCameraMode` with your desired sensor resolution and downscale it to 1080p:

```yml
paths:
  cam:
    source: rpiCamera
    rpiCameraWidth: 1920
    rpiCameraHeight: 1080
    rpiCameraMode: '2592:1944'

```

**Comment by Avatarsia** [comment]
![image](https://github.com/bluenviron/mediamtx/assets/43354003/f303348a-85bf-4a1a-be93-9b06b1515677)
left side the taken picture, right side the stream. 
i need it like left side

**Comment by aler9** [comment]
Parameters that can be set in the server are the same of the ones requested by libcamera-vid. If your video can't be produced with libcamera-vid, nothing can be done here.
