### ISSUE TITLE
Response pageCount is incorrect

### ISSUE THREAD

**Issue by tbnguyen1407** [bluenviron/mediamtx#1813]
## Which version are you using?

v0.23.0

## Which operating system are you using?

- [x] Windows amd64 standard

## Describe the issue

Page count is incorrect when `itemsPerPage` is smaller or equal to total number of items

## Describe how to replicate the issue

1. start the server
2. add 3 paths
3. call `/v1/paths/list?itemsPerPage=X`
    - X=1 -> pageCount=4  ## wrong, should be 3
    - X=2 -> pageCount=2  ## right
    - X=3 -> pageCount=2  ## wrong, should be 1
    - X=4 -> pageCount=1  ## right
    - X>=4 -> pageCount=1  ## right

## Did you attach the server logs?

no

## Did you attach a network dump?

no

## Notes

For pagination it is more common to return total item count instead of total page count and let the client side figure out the total page count. It is currently not possible to know how many paths there are in total.

Client side needs:

- Page index (from request/response)
- Page size (from request/response)
- Total item count (from response)

Common practice is to return pagination in response header, e.g.:

```
X-Pagination-Page-Index
X-Pagination-Page-Size
X-Pagination-Total-Count  ## item count not page count
```

**Comment by aler9** [comment]
Fixed in in v0.23.1
