### ISSUE TITLE
Slow ll-HLS

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#1814]
## Which version are you using?

v0.22.2 and v0.23.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (Linux amd64 LXC)

## Describe the issue

when receiving an LLHLS stream in the browser with a playlist(need for ios/android app and VLC player) specified, the stream is given with a long delay (5-10 seconds) - **https://ip:port/path/index.m3u8** (**https://ip:port/path/stream.m3u8**)

if i receiving in the browser without set playlist(index.m3u8/stream.m3u8), the stream is given fast(1-2 seconds) - **https://ip:port/path/**

## Describe how to replicate the issue

1. start the server
2. publish with rtsp
3. read with browser(safari/chrome/firefox) or player(vlc) use path https://ip:port/path/index.m3u8(https://ip:port/path/stream.m3u8).

## Did you attach the server logs?

yes / **no**

## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
Hello, this is not a server issue. In order for a client to read a LL-HLS stream, it must support LL-HLS. Otherwise, it switches back to standard HLS, which has a higher latency.

Check that your library or client supports LL-HLS.

**Comment by pikachu937** [comment]
Hm. it not logical. if i set playlist in browser, then hls isn't low latency, if i don't set playlist in browser, then i have low latency. why?? last testing on browser safari(mac os ventura), it support low latency hls by default

**Comment by aler9** [comment]
The web page used inside the server makes use of hls.js, which is a client that supports LL-HLS.

The only browser that natively supports HLS playlists is Safari, i don't know whether it supports LL-HLS or not, but it probably requires encryption as described in the README, in the section about HLS and iOS.

**Comment by pikachu937** [comment]
encryption already enable. if you have mac os, you can test any stream **https://ip:port/path/index.m3u8** and ** https://ip:port/path/** an you can see that first link have slowly stream and second link fast
