### ISSUE TITLE
WEBRTC v0.23.0. error: webrtcICEHostNAT1To1IPs doesn't work if webrtcICEServers is empty

### ISSUE THREAD

**Issue by alpe12** [bluenviron/mediamtx#1817]
## Which version are you using?

v0.23.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [x] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Ever since this update the WEBRTC stream stopped working.
I open http://192.168.1.250:8889/cam/ and in the console:
```
requesting ICE servers
error: TypeError: links is null
```

Looking at the "networks" tab it constantly tries to access /cam/whep which return code 200 but with empty response. If i open /cam/whep directly I get 404.

## Describe how to replicate the issue
                                                         
   
                      
                               
   

[mediamtx.yml](https://pastebin.com/qLnUuU7b)
[docker-compose.yml](https://pastebin.com/XtHprFW8)

## Did you attach the server logs?

[here](https://pastebin.com/iTuLpnVk)

## Did you attach a network dump?
  

no

**Comment by alpe12** [comment]
Update:
If I add
`webrtcICEServers: [stun:stun.l.google.com:19302]`
it works. Before it worked with [] in it.
I used to use [] on it because it leaked the public IP when it was not necessary for the client.
Does the current implementation prevents it?
If no, please make it work with [] as before, using only webrtcICEHostNAT1To1IPs: [192.168.1.250]

**Comment by aler9** [comment]
Fixed in in v0.23.1
