### ISSUE TITLE
[0.23.1 WebRTC-WHIP] It cannot work in the LAN. using chrome of pc or Android phone to push stream to the server.

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#1836]
## Which version are you using?

v0.23.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

[0.23.1 WebRTC-WHIP] It cannot work in the LAN. using chrome of pc or Android phone to push stream to the server.

## Describe how to replicate the issue

1. start the server
2. publish with Chrome of on another pc by LAN: http://192.168.10.11:8889/mystream/publish
3. it cannot work on chrome of pc or Android phone

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by iesv** [comment]
sir, there is no log at all. it does not show info in console.

**Comment by aler9** [comment]
Without server logs or any additional information it's not possible to replicate the issue.

**Comment by UnKnoWn-Consortium** [comment]
You need HTTPS for WebRTC to work.

**Comment by iesv** [comment]
> You need HTTPS for WebRTC to work.

Thank you very much! It works now even if it is not perfect.
![Uploading Screenshot_20230717-143933.png…]()

**Comment by UnKnoWn-Consortium** [comment]
You are welcome. Glad it works. 

Yeah the interface does require some extra work. Pull requests are welcomed. Though it is not that hard to DIY your own by referring to the [source code of the page](https://github.com/bluenviron/mediamtx/blob/main/internal/core/webrtc_publish_index.html).

**Comment by aler9** [comment]
I'll edit the default publish page in order to display an error whether device sharing is not allowed due to the fact that host is different than `localhost` and HTTPS is not enabled.

**Comment by iesv** [comment]
> I'll edit the default publish page in order to display an error whether device sharing is not allowed due to the fact that host is different than `localhost` and HTTPS is not enabled.

Thank you aler9 so so much!!!

**Comment by aler9** [comment]
added in v0.23.8
