### ISSUE TITLE
high load

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#1851]
## Which version are you using?

v0.23.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (Debian LXC)

## Describe the issue

If you set the
```yaml
runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-% S.ts
```
, then the load on the server increases (load average 6.12 6.30 6.05), memory and processor consumption rise to 30% -40%.

 but if you run ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%S.ts separately for each thread in the background, then the values of load average 0.40 0.37 0.35, processor and memory are not rises above 7%.

PS. 300 streams on the server

## Describe how to replicate the issue

1. start the server
2. set runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-% S.ts
3. publish with rtsp
4. check load

## Did you attach the server logs?

yes / **no**

## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
hello, the only thing that comes to my mind is that maybe there's some load involved in processing and displaying log lines of all FFmpeg instances, since log lines are written sequentially to the terminal. Try disabling FFmpeg output:

```yml
paths:
  all:
    runOnReady: ffmpeg -loglevel error -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -c copy -f segment -strftime 1 -segment_time 60 -segment_format mpegts saved_%Y-%m-%d_%H-%M-%.ts
```

Other than that, i tested FFmpeg inside and outside `runOnReady`, and it consumed exactly the same.

**Comment by aler9** [comment]
closed since no additional feedback was provided.
