### ISSUE TITLE
BUG: paths/all configurations don't apply to paths created by HTTP API

### ISSUE THREAD

**Issue by hu-xd** [bluenviron/mediamtx#1853]
## Which version are you using?

v0.23.2
it seems like v0.22.2 didn't have this problem

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

if a path is created by HTTP API /v2/config/paths/add/{name}
the config of this path is initialized as default values, ignoring the config in the paths/all section in the .yml file
especially, the sourceOnDemandStartTimeout are 0s, this makes the path essentially unusable,
since the source connection is closed immediately after connected

## Describe how to replicate the issue

1. start the server
2. create a path using HTTP API /v2/config/paths/add/test
{ “source”: "rtsp://......" }
3. read paths info with HTTP API /v2/paths/list
4. see the sourceOnDemandStartTimeout config of "test" is 0s
5. open mediamtx.yml file
6. see the sourceOnDemandStartTimeout config under paths/all section is 10s

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, config parameters under path "all" are not applied to other paths, as mentioned in the configuration file:

> The settings under the path "all" are applied to all paths that do not match another entry.

Nonetheless, `sourceOnDemandStartTimeout: 10s` and all other default parameters should be applied to API-created paths too, while they are not, and this is a bug.

**Comment by aler9** [comment]
fixed in v0.23.4
