### ISSUE TITLE
If one source url is disconnected, other proxy stream stop publishing

### ISSUE THREAD

**Issue by sharmasulekh87** [bluenviron/mediamtx#1866]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am running around 30 -40 proxy streams from rtsp urls of IP Cameras. But if one of the source camera is disconnected, the remaining proxy stream also stops publishing.

## Describe how to replicate the issue

1. start the server
2. publish with 30 rtsp urls.
3. randomly disconnect one of the source.
4. the server will start giving timeout error and i am unable to receive any of the other proxy stream as well

## Did you attach the server logs?

**yes** / no
[rtsp-simple-server.zip](https://github.com/bluenviron/mediamtx/files/11581861/rtsp-simple-server.zip)
## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
Hello, i took a look at the logs, i don't think this issue has something to do with the server, it looks related to your VPN.
Make sure to use the latest version and check that the network routes are still working when you disconnect a camera.
