### ISSUE TITLE
Capture HDR video

### ISSUE THREAD

**Issue by dominikstupka** [bluenviron/mediamtx#1876]
## Describe the feature

Hi, with camera module 3, it is possible to take HDR images and videos. The libcamera library enables HRD acquisition by calling the --hdr flag. It is possible to add this flag to mediamtx.yml

**Comment by aler9** [comment]
https://github.com/raspberrypi/libcamera-apps/blob/a6267d51949d0602eedf60f3ddf8c6685f652812/core/options.cpp#L101

**Comment by aler9** [comment]
added in v0.23.8
