### ISSUE TITLE
The application does not release memory

### ISSUE THREAD

**Issue by redipaul** [bluenviron/mediamtx#1884]
## Which version are you using?

v0.23.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The application does not release memory when disconnecting and switching WebRTC streams.
Version 0.22.2 did not have this problem.

## Describe how to replicate the issue

1. start the server
2. publish with Proxy mode several rtsp ip-cams
3. read with Google Chrome http://localhost:8889/proxied_XXX

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, by "disconnecting and switching WebRTC streams" you mean connecting and disconnecting multiple WebRTC readers?

How did you come to the conclusion that memory is not released? how many readers are needed to saturate memory?

**Comment by redipaul** [comment]
I opened and closed webrtc link in the browser and watched the process memory in the task manager:
1. 8 700K - first run, no active streams
2. 17 500K - the first active stream
3. 17 800K - client closed, no active streams
4. 22 350K - the 2nd active stream
5. 22 340K - client closed, no active streams
6. 26 550K - the 3nd active stream
7. 26 640K - client closed, no active streams
...
step N. ~2GB - all clients closed, no active streams
Sometimes I opened and closed several webrts links at once and the process memory grew faster.
Version 0.22.2 freed memory almost immediately.

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #1983

**Comment by aler9** [comment]
added in v0.23.7

**Comment by redipaul** [comment]
Problem solved. Thank you!
