### ISSUE TITLE
Allow longer intervals between keyframes before emitting a warning

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#1904]
## Describe the feature

https://github.com/bluenviron/mediamtx/pull/1825#issuecomment-1553763689

**Comment by stevedanomodolor** [comment]
How do we test this @aler9 ?, I am having the same issue.

**Comment by aler9** [comment]
After some reasoning it was decided to remove the warning message since it causes more problems than the ones it solves.

Long intervals between key frames are not a problem in HLS since current key frame is always available in the last segment.

Long intervals between key frames will not be a problem in WebRTC / SRT / RTMP when #1209 will be implemented.
