### ISSUE TITLE
Bad audio quality when using WebRTC publisher

### ISSUE THREAD

**Issue by zapf2000** [bluenviron/mediamtx#1908]
## Describe the feature

When publishing AV1 video via WebRTC the Opus sound is very bad.
It would be great if the audio bitrate can also be defined in web publisher.

**Comment by aler9** [comment]
Hello, after meddling around with the WebRTC handshake i was able to force Opus to use the full band and respect a certain average bitrate. I used Chrome throughout the test.
I developed a patch (#1985), please test it by using this nightly release and let me know if it works:

[mediamtx_v0.23.6-8-g982f882_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857734/mediamtx_v0.23.6-8-g982f882_darwin_amd64.tar.gz)
[mediamtx_v0.23.6-8-g982f882_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857735/mediamtx_v0.23.6-8-g982f882_darwin_arm64.tar.gz)
[mediamtx_v0.23.6-8-g982f882_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857737/mediamtx_v0.23.6-8-g982f882_linux_amd64.tar.gz)
[mediamtx_v0.23.6-8-g982f882_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/11857738/mediamtx_v0.23.6-8-g982f882_linux_arm64v8.tar.gz)
[mediamtx_v0.23.6-8-g982f882_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/11857739/mediamtx_v0.23.6-8-g982f882_linux_armv6.tar.gz)
[mediamtx_v0.23.6-8-g982f882_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/11857740/mediamtx_v0.23.6-8-g982f882_linux_armv7.tar.gz)
[mediamtx_v0.23.6-8-g982f882_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/11857741/mediamtx_v0.23.6-8-g982f882_windows_amd64.zip)

**Comment by zapf2000** [comment]
> Hello, after meddling around with the WebRTC handshake i was able to force Opus to use the full band and respect a certain average bitrate. I used Chrome throughout the test. I developed a patch (#1985), please test it by using this nightly release and let me know if it works:
> 
> [mediamtx_v0.23.6-8-g982f882_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857734/mediamtx_v0.23.6-8-g982f882_darwin_amd64.tar.gz) [mediamtx_v0.23.6-8-g982f882_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857735/mediamtx_v0.23.6-8-g982f882_darwin_arm64.tar.gz) [mediamtx_v0.23.6-8-g982f882_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11857737/mediamtx_v0.23.6-8-g982f882_linux_amd64.tar.gz) [mediamtx_v0.23.6-8-g982f882_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/11857738/mediamtx_v0.23.6-8-g982f882_linux_arm64v8.tar.gz) [mediamtx_v0.23.6-8-g982f882_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/11857739/mediamtx_v0.23.6-8-g982f882_linux_armv6.tar.gz) [mediamtx_v0.23.6-8-g982f882_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/11857740/mediamtx_v0.23.6-8-g982f882_linux_armv7.tar.gz) [mediamtx_v0.23.6-8-g982f882_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/11857741/mediamtx_v0.23.6-8-g982f882_windows_amd64.zip)

Hi and thank you for your work.
I tested the enhancement in various scenarios. The quality is still very bad. It seems that echo cancelling option for webrtc is enabled by default. That causes music sound very bad. Here are some screenshots:

![publish settings](https://github.com/bluenviron/mediamtx/assets/52130927/9b8d9096-bc5f-4f1a-9ec5-50275e1ad63b)
![player properties](https://github.com/bluenviron/mediamtx/assets/52130927/62f910c4-58d3-4ba0-8ece-00d131fcce34)
![audio properties](https://github.com/bluenviron/mediamtx/assets/52130927/efeaa27a-9d42-4202-b1eb-080b72901283)

Perhaps it's neccessary to add some additional configuration options for audio publishing and playing.

**Comment by aler9** [comment]
I'll add an option for disabling audio effects too. 

Meanwhile, please confirm that setting audio bitrate works as expected, you can check audio bitrate by opening about://webrtc-internals and checking tab "stats for outgoing stream, media=audio".

**Comment by zapf2000** [comment]
Yes, I can confirm that the bitrate is set correctly for outbound-rtp audio. Works fine. I think the bad quality is related to enabled effects.

**Comment by aler9** [comment]
i've added the option:

[mediamtx_v0.23.6-9-g972cd58_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11866894/mediamtx_v0.23.6-9-g972cd58_darwin_amd64.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/11866898/mediamtx_v0.23.6-9-g972cd58_darwin_arm64.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11866901/mediamtx_v0.23.6-9-g972cd58_linux_amd64.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/11866905/mediamtx_v0.23.6-9-g972cd58_linux_arm64v8.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/11866908/mediamtx_v0.23.6-9-g972cd58_linux_armv6.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/11866915/mediamtx_v0.23.6-9-g972cd58_linux_armv7.tar.gz)
[mediamtx_v0.23.6-9-g972cd58_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/11866920/mediamtx_v0.23.6-9-g972cd58_windows_amd64.zip)

**Comment by zapf2000** [comment]
> 

This seems to be solved. Sound is much better now. But there is a new issue with AV1 Video playback or encoding.
Have a look at the video. Every 2 seconds, there seems to be a short interrupt. Looks like he tries to scale or re-scale. 
Also a problem on video: It does not playback on Chrome mobile devices, but AV1 is definitely supported (I tried in webm container with icecast server before). Perhaps the wrong AV1 encoding model is chosen by default. There are several ones, but not all supported by mobile devices.

https://github.com/bluenviron/mediamtx/assets/52130927/b0f26171-4094-47ce-ae8f-eccdca9085b9

**Comment by aler9** [comment]
Regarding the AV1 bug, open a new issue, specify whether it's a regression or not and provide replication details.
Furthermore, i've moved all codec selection-related code to client side, hence it should be really easy to hack the code and change things such as the AV1 profile.

**Comment by aler9** [comment]
added in v0.23.7
