### ISSUE TITLE
webrtc read (whep) username:password inline in url fails

### ISSUE THREAD

**Issue by saket424** [bluenviron/mediamtx#1919]
## Which version are you using?

v0.23.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

whep not working when username:password specified inline with URL

Playing of this url in the browser https://username:password@example.io:8889/endpoint1 results in the following error

(index):112 error: TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: whep

Before whep, this webrtc scenario where url contains username:password worked fine in google chrome

## Describe how to replicate the issue

1. start the server
2. publish with rtsp
3. read with webrtc over whep using username:password

## Did you attach the server logs?

yes 
(index):112 error: TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: whep

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #1966

**Comment by aler9** [comment]
added in v0.23.6
