### ISSUE TITLE
libcamera.so not recognized

### ISSUE THREAD

**Issue by baloghzipbier** [bluenviron/mediamtx#1940]
## Which version are you using?

v0.23.5

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (Yocto arm7 based on meta-rpi )

## Describe the issue
My issue is when I start the app, i have this error:
ERR: libcamera is 64-bit, you need the 64-bit server version

I found what is causing, the "findLibrary" function checks the url with ldconfig is that contains the "arm-linux-gnueabihf" part.
https://github.com/bluenviron/mediamtx/blob/21756a4d54152872cda48469861147ee652df922/internal/rpicamera/rpicamera.go#L89
With the v0.22.0 my yocto environment works(without the check). Maybe we can check that somehow else is this an 32bit or 64bit OS?

my ldconfig -p is contains this
`libcamera.so.0.0.4 (libc6) => /usr/lib/libcamera.so.0.0.4`
`libcamera-base.so.0.0.4 (libc6) => /usr/lib/libcamera-base.so.0.0.4`

## Did you attach the server logs?
no
## Did you attach a network dump?
no

**Comment by aler9** [comment]
Hello, due to #1644, the 32/64 bit check has to be performed on the library, not elsewhere. We can certainly find a better way to do it than checking the path name, for instance by analyzing the ELF header of the library, that may contain the 32/64 bit information.

**Comment by aler9** [comment]
I've moved the 64 bit check from the path to the ELF header of the library, please test this nightly release and confirm that the fix works:

[mediamtx_v0.23.6-12-g15d524a_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11887745/mediamtx_v0.23.6-12-g15d524a_darwin_amd64.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/11887746/mediamtx_v0.23.6-12-g15d524a_darwin_arm64.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/11887750/mediamtx_v0.23.6-12-g15d524a_linux_amd64.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/11887753/mediamtx_v0.23.6-12-g15d524a_linux_arm64v8.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/11887758/mediamtx_v0.23.6-12-g15d524a_linux_armv6.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/11887760/mediamtx_v0.23.6-12-g15d524a_linux_armv7.tar.gz)
[mediamtx_v0.23.6-12-g15d524a_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/11887762/mediamtx_v0.23.6-12-g15d524a_windows_amd64.zip)

**Comment by aler9** [comment]
added in v0.23.7
