### ISSUE TITLE
time parsing error when reading metadata from owncast hls stream

### ISSUE THREAD

**Issue by Miningpro362** [bluenviron/mediamtx#1958]
## Which version are you using?

v0.23.5

## Which operating system are you using?

- [x] Linux amd64 standard

## Describe the issue

Description

## Describe how to replicate the issue

1. configure mediamtx to have a path that gets an hls stream from an owncast server (which is <SERVER_URL>/hls/stream.m3u8
2. start mediamtx and observe logs.
3. mediamtx gives something along the lines of `INF [path uwu] [hls source] ERR: parsing time "2023-06-16T21:08:02.686-0400" as "2006-01-02T15:04:05.999Z07:00": cannot parse "-0400" as "Z07:00"` every five seconds.

## Did you attach the server logs?

no

## Did you attach a network dump?

the dump is available [here](https://hhsys.s-ul.eu/AzEFy3vv.pcap) since gh won't let me attach it

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by https://github.com/bluenviron/gohlslib/pull/50
