### ISSUE TITLE
runOnDisconnect or runOnEnd paramter

### ISSUE THREAD

**Issue by pantherale0** [bluenviron/mediamtx#1986]
## Describe the feature

I would like an option to run a script after all clients have disconnected from a string (in essence, start a service on connect, end the service on disconnect)

**Comment by aler9** [comment]
You can already do this by using unix signals: https://github.com/bluenviron/mediamtx/issues/1352#issuecomment-1371408078

If you want a more user-friendly solution, this is being already tracked here: #1464
