### ISSUE TITLE
Text overlay of timestamp on rtsp/rtsps stream

### ISSUE THREAD

**Issue by lchy12345** [bluenviron/mediamtx#1988]
## Describe the feature

Description
hi, i saw that it is possible to add text overlay to rpi camera. is it possible to apply to rtsp stream? or how can i apply it to rtsp stream?
Thanks so much

**Comment by aler9** [comment]
Hello, this can be done with GStreamer of FFmpeg and has already been answered here:

https://github.com/bluenviron/mediamtx/discussions/1660#discussioncomment-5552039
