### ISSUE TITLE
mediamtx is unable to find the configuration file when installing from AUR

### ISSUE THREAD

**Issue by Managor** [bluenviron/mediamtx#1993]
## Which version are you using?

v0.23.6-1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [X] Other (please describe)
Arch Linux x86_64 standard

## Describe the issue

Description

## Describe how to replicate the issue

1. Install mediamtx from AUR
2. run mediamtx
3. Receive warning `WAR configuration file not found, using an empty configuration`

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
fixed in v1.1.0
