### ISSUE TITLE
SourceOnDemand true not accepted 

### ISSUE THREAD

**Issue by pk1057** [bluenviron/mediamtx#2019]
## Which version are you using?

v0.23,7

## Which operating system are you using?

- [ X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I try to create an rtsp stream proxy with sourceOnDemand: true via api and i get allways response Code 400

## Describe how to replicate the issue
run a server with api enabled
A simple python script like:

`
import json
import requests

data = {'source': 'rtsp://root:axis@192.168.10.3:554/media.src'}
json_data = json.dumps(data)
print(json_data)

headers = {'Content-type': 'application/json'}
response = requests.post('http://localhost:9997/v2/config/paths/remove/pm1/cam199', headers=headers)
print("1->",response)

response = requests.post('http://localhost:9997/v2/config/paths/add/pm1/cam199', data=json_data, headers=headers)

print("2->",response)

data = {'sourceOnDemand': 'true'}
json_data = json.dumps(data)
print(json_data)
response = requests.post('http://localhost:9997/v2/config/paths/edit/pm1/cam199', data=json_data, headers=headers)
print("3->",response)
`

## Did you attach the server logs?

This leads to errors like:

mediamtx[432919]: 2023/07/04 14:32:09 DEB [API] [conn 127.0.0.1:41722] POST /v2/config/paths/edit/pm1/cam199
mediamtx[432919]: 2023/07/04 14:32:09 DEB [API] [conn 127.0.0.1:41722] [c->s] POST /v2/config/paths/edit/pm1/cam199 HTTP/1.1#015#012Host: localhost:9997
#015#012Accept: */*#015#012Accept-Encoding: gzip, deflate#015#012Connection: keep-alive#015#012Content-Length: 26#015#012Content-Type: application/json#015#012User-Agent: python-requ
ests/2.22.0#015#012#015#012{"sourceOnDemand": "true"}
mediamtx[432919]: 2023/07/04 14:32:09 DEB [API] [conn 127.0.0.1:41722] [s->c] HTTP/1.1 400 Bad Request#012Server: mediamtx#015#012#012

Or when i pack creation and sourceOnDemand in one json the same;

mediamtx[432919]: 2023/07/04 14:36:11 DEB [API] [conn 127.0.0.1:37116] [c->s] POST /v2/config/paths/add/pm1/cam01 HTTP/1.1#015#012Host: localhost:9997#0
15#012Accept: */*#015#012Accept-Encoding: gzip, deflate#015#012Connection: keep-alive#015#012Content-Length: 150#015#012Content-Type: application/json#015#012User-Agent: python-reque
sts/2.22.0#015#012#015#012{"source": "rtsp://192.168.10.2:554/media.amp", "sourceOnDemand": "true"}
Jul  4 14:36:11 Teleoperation mediamtx[432919]: 2023/07/04 14:36:11 DEB [API] [conn 127.0.0.1:37116] [s->c] HTTP/1.1 400 Bad Request#012Server: mediamtx#015#012#012

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Hello, `sourceOnDemand` is a boolean, not a string, replace `'true'` with `True`:

```python
import json
import requests

data = {'source': 'rtsp://root:axis@192.168.10.3:554/media.src'}
json_data = json.dumps(data)
print(json_data)

headers = {'Content-type': 'application/json'}
response = requests.post('http://localhost:9997/v2/config/paths/remove/pm1/cam199', headers=headers)
print("1->",response)

response = requests.post('http://localhost:9997/v2/config/paths/add/pm1/cam199', data=json_data, headers=headers)

print("2->",response)

data = {'sourceOnDemand': True}
json_data = json.dumps(data)
print(json_data)
response = requests.post('http://localhost:9997/v2/config/paths/edit/pm1/cam199', data=json_data, headers=headers)
print("3->",response)
```
