### ISSUE TITLE
Artefacts on RTSP stream from rpiCamera

### ISSUE THREAD

**Issue by bigbeka** [bluenviron/mediamtx#2030]
## Which version are you using?

v0.23.6

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
Running mediamtx on Raspberry Pi Zero W 2 with Raspberry Pi Camera V3 - Wide angle (Tested both RTSP and WebRTC feeds)
Where the feed is normal when camera and the objects in the frame are still.
As soon as the objects in the frame or the camera is moved, the artefacts start appearing (see sample recording attached).

## Describe how to replicate the issue

1. start the server
2. publish with RTSP or WebRTC
3. read with VLC on MacOS or reach with `datarhei/restreamer`

## Did you attach the server logs?

yes: [mediamtx.log](https://github.com/bluenviron/mediamtx/files/11968880/mediamtx.log)

## Did you attach a network dump?
no

https://github.com/bluenviron/mediamtx/assets/53529055/8897c568-484c-43ea-9a1d-4da6adf3cda6

**Comment by aler9** [comment]
short answer: decrease the camera bitrate since your network is not able to handle it. Otherwise you can try to switch to TCP. There's a section in the README about corrupted frames: https://github.com/bluenviron/mediamtx#corrupted-frames
