### ISSUE TITLE
readUser and readPass doesnt work ?

### ISSUE THREAD

**Issue by xmaxmex** [bluenviron/mediamtx#2042]
## Which version are you using?

v0.23.5

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Using this config, the strem plays auto without authentication..
  cam1:
          readIPs: []
          readUser: xmaxmex
          readPass: user123
          runOnInit: camera.sh
          runOnInitRestart: yes

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?
2023/07/10 11:09:19 INF MediaMTX v0.23.5
2023/07/10 11:09:19 INF [metrics] listener opened on 127.0.0.1:9998
2023/07/10 11:09:19 INF [pprof] listener opened on 127.0.0.1:9999
2023/07/10 11:09:19 DEB [path cam1] created
2023/07/10 11:09:19 DEB [path cam_user1] created
2023/07/10 11:09:19 INF [path cam1] runOnInit command started
2023/07/10 11:09:19 DEB path manager created
2023/07/10 11:09:19 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/07/10 11:09:19 INF [RTMP] listener opened on :1935
2023/07/10 11:09:19 INF [HLS] listener opened on :8888
2023/07/10 11:09:19 INF [WebRTC] listener opened on :8889 (HTTP)
2023/07/10 11:09:19 INF [API] listener opened on 127.0.0.1:9997
2023/07/10 11:09:21 INF [RTSP] [conn 127.0.0.1:34792] opened
2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [c->s] OPTIONS rtsp://localhost:8554/vip1 RTSP/1.0
CSeq: 1
User-Agent: Lavf58.29.100

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [c->s] ANNOUNCE rtsp://localhost:8554/vip1 RTSP/1.0
CSeq: 2
Content-Length: 506
Content-Type: application/sdp
User-Agent: Lavf58.29.100

v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Server
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.29.100
m=video 0 RTP/AVP 96
b=AS:4000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAHqyyAWB7YCIAAAMAAgAAAwAoHixckA==,aOvMsiw=; profile-level-id=64001E
a=control:streamid=0
m=audio 0 RTP/AVP 97
b=AS:128
a=rtpmap:97 MPEG4-GENERIC/44100/2
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=121056E500
a=control:streamid=1

2023/07/10 11:09:21 INF [RTSP] [session d5543c6a] created by 127.0.0.1:34792
2023/07/10 11:09:21 DEB [path vip1] created
2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [s->c] RTSP/1.0 200 OK
CSeq: 2
Server: gortsplib

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [c->s] SETUP rtsp://localhost:8554/vip1/streamid=0 RTSP/1.0
CSeq: 3
Transport: RTP/AVP/UDP;unicast;client_port=5570-5571;mode=record
User-Agent: Lavf58.29.100

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [s->c] RTSP/1.0 200 OK
CSeq: 3
Server: gortsplib
Session: b2aa0ab9f50a4e25b3dfe17f3fbff552
Transport: RTP/AVP;unicast;client_port=5570-5571;server_port=8000-8001

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [c->s] SETUP rtsp://localhost:8554/vip1/streamid=1 RTSP/1.0
CSeq: 4
Session: b2aa0ab9f50a4e25b3dfe17f3fbff552
Transport: RTP/AVP/UDP;unicast;client_port=5572-5573;mode=record
User-Agent: Lavf58.29.100

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [s->c] RTSP/1.0 200 OK
CSeq: 4
Server: gortsplib
Session: b2aa0ab9f50a4e25b3dfe17f3fbff552
Transport: RTP/AVP;unicast;client_port=5572-5573;server_port=8000-8001

2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [c->s] RECORD rtsp://localhost:8554/vip1 RTSP/1.0
CSeq: 5
Range: npt=0.000-
Session: b2aa0ab9f50a4e25b3dfe17f3fbff552
User-Agent: Lavf58.29.100

2023/07/10 11:09:21 INF [RTSP] [session d5543c6a] is publishing to path 'vip1', with UDP, 2 tracks (H264, MPEG4-audio-gen)
2023/07/10 11:09:21 DEB [RTSP] [conn 127.0.0.1:34792] [s->c] RTSP/1.0 200 OK
CSeq: 5
Server: gortsplib
Session: b2aa0ab9f50a4e25b3dfe17f3fbff552

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment]
In the configuration you posted, you set read credentials for path `cam1`, while in the log you posted, you are using the path `vip1`. In the server, configuration and streams are splitted by path.
