### ISSUE TITLE
WebRTC Playback: Sound only mono

### ISSUE THREAD

**Issue by zapf2000** [bluenviron/mediamtx#2043]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When playing a WebRTC stream, the audio is only played in mono, even it shows 2 channels in webrtc internals (Chrome Linux latest version). On Firefox it works normally in Stereo. Chrome defaults to Mono playback. This is a 3 year old issue on Chrome. So if client is Chrome or Chromium, the SDP answer has to be ignered and forced to stereo=1 on WHEP side.

## Describe how to replicate the issue

Ingest WebRTC Stream in Stereo via WHIP or WebRTC
Listen on another client or the same one on a different audio device. Switch fader from left side to right side. Hear the same on both channels. I made some audio examples, that show the problem.

[Audio Test.zip](https://github.com/bluenviron/mediamtx/files/12003705/Audio.Test.zip)

## Did you attach the server logs?

on WHIP side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 cbr=1;maxaveragebitrate=131072;minptime=10;sprop-stereo=1;stereo=1;useinbandfec=1

on WHEP side:
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1 <<< This has to be ignored and player side has to add stereo=1 (or better the same values as provided on WHIP side).

No chance to set the custom parameters stereo=1 or sprop-stereo=1 on client side, because chrome defaults to Mono playback.

yes

## Did you attach a network dump?

no

There is also a solution for that in ovenplayer: 
https://github.com/AirenSoft/OvenMediaEngine/issues/203 .... I think this can be used in WHEP Player too.

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, this is fixed with #2470.

**Comment by aler9** [comment]
added in v1.2.0
