### ISSUE TITLE
RTSP Audio issue with OBS >= 29 

### ISSUE THREAD

**Issue by moonvrc** [bluenviron/mediamtx#2045]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

With anything above OBS 28, im getting weird Audio issues on RTSP with any kind of louder audio (It almost sounds like audio lag or heavy audio quantization)
(I tested this with other providers that are using different server software and it works fine)

## Describe how to replicate the issue

1. start the server
2. connect to the server
3. make sure you are on OBS version 29.X (Latest)
4. In OBS Set your settings to normal FFMPEG AAC and NVENC H264
5. Play any music that has lots of distortion and loudness (E.g Hardstyle, Hardcore)

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, it's quite difficult to understand how to replicate the issue without logs and without a detailed explanation.

Are you using OBS to publish to the server or to read from the server?

If you're using OBS to publish, which protocol are you using ? (RTMP, RTSP, etc) what software are you using to read and with which protocol?

If you're using OBS to read from the server, who is publishing and with what protocol?

What other software is "working fine" and how?

**Comment by aler9** [comment]
closed since author did not provide required data.
