### ISSUE TITLE
add path success with api, but mediamtx.yml not change

### ISSUE THREAD

**Issue by codecodingg** [bluenviron/mediamtx#2063]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. start the server
2. add path url http://localhost/v2/config/paths/add/new_ip
    payload: {
    "source": "rtsp://admin:123456@192.168.1.1:554/h264/ch1/sub/av_stream",
    "sourceOnDemand": true,
    "sourceProtocol": "tcp"
}
4. response 200 ok
5.  mediamtx.yml not change, when resart server, path disappear

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
The configuration file is not supposed to get changed following an API request. If you want to store API changes, you have to store them in your database and restore them every time the server starts. There's a feature request for an internal database here: #1406
