### ISSUE TITLE
It CANNOT select Back camera or screen on Android moble phone by webrtc streaming

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#2066]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

It CANNOT select Back camera or screen on Android moble phone by webrtc streaming. And the video doesn't display at the correct ratio on the phone.

## Describe how to replicate the issue

1. start the server
2. publish with Android 13 of Pixel 4A
3. read with chrome

## Did you attach the server logs?

![42aca640cf9b28552cad4988162c60b](https://github.com/bluenviron/mediamtx/assets/16969250/3da03c7b-ca8d-45cb-ac15-5da4a1d20139)
![d635eeda55c7210fcea8a78346bf229](https://github.com/bluenviron/mediamtx/assets/16969250/94418e79-3ada-40ee-a928-3513cce23672)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i checked the WebRTC publish page with an Android device and found several issues:

* an option for publishing the screen was shown even though it is not supported on mobile devices
* errors in opening cameras were not reported
* interface was not optimized for mobile

everything is fixed now.

**Comment by iesv** [comment]
THANK YOU VERY MUCH!!!

**Comment by aler9** [comment]
added in v1.2.0
