### ISSUE TITLE
Bad Request returned from API when editing a path published by software.

### ISSUE THREAD

**Issue by WCEarp** [bluenviron/mediamtx#2067]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [x] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
API returns a 400 Bad Request when attempting to edit a path that was added by software, e.g. Gstreamer. The issue does not appear to exist when editing a path that was added via the API or manually entered into the config file. 

## Describe how to replicate the issue
1. Start the server
2. Publish with a Gstreamer command: `gst-launch-1.0 videotestsrc ! x264enc ! rtspclientsink location=rtsp://{API_ADDRESS}:{RTSP_PORT}/test`
3. From a terminal, use `curl` edit the path's config: `curl -X POST http://{API_ADDRESS}:{API_PORT}/v2/config/paths/edit/test -H 'Content-Type: application/json' -d '{"runOnInitRestart": true}'`
4. MediaMTX return's `400 Bad Request`

## Did you attach the server logs?
yes
[mediamtx_v0.23.7_issue2067.log](https://github.com/bluenviron/mediamtx/files/12071561/mediamtx_v0.23.7_issue2067.log)

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Hello, publishing to a path doesn't cause a path configuration to be created, on the contrary, publishing to a path is only possible if a path configuration already exists. The default configuration is something like that:

```yml
paths:
  all:
```

The path configuration called "all" catches all paths. If you want to create and control a configuration for a certain path, add it through the configuration file or through the API:

```yml
paths:
  test:
```

**Comment by WCEarp** [comment]
> Hello, publishing to a path doesn't cause a path configuration to be created, on the contrary, publishing to a path is only possible if a path configuration already exists. The default configuration is something like that:
> 
> ```yaml
> paths:
>   all:
> ```
> 
> The path configuration called "all" catches all paths. If you want to create and control a configuration for a certain path, add it through the configuration file or through the API:
> 
> ```yaml
> paths:
>   test:
> ```

Understood, thank you for your time!
