### ISSUE TITLE
RTSP source url cannot currently support passwords with @ in them

### ISSUE THREAD

**Issue by saket424** [bluenviron/mediamtx#2069]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
If the source url is something like this example

rtsp://user1:P@ssword@192.168.8.10/stream1

Need an alternate way of specifying rtsp source URLs or escape of special characters in the password similar to what was done to address support for turn credentials to be allowed to contain special characters like :

## Describe how to replicate the issue

1. start the server
2. Specify a source url rtsp path with basic auth where the password contains the special character @ 
3. Restream of that path fails

## Did you attach the server logs?

no

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Hello, in order to use special characters in URL it's enough to URL-encode them:

```
rtsp://user1:P%40ssword@192.168.8.10/stream1
```
