### ISSUE TITLE
OBS RTMP connection error - closed (unsupported object type: 9)

### ISSUE THREAD

**Issue by mapl** [bluenviron/mediamtx#2077]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

Issue: OBS 29.1.3 cannot stream to RTMP Target Localhost

Setup 
OBS with standard target definiation

Service: Custom...
Server: rtmp://localhost
Stream key: mystream

## Did you attach the server logs?

INF MediaMTX v0.23.7
DEB path manager created
INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (U
INF [RTMP] listener opened on :1935
INF [HLS] listener opened on :8888
INF [WebRTC] listener opened on :8889 (HTTP)
INF [RTMP] [conn 127.0.0.1:6344] opened
DEB [path mystream] created
DEB [path mystream] destroyed (not in use)
INF [RTMP] [conn 127.0.0.1:6344] closed (unsupported object type: 9)
INF [RTMP] [conn 127.0.0.1:6345] opened
DEB [path mystream] created
DEB [path mystream] destroyed (not in use)
INF [RTMP] [conn 127.0.0.1:6345] closed (unsupported object type: 9)
INF [RTMP] [conn 127.0.0.1:6349] opened
DEB [path mystream] created
DEB [path mystream] destroyed (not in use)
INF [RTMP] [conn 127.0.0.1:6349] closed (unsupported object type: 9)
INF [RTMP] [conn 127.0.0.1:6351] opened
DEB [path mystream] created
DEB [path mystream] destroyed (not in use)
INF [RTMP] [conn 127.0.0.1:6351] closed (unsupported object type: 9)

yes / no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the error "unsupported object type: 9" is related to the audio, not to the video. What are your audio settings?

**Comment by mpisat** [comment]
I wonder if OBS audio encoder was set to CoreAudio AAC (wowza also doesn't like it) rather than FFMpeg AAC?
<img width="361" alt="Screenshot 2023-08-22 at 09 23 32" src="https://github.com/bluenviron/mediamtx/assets/52810975/a8c28483-efb7-4a63-a742-4f8086a90fb2">

**Comment by aler9** [comment]
I tried streaming with OBS, RTMP and the CodeAudio AAC encoder (available on Windows if iTunes is installed) but in my case everything worked perfectly. Please provide the audio settings.

**Comment by aler9** [comment]
closed since no additional feedback was provided.
