### ISSUE TITLE
Libcamera has been updated - causing rpiCamera source failure.

### ISSUE THREAD

**Issue by neutralvibes** [bluenviron/mediamtx#2084]
## Which version are you using?

v0.23.7

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [x] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

mediamtx fails to source the rpiCamera.

libcamera reports the following `libcamera v0.0.5+82-2783c8d8`

## Describe how to replicate the issue
Upgrade via `sudo apt update && sudo apt upgrade` on rpi bullseye distribution. **Libcamera has been updated***

1. start the server via `mediamtx`
2. publish with `rpiCamera as source`
3. read with : anything

## Did you attach the server logs?
`
/dev/shm/rtspss-embeddedexe-1689772364917466714: symbol lookup error: /dev/shm/rtspss-embeddedexe-1689772364917466714: undefined symbol: _ZN9libcamera6Camera21generateConfigurationERKSt6vectorINS_10StreamRoleESaIS2_EE
`

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, libcamera authors are always nice and respectful towards the community, so every two months they perform a forced and backward-incompatible update that messes us every software that wants to interact with the camera excluding libcamera-apps.

**Comment by aler9** [comment]
I checked and in order to support the latest libcamera is enough to recompile the server. Therefore i'll release a new version ASAP.

**Comment by neutralvibes** [comment]
That is great news. Thanks for your efforts👍🏽

**Comment by Tormund1985** [comment]
I have the same problem

**Comment by aler9** [comment]
@Tormund1985 MediaMTX v0.23.8 is compatible with latest libcamera (0.0.5). If you still have problems, please open another issue.
