### ISSUE TITLE
hi & low resolutions streams for a single camera source

### ISSUE THREAD

**Issue by neutralvibes** [bluenviron/mediamtx#2104]
## Describe the feature

Ability to provide at minimum two streams of varying quality from for instance the piCamera source (which I am particularly interested in truthfully). Though perhaps any method used, if it is indeed possible, could translate to _any_ particular source.

Description

The ability to resize and serve different resolutions from a **single** camera source. As in the way commercial ip cameras can provide low & high res versions of the same stream simultaneously without adding too much extra load on their cpu's. 

A particular use case I have in mind is frigate, which utilises this feature of some cameras to record via the high res stream, and is able to reduce processing required for motion and object detection by utilising a lower res one, and even using that for general viewing.

I have a feeling this may be achieved by using ffmpeg in the configuration, although I haven't worked out how to do it, and I suspect, rightly or wrongly that there may be a more efficient way to  do it, without having dived into the code in all honesty. So of course could be completely wrong, old habits die hard .

Please forgive me if I am wasting your time with an idiotic feature. Everyone has their particular talents, that happens to be one of mine at times. Having said that, if it is possible, and not super time consuming, it may be a great feature.

**Comment by pkerney** [comment]
Standard feature.
Use ffmpeg to transcode to a lower resolution/bitrate/framerate and re-stream. (quoted ffmpeg is a little longwinded and is a SW transcode. You can use HW transcode as well.) Also could use gstreamer pipeline instead.
When you uncomment the lines, you can play from rtsp://hostname/garage to get the full stream or  rtsp://hostname/garage_half to get the smaller stream.


  garage:
    source: rtsp://user:passowrd@IP/live/0/MAIN
    sourceOnDemand: yes
    #    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -s 960x540 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 100k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/garage_half
    #    runOnReadyRestart: yes

**Comment by aler9** [comment]
Hello, you can already do this by following instructions in the [remuxing, re-encoding, compression section of the README](https://github.com/bluenviron/mediamtx#remuxing-re-encoding-compression).
