### ISSUE TITLE
Version MEDIAMTX

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2168]
## Which version are you using?

v0.23.8

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (Linux amd64 LXC)

## Describe the issue

When running mediamtx, the console shows the version: **INF version of MediaMTX v0.0.0**, but it is not true

## Describe how to replicate the issue

1. start the server /path/to/mediamtx /path/to/mediamtx.yml
2. see in console version mediamtx

## Did you attach the server logs?

**yes** / no

2023/08/07 12:15:04 INF MediaMTX **v0.0.0**
2023/08/07 12:15:04 INF [metrics] listener opened on 192.168.0.10:9998
2023/08/07 12:15:04 INF [path path1] [rtsp source] started
2023/08/07 12:15:04 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/08/07 12:15:04 INF [path path2] [rtsp source] started
2023/08/07 12:15:04 INF [WebRTC] listener opened on :8889 (HTTP)
2023/08/07 12:15:04 INF [API] listener opened on 192.168.0.10:9997

## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
The executable version is set in official binaries and official Docker images. If it is not set, it means that you've built the executable by yourself.
