### ISSUE TITLE
Not responding path (rtsp h265 camera to hls, connect through vpn)

### ISSUE THREAD

**Issue by ftvdexcz** [bluenviron/mediamtx#2175]
## Which version are you using?

v0.23.8

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I've created a path publish rtsp camera to server 

```
paths:
  proxied:
    source: rtsp://admin:@192.168.1.81:554
  all:
  ...
```
Source ip camera is `192.168.1.81` because this camera and my Pi same network. I want to convert rtsp -> hls and access hls link via openvpn, for example: `http://10.8.0.16:8888/proxied` (`10.8.0.16` is ip of pi)

...
But, I can only access to `http://10.8.0.16:8888` with 404 response 
![image](https://github.com/bluenviron/mediamtx/assets/60183306/1c6da3cb-18b4-41e7-9df3-87580998f6a3)

When I access  `http://10.8.0.16:8888/proxied`, it's pending for a long time 
![image](https://github.com/bluenviron/mediamtx/assets/60183306/d3410a93-e12f-4748-8b8d-b65ceab6c9f0)

If I access `http://192.168.1.127:8888/proxied` (`192.168.1.127` is local ip of Pi), it's working well 

## Describe how to replicate the issue
1. Download release binary and edit config file 
2. Connect Pi to vpn 
3. Run ./mediamtx

## Did you attach the server logs?

yes
![image](https://github.com/bluenviron/mediamtx/assets/60183306/e19199f7-0253-46da-8f11-d5fd8cb95b91)

## Did you attach a network dump?
no, i don't know how to 

Thanks !

**Comment by aler9** [comment]
Hello, in the logs there's no trace of any request coming from the VPN to the server. Make sure that your firewall allows incoming connections from the VPN. The only port required for HLS to work is TCP 8888.

If you still have problems attach server logs with option `logLevel: debug` (as written in instructions) as they allow to view any incoming request to the server.

**Comment by ftvdexcz** [comment]
i checked the firewall, i think it's not blocking anything. Because, sometime it's work but sometime not.

For now I can go to client with ip 10.8.0.19 
![image](https://github.com/bluenviron/mediamtx/assets/60183306/c6bd3f21-49a6-4f6f-92b1-e25bd0d25474)

But not 10.8.0.20 
![image](https://github.com/bluenviron/mediamtx/assets/60183306/f6581387-4a55-4f0a-a0e5-592758d156c4)

I'm sure server is running on port 8888 
![image](https://github.com/bluenviron/mediamtx/assets/60183306/2091c688-66f1-42b0-be15-67c8bfc310f4)

What can I do, please thanks !

**Comment by aler9** [comment]
In the instructions and in my reply there's clearly written to attach logs generated with `logLevel: debug`. Please reopen the issue and attach such logs.

**Comment by ftvdexcz** [comment]
[log.txt](https://github.com/bluenviron/mediamtx/files/12328079/log.txt)

Yes, my server's log here, I see my request in line: 
```
Aug 13 01:47:20 bpi-iot-ros-ai mediamtx[4303]: 2023/08/13 01:47:20 DEB [HLS] [conn 10.8.0.25:14049] GET /cam81/
Aug 13 01:47:20 bpi-iot-ros-ai mediamtx[4303]: 2023/08/13 01:47:20 DEB [HLS] [conn 10.8.0.25:14049] [c->s] GET /cam81/ HTTP/1.1
```

But nothing happend in my screen :(

**Comment by ftvdexcz** [comment]
@ftvdexcz reopened this issue

**Comment by aler9** [comment]
In my opinion the issue is linked to the fact that when you are in the VPN your browser is unable to download the subresources of the HLS page. These includes:

* the hls.js library, that is hosted in the internet
* playlists and segments, hosted on the server

If you open Developer Tools (F12) and go to the "Network" and the "Console" page, you're able to see the status of requests to download the subresources.

**Comment by ftvdexcz** [comment]
Yes, I can see it's pending for long time when download index.m3u8. I'm very confuse because sometime it's work

**Comment by mateothegreat** [comment]
You need to share a screenshot of the network tab of your developer tools.
Specifically, we need to see the host of the pending requests to first determine if it's using the VPN tunnel.

If that is the case then we have a plethora of other VPN related things that could be causing the issue.

At a glance, we have addresses all over the place based on the comments above:
- 10.8.0.19
- 10.8.0.20
- 10.8.0.25
.. so you can appreciate how difficult this is for us to guess ;)

The "hanging" of the requests means the connection was successfully opened but is in purgatory between the tun interface, the VPN routing, and/or the landing side tun interface.

I'd see guidance on a devops/sysadmin oriented server on discord (ping me if you need a link).

Good luck!

**Comment by ftvdexcz** [comment]
Thanks you for help @mateothegreat  ! but I think it's quite old, I stopped running it
