### ISSUE TITLE
ERR: json: unknown field "maxReaders"

### ISSUE THREAD

**Issue by renyongjian** [bluenviron/mediamtx#2181]
## Which version are you using?

docker latest version in arm64

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [x ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I try to start rtmp server with cmd:
sudo docker run --rm -it --network=host  \
-e MTX_PROTOCOLS=tcp \
-p 1935:1935 \
-v /home/mediamtx.yml:/mediamtx.yml \
bluenviron/mediamtx

but happen this error :
WARNING: Published ports are discarded when using host network mode
ERR: json: unknown field "maxReaders"

## Describe how to replicate the issue

1. sudo docker pull bluenviron/mediamtx
2. download  mediamtx.yml from github.
3.  run  sudo docker run --rm -it --network=host  \
-e MTX_PROTOCOLS=tcp \
-p 1935:1935 \
-v /home/mediamtx.yml:/mediamtx.yml \
bluenviron/mediamtx
4.  error happen :   WARNING: Published ports are discarded when using host network mode
ERR: json: unknown field "maxReaders" was printed.
5. it seems yml in github  file is invalid.

## Did you attach the server logs?

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
You're using an outdated Docker image, you can either clean the local cache by running:

```
docker image rm bluenviron/mediamtx:latest
```

or alternatively you can set the image version in the command:

```
sudo docker run --rm -it --network=host
-e MTX_PROTOCOLS=tcp
-p 1935:1935
-v /home/mediamtx.yml:/mediamtx.yml
bluenviron/mediamtx:1.0.0
```

**Comment by renyongjian** [comment]
thanks,it works well
