### ISSUE TITLE
Embed hls.js into the server

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#2202]
## Describe the feature

This avoids problems when reading with HLS in an environment without internet.

**Comment by 948764321** [comment]
我试图克隆一份一样的 html，同时将 hls.js 放在本地，但是请求 index.m3u8 时报错 404 了（不同 ip 环境下会发生，相同 ip 下就没事）。
怎么解决呢？

**Comment by aler9** [comment]
added in MediaMTX v1.0.1
