### ISSUE TITLE
Enhanced RTMP H265 error in onMetaData command

### ISSUE THREAD

**Issue by pedroSG94** [bluenviron/mediamtx#2217]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm actually developing H265 support for RTMP in my Android library following the enhanced rtmp way. According with:
https://github.com/veovera/enhanced-rtmp/blob/main/enhanced-rtmp.pdf (official pdf)

In the onMetaData command, the value of the property videocodecid should be 1752589105 ('hvc1' character sequence as double).
But if i set that value the server response me:

![imagen](https://github.com/bluenviron/mediamtx/assets/17556876/40646dbc-56a8-46f4-921f-7b7e5e6ec7b3)

If i set the value 7 (avc videocodecid) the streaming with h265 is totally working:

![imagen](https://github.com/bluenviron/mediamtx/assets/17556876/76f519d1-69fc-4264-8137-e74a9fe2a12f)

I detected that OBS send videocodecid with value 7 so I'm not sure if I misunderstand something or server side should support both ways.

Also, it is off topic, I want to confirm that AMF3 actually is not supported in RTMP, right?
It is because this method response me type 17 (AMF3Command) is invalid:
https://github.com/bluenviron/mediamtx/blob/5e095971c4351efa3345642f6c750caa9f2981e5/internal/rtmp/message/reader.go#L11

## Describe how to replicate the issue

You can use this apk file:

[apksample.zip](https://github.com/bluenviron/mediamtx/files/12373514/apksample.zip)

Steps:
1 - Unzip file to obtain the apk sample
2 - Install apk in an Android device
3 - open app
4 - select OpenGl RTMP
5 - fill the text box with the rtmp server endpoint. For example: rtmp://192.168.0.5:1935/live/test
6 - press start stream button

After that, the stream should fail with broken pipe because server closed connection.

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the part about videocodecid in the Enhanced RTMP specification was added just 3 weeks ago, so i would consider this more an enhancement than a bug. In the meanwhile, use value "7".

**Comment by pedroSG94** [comment]
Hello,

For now I will continue with value 7 since other servers like YouTube accept it.
Waiting for this update. Thank you for this great server.

**Comment by aler9** [comment]
implemented in #2234

**Comment by aler9** [comment]
added in MediaMTX v1.0.1

**Comment by pedroSG94** [comment]
> 

Thank you!, I will download the version
