### ISSUE TITLE
Occational stuttering on multiple transports

### ISSUE THREAD

**Issue by agg23** [bluenviron/mediamtx#2227]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

[I previously created a discussion for my problem](https://github.com/bluenviron/mediamtx/discussions/2223), and was asked to create an issue. I would not be surprised if this is just user error, but I can't seem to figure it out...

 I have tried:

* Direct streaming HLS sources
* Passing HLS sources through machine local `ffmpeg` -> RTSP
* Passing HLS sources through remote `ffmpeg` -> RTSP
* Passing local media through `ffmpeg` -> RTSP

All of these have resulted in occasional (every 30s - 1min) stuttering for a second or more on RTSP and WebRTC outputs. The stutters do not occur at the same time across transports, but within a given transport (say WebRTC), they drop at the same time. This suggests to me something occurring serverside, and not a packet loss issue.

I don't believe the HLS sources at least are too high of bitrate (because they're streamed on their own normally), and considering I'm currently testing within my LAN, I would not expect even the local media to be stuttering. I believe my LAN architecture to be fairly robust, but I'm not ruling out some weird edgecase that's causing failures. In any case, I watch a lot of Twitch without issue.

On trying to get a reliable repro for this issue, I found that WebRTC to be stuttering way more often than it has been, sometimes up to once every 10 seconds, often for 5-10 seconds at a time. During this time RTSP also stutters, but never on the same frame as WebRTC (using test videos with incrementing frame counters), and no where near as frequently.

## Describe how to replicate the issue

My config is nearly empty for these tests, just some settings to try to aid in the stuttering, and some paths to broadcast to.

```yaml
logLevel: debug

# Unclear what size this should be. Tried increasing it just in case
readBufferCount: 16384

# Trying to see if UDP is causing problems with RTSP
protocols: [tcp]

paths:
  output:
    #
```

I've unfortunately been able to find a good example HLS stream that doesn't require transcoding to remove B-frames for WebGL, so all of these examples will pass through `ffmpeg` (which I recognize may simply be the problem, though it seems unlikely).

----

All of these examples were tested with VLC 3.0.6 on Windows (no custom settings) for reading the RTSP streams, and Firefox 116.0.2 on Windows for WebRTC.

### Example 1 - Remote HLS rebroadcast

Using Apple's example bip stream: https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8

```bash
ffmpeg-re -i https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8  -c:v libx264 -preset ultrafast -bf 0 -tune zerolatency -c:a libopus -ac 2 -f rtsp rtsp://[hostname]:8554/output
```

Substituting `[hostname]` for either `localhost`, when running on `ffmpeg` inside the Docker container, or my LAN IP for that box.

Directly watching the HLS stream in VLC results in no stuttering. Could this simply be because of VLC's buffer size?

### Example 2 - Local media broadcast

Using Big Buck Bunny (pulled from Archive.org, as the Blender download is very slow): https://archive.org/details/BigBuckBunnyFULLHD60FPS

```bash
ffmpeg -re -i "Big Buck Bunny - FULL HD 60FPS.mp4" -c:v libx264 -preset ultrafast -bf 0 -tune zerolatency -c:a libopus -ac 2 -f rtsp rtsp://[hostname]:8554/output
```

Basically the same command as Example 1.

This example seems extremely odd to me, as I would expect this to be the best case scenario. Extremely fast IO with local media, extremely fast transcode, still somehow has problems.

## Did you attach the server logs?

yes: [mediamtx - agg23.log](https://github.com/bluenviron/mediamtx/files/12397848/mediamtx.-.agg23.log)

I don't think these logs contain anything useful, but in case they do, they are attached.

## Did you attach a network dump?

no

----

Please let me know if you would like anything else from me. I feel like I haven't done a great job of providing repros, but I'm not used to this space. If you know of a public HLS stream without B-frames (and thus doesn't have to be passed through `ffmpeg` to be used by WebRTC), I would appreciate it.

**Comment by agg23** [comment]
I don't know if this is useful information or just noise, but I tried using [srs](https://github.com/ossrs/srs) in the same situations (same Docker machine, same publisher, same stream, though different format) and it seemed to perform much better. I didn't notice any stuttering with the Apple example, and I tried streaming in a Twitch stream (HLS) with the same command and didn't have audio interruptions, but the video kept speeding up and slowing down.

```bash
ffmpeg -re -i https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8  -c:v libx264 -preset ultrafast -bf 0 -tune zerolatency -c:a aac -b:a 128k -ac 2 -f flv rtmp://192.168.1.241/live/livestream
```

**Comment by aler9** [comment]
Hello, stutterings are caused by the fact that you're using the wrong encoder settings. Color format must be converted into yuv420 and the `-tune zerolatency` flag must be removed:

```
ffmpeg -re \
-i https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8 \
-pix_fmt yuv420p \
-c:v libx264 \
-preset ultrafast \
-c:a libopus -ac 2 -f rtsp rtsp://[hostname]:8554/output
```

Keep in mind that MediaMTX only performs media routing, without any internal conversion. This has the advantage of being as lightweight as possible, but the original stream has to be compatible with the protocol you're interested into using at the subscriber side. Recommended encoder settings are available in the README.
