### ISSUE TITLE
Combine multiple streams to one stream

### ISSUE THREAD

**Issue by Velt1** [bluenviron/mediamtx#2240]
## Describe the feature

Description
It would be nice to be able to combine different streams to one stream to save bandwith.

**Comment by aler9** [comment]
Hello, what do you mean by combining two streams together? How this operation would lead to save bandwidth?

**Comment by Velt1** [comment]
For example:
If 4 RTSP Streams from different devices, lets just say security cameras, are streaming to the mediamtx server, and i want to see all four on my website combined. I could receive 4 streams or combine the 4 streams in one stream in a specified resolution, to see them all at once.

**Comment by aler9** [comment]
@Velt1 you can achieve this by using FFmpeg, instructions are here: https://github.com/bluenviron/mediamtx/discussions/893#discussioncomment-2607954

The server has the task of routing frames, not editing them.
