### ISSUE TITLE
Error read RTMP frame_mbs_only_flag

### ISSUE THREAD

**Issue by lozo2010** [bluenviron/mediamtx#2259]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have a camera with which I stream via RTMP to the server. When I want to consume that stream via RTMP I get the error frame_mbs_only_flag = 0 is not supported.

If I consume it by RTSP I have no problem. Is it possible that there is an option to make it work also for RTMP?

## Describe how to replicate the issue

1. start the server
2. publish to RTMP
3. read RTMP

## Did you attach the server logs?

2023/08/28 17:33:09 INF MediaMTX v1.0.0
2023/08/28 17:33:09 DEB path manager created
2023/08/28 17:33:09 INF [RTSP] listener opened on :9556 (TCP)
2023/08/28 17:33:09 INF [RTMP] listener opened on :9936
2023/08/28 17:33:14 INF [RTMP] [conn 84.236.195.134:11127] opened
2023/08/28 17:33:14 DEB [path live/vision6-cam00] created
2023/08/28 17:33:15 INF [RTMP] [conn 84.236.195.134:11127] is publishing to path 'live/vision6-cam00', 2 tracks (H264, MPEG-4 Audio)
2023/08/28 17:33:18 INF [RTMP] [conn 79.117.110.134:40682] opened
2023/08/28 17:33:18 INF [RTMP] [conn 79.117.110.134:40682] is reading from path 'live/vision6-cam00', 2 tracks (H264, MPEG-4 Audio)
2023/08/28 17:33:19 INF [RTMP] [conn 79.117.110.134:40682] closed (frame_mbs_only_flag = 0 is not supported)

## Did you attach a network dump?

yes 
[cam.zip](https://github.com/bluenviron/mediamtx/files/12455990/cam.zip)

**Comment by aler9** [comment]
hello, try again with this nightly release and let me know if it works

[mediamtx_v1.0.0-31-g30b7245_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12462276/mediamtx_v1.0.0-31-g30b7245_darwin_amd64.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12462277/mediamtx_v1.0.0-31-g30b7245_darwin_arm64.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12462279/mediamtx_v1.0.0-31-g30b7245_linux_amd64.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12462281/mediamtx_v1.0.0-31-g30b7245_linux_arm64v8.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12462287/mediamtx_v1.0.0-31-g30b7245_linux_armv6.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12462289/mediamtx_v1.0.0-31-g30b7245_linux_armv7.tar.gz)
[mediamtx_v1.0.0-31-g30b7245_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12462292/mediamtx_v1.0.0-31-g30b7245_windows_amd64.zip)

**Comment by lozo2010** [comment]
First of all thanks for the support.

Now I get the following error when consuming the RTMP

![image](https://github.com/bluenviron/mediamtx/assets/9165283/bc606499-0611-4e46-ab17-622497f5289d)

**Comment by aler9** [comment]
It seems that your camera uses [interlacing](https://en.wikipedia.org/wiki/Interlaced_video), that's the first time i've seen an IP camera using it.

Here's another nightly release, i've put your packet dump into a simulator and launched it against this version without errors:
[mediamtx_v1.0.0-33-g8e955d2_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12465815/mediamtx_v1.0.0-33-g8e955d2_darwin_amd64.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12465817/mediamtx_v1.0.0-33-g8e955d2_darwin_arm64.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12465819/mediamtx_v1.0.0-33-g8e955d2_linux_amd64.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12465820/mediamtx_v1.0.0-33-g8e955d2_linux_arm64v8.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12465822/mediamtx_v1.0.0-33-g8e955d2_linux_armv6.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12465832/mediamtx_v1.0.0-33-g8e955d2_linux_armv7.tar.gz)
[mediamtx_v1.0.0-33-g8e955d2_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12465833/mediamtx_v1.0.0-33-g8e955d2_windows_amd64.zip)

**Comment by lozo2010** [comment]
It is not a normal ip camera. 
With this version, I can consume the RTMP stream without problems.
