### ISSUE TITLE
HLS.js/Browser with RTMP ingest of AV1+AAC not working, mpv works

### ISSUE THREAD

**Issue by CounterPillow** [bluenviron/mediamtx#2260]
## Which version are you using?

git master (e74c458)

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Streaming AV1+AAC over RTMP from OBS into mediamtx, and then trying to play the stream through HLS with Firefox is not working. Browsers report the error "DOMException: The fetching process for the media resource was aborted by the user agent at the user's request." which could indicate the format is unsupported.

`mpv http://localhost:8888/mystream/index.m3u8` plays back the stream fine.

## Describe how to replicate the issue

1. start the server
2. publish with obs, AV1 1920x1080@60 preset=8 + AAC (either libfdk AAC or FFmpeg AAC) over rtmp
3. read with HLS through a web browser

## Did you attach the server logs?

I run HLS on port 18888, but changing it to 8888 makes no difference. I also use fmp4, but lowLatency makes no difference.
```
2023/08/28 22:17:44 INF [RTMP] [conn [::1]:36270] opened
2023/08/28 22:17:44 DEB [path pillowstrim] created
2023/08/28 22:17:46 INF [RTMP] [conn [::1]:36270] is publishing to path 'pillowstrim', 2 tracks (AV1, MPEG-4 Audio)
2023/08/28 22:17:46 INF [HLS] [muxer pillowstrim] created automatically
2023/08/28 22:17:46 INF [HLS] [muxer pillowstrim] is converting into HLS, 2 tracks (AV1, MPEG-4 Audio)
2023/08/28 22:17:52 DEB [HLS] [conn 127.0.0.1:51136] GET /pillowstrim/index.m3u8
2023/08/28 22:17:52 DEB [HLS] [conn 127.0.0.1:51136] [c->s] GET /pillowstrim/index.m3u8 HTTP/1.1
Host: localhost:18888
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Dnt: 1
Referer: http://localhost:18888/pillowstrim/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0


2023/08/28 22:17:57 DEB [HLS] [conn 127.0.0.1:51136] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Cache-Control: max-age=30
Content-Type: application/vnd.apple.mpegurl
Server: mediamtx

(body of 199 bytes)
2023/08/28 22:17:57 DEB [HLS] [conn 127.0.0.1:51146] GET /pillowstrim/hls.min.js.map
2023/08/28 22:17:57 DEB [HLS] [conn 127.0.0.1:51146] [c->s] GET /pillowstrim/hls.min.js.map HTTP/1.1
Host: localhost:18888
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0


2023/08/28 22:17:57 DEB [HLS] [conn 127.0.0.1:51146] [s->c] HTTP/1.1 301 Moved Permanently
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Location: /pillowstrim/hls.min.js.map/
Server: mediamtx


2023/08/28 22:18:23 DEB [HLS] [conn 127.0.0.1:51136] GET /pillowstrim/index.m3u8
2023/08/28 22:18:23 DEB [HLS] [conn 127.0.0.1:51136] [c->s] GET /pillowstrim/index.m3u8 HTTP/1.1
Host: localhost:18888
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Dnt: 1
Referer: http://localhost:18888/pillowstrim/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0


2023/08/28 22:18:23 DEB [HLS] [conn 127.0.0.1:51136] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Cache-Control: max-age=30
Content-Type: application/vnd.apple.mpegurl
Server: mediamtx

(body of 198 bytes)
2023/08/28 22:18:53 DEB [HLS] [conn 127.0.0.1:51136] GET /pillowstrim/index.m3u8
2023/08/28 22:18:53 DEB [HLS] [conn 127.0.0.1:51136] [c->s] GET /pillowstrim/index.m3u8 HTTP/1.1
Host: localhost:18888
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Dnt: 1
Referer: http://localhost:18888/pillowstrim/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0


2023/08/28 22:18:53 DEB [HLS] [conn 127.0.0.1:51136] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Cache-Control: max-age=30
Content-Type: application/vnd.apple.mpegurl
Server: mediamtx

(body of 197 bytes)
2023/08/28 22:18:56 INF [RTMP] [conn [::1]:36270] closed (EOF)
2023/08/28 22:18:56 DEB [path pillowstrim] destroyed (not in use)
2023/08/28 22:18:56 INF [HLS] [muxer pillowstrim] destroyed (terminated)
```

yes

## Did you attach a network dump?

no

## ffprobe output

```
[libdav1d @ 0x557b1944c9c0] libdav1d 1.2.1
Input #0, hls, from 'http://localhost:18888/pillowstrim/index.m3u8':
  Duration: N/A, start: 0.000000, bitrate: 2389 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 2861568
  Stream #0:0: Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, 2261 kb/s, 60 fps, 60 tbr, 90k tbn (default)
    Metadata:
      variant_bitrate : 2861568
      major_brand     : mp42
      minor_version   : 1
      compatible_brands: mp41mp42isomhlsf
  Stream #0:1: Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      variant_bitrate : 2861568
```

**Comment by CounterPillow** [comment]
You can also reproduce this using ffmpeg instead of OBS as the producer if you have [the Enhanced RTMP series](https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=9580) applied:

```
./ffmpeg -stream_loop -1 -re -i ~/Videos/Wanderers.mov -pix_fmt yuv420p -c:v libsvtav1 -g 120 -minrate:v 3000k -maxrate:v 3000k -preset 8 -c:a libfdk_aac -b:a 192k -f flv rtmp://localhost:1935/pillowstrim
```

**Comment by CounterPillow** [comment]
The problem appears to be `index.m3u8`, having hls.js play back `stream.m3u8` directly works.

**Comment by aler9** [comment]
Hello, can you post the content of index.m3u8?

**Comment by CounterPillow** [comment]
```
#EXTM3U
#EXT-X-VERSION:9
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=6307412,AVERAGE-BANDWIDTH=5750319,CODECS="av01.0.08M.08.1.110.32.32.32.0,mp4a.40.2",RESOLUTION=1920x816
stream.m3u8
```

this is the index.m3u8 your software generates. If it doesn't work with the player page you generate, it's not a "question", it's a bug in your software.

**Comment by aler9** [comment]
The server parses the AV1 track and generates the codec string `av01.0.08M.08.1.110.32.32.32.0`.

This codec string is marked as unsupported by both Firefox and Chrome:

https://jsfiddle.net/tfqjhyv9/

I have to check whether the codec string is generated in a wrong way or is correct and there's a bug in Firefox and Chrome.

**Comment by aler9** [comment]
@CounterPillow please test this nightly release (https://github.com/bluenviron/mediacommon/pull/69) and let me know if it works.

[mediamtx_v1.0.0-34-gbd1cb35_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12469599/mediamtx_v1.0.0-34-gbd1cb35_darwin_amd64.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12469602/mediamtx_v1.0.0-34-gbd1cb35_darwin_arm64.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12469604/mediamtx_v1.0.0-34-gbd1cb35_linux_amd64.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12469606/mediamtx_v1.0.0-34-gbd1cb35_linux_arm64v8.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12469608/mediamtx_v1.0.0-34-gbd1cb35_linux_armv6.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12469609/mediamtx_v1.0.0-34-gbd1cb35_linux_armv7.tar.gz)
[mediamtx_v1.0.0-34-gbd1cb35_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12469612/mediamtx_v1.0.0-34-gbd1cb35_windows_amd64.zip)

**Comment by CounterPillow** [comment]
Yep, works now. Thanks!
