### ISSUE TITLE
RTSP sessions sometimes terminate with Android ExoPlayer clients due to unsupported RTP AggregationPacket 

### ISSUE THREAD

**Issue by machenmusik** [bluenviron/mediamtx#2272]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTSP sessions sometimes terminate with Android ExoPlayer clients due to unsupported RTP AggregationPacket.
It's unclear exactly what the condition is that causes RTP AggregationPacket usage, so if it is possible to have a configuration option to avoid use of RTP AggregationPacket, that is probably best.
 
## Describe how to replicate the issue

1. start the server
2. publish with camera using ffmpeg source and runOnDemand (unclear exactly what the condition is that causes RTP AggregationPacket usage)
3. read with Android ExoPlayer client (e.g. demo app)
4. when RTP AggregationPacket usage occurs, Android ExoPlayer client fails; this error can be found in adb logcat: `java.lang.UnsupportedOperationException: need to implement processAggregationPacket`

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, RTP packets are generated by the publisher, in this case FFmpeg. The server just routes them from publisher to readers, so nothing can be done on server side.

Aggregated RTP packets are generated by FFmpeg in order to aggregate together multiple small H264 NALUs, typically SPS and PPS. They are really common and i don't think there's a FFmpeg option to disable them. My advice is to open an issue in ExoPlayer, since it's the only part that is lacking something.

**Comment by machenmusik** [comment]
Thanks for the quick response!  I thought it might be an issue when publishing as RTSP from non-RTSP sources, as well.

**Comment by aler9** [comment]
Yes, it might be an issue since in case of non-RTSP sources it's the server that generates RTP packets, but aggregated packets are not an optional feature, they are an essential part of [RFC6184](https://datatracker.ietf.org/doc/html/rfc6184). ExoPlayer has to support them.
