### ISSUE TITLE
RTMP ingest from Dahua cameras is not working (only audio track accepted)

### ISSUE THREAD

**Issue by rudyryk** [bluenviron/mediamtx#2289]
## Which version are you using?

v1.0.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [x] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When pushing RTMP stream from Dahua IP camera (e.g model N45DJ62), the video track is rejected and only audio track is available on the stream.

## Describe how to replicate the issue

1. Start the MediaMTX server with RTMP enabled
2. In the camera's settings:
   - Network
      - Access Platform
         - RTMP
            - Enable main stream, enable RTMP, put custom address of MediaMTX RTMP ingest endpoint
3. Check server's logs and/or try to view the stream

## Did you attach the server logs?

Yes

[Dahua-RTMP-dump-20230904-0840.log.zip](https://github.com/bluenviron/mediamtx/files/12511876/Dahua-RTMP-dump-20230904-0840.log.zip)

## Did you attach a network dump?

Yes

[Dahua-RTMP-dump-20230904-0840.pcap.zip](https://github.com/bluenviron/mediamtx/files/12511862/Dahua-RTMP-dump-20230904-0840.pcap.zip)

I've used a camera connected to my laptop's Ethernet port:

- Camera: 192.168.88.251 / 24
- Laptop: 192.168.88.1 / 24
- MediaMTX running inside a Docker container with a port 1935 port exposed, with config [mediamtx-20230904-0840.yml.zip](https://github.com/bluenviron/mediamtx/files/12511904/mediamtx-20230904-0840.yml.zip)

**Comment by aler9** [comment]
@rudyryk please try this nightly release (branch dev/dahua) and let me know if it works. If it doesn't attach another network dump. Thanks for your collaboration.

[mediamtx_v1.0.3-5-gc1cc320_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12516757/mediamtx_v1.0.3-5-gc1cc320_darwin_amd64.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12516758/mediamtx_v1.0.3-5-gc1cc320_darwin_arm64.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12516762/mediamtx_v1.0.3-5-gc1cc320_linux_amd64.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12516764/mediamtx_v1.0.3-5-gc1cc320_linux_arm64v8.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12516765/mediamtx_v1.0.3-5-gc1cc320_linux_armv6.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12516766/mediamtx_v1.0.3-5-gc1cc320_linux_armv7.tar.gz)
[mediamtx_v1.0.3-5-gc1cc320_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12516768/mediamtx_v1.0.3-5-gc1cc320_windows_amd64.zip)

**Comment by rudyryk** [comment]
@aler9 Awesome, this is working!

**Comment by aler9** [comment]
fixed in v1.1.0
