### ISSUE TITLE
webrtc playback speed

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#2297]
## Which version are you using?

v1.0.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

whep播放有4秒的延迟，卡在这里（Incidentswhep playback has a 4 second delay and is stuck here）
![image](https://github.com/bluenviron/mediamtx/assets/86584277/f6ba8993-8f1c-418a-a76b-d499b7c277b4)
完整播放出来后的js打印信息（Print information in JavaScript after complete playback）
![image](https://github.com/bluenviron/mediamtx/assets/86584277/8cf20208-dc37-465e-87c2-d470db728eb9)
有什么办法可以加快点播速度。（What are the methods to speed up the on-demand playback speed by printing information on the JS after complete playback）

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, it's unclear whether you are reporting a delay in connecting to the server or a delay in showing the video to the user. In case you have issues in establishing a WebRTC peer connection with the server, the README has a dedicated section:

https://github.com/bluenviron/mediamtx#connectivity-issues

**Comment by liusuyi2021** [comment]
Thank you very much for following the link you provided
My configuration:
WebrtcICEHostNAT1To1IPs: [localhost]
WebrtcICEUDPMuxAddress: localhost: post
WebrtcICETCPMuxAddress: localhost: post
And then the on-demand was very fast. Thank you again

**Comment by aler9** [comment]
i'm thinking about making `WebrtcICEUDPMuxAddress` enabled by default since it avoids this kind of issues, that are mostly caused by the fact that both the server and client have to reach Google's STUN server before establishing a connection. `WebrtcICEUDPMuxAddress` avoids interaction with the STUN server.
