### ISSUE TITLE
ios and mac safari native mode does not support llhls very well

### ISSUE THREAD

**Issue by fastfading** [bluenviron/mediamtx#2317]
Related Topic   https://github.com/bluenviron/mediamtx/discussions/2288

## Which version are you using?
v1.0.3

## Which operating system are you using?
- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] macOS arm64 standard  (M1 chips)
- [ ] Other (please describe)

## Describe the issue
ios and mac safari native mode does not support llhls very well.
there will be a long latency 10s+ delay on ios device and mac safari native mode
sometimes the video freezed and did not recover

## Describe how to replicate the issue
1. build mtx
2. follow https://github.com/bluenviron/mediamtx#compatibility-with-apple-devices to generate hlsServerKey and hlsServerCert
openssl genrsa -out server.key 2048
openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650

3. start mtx with following configuration.   set 
hlsEncryption: yes
hlsServerKey: server.key
hlsServerCert: server.crt
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 6s
hlsPartDuration: 1000ms
[mediamtx.yml.zip](https://github.com/bluenviron/mediamtx/files/12556837/mediamtx.yml.zip)

4. use obs to send rtmp stream , configuration as follow.  
GOP: 6s   
tune:zerolatency   
url: rtmp://localhost:1935/live/abc
<img width="990" alt="image" src="https://github.com/bluenviron/mediamtx/assets/8351732/03ab86e0-a114-4db0-8c6d-a97af41fab30">

5. use mac chrome to play https://localhost:8888/live/abc/ ,  latency is about 3.5s
    use ios safari to play https://localhost:8888/live/abc/  , we will see a very long latency  10s+ 
    use mac safari play stream.m3u8 directly https://localhost:8888/live/abc/index.m3u8  we will see a very long latency  10s+ 
both ios and mac safari will get freezed sometimes. 
we have seen the network through web console that small segement part.mp4 are downloaded.  

we have dig into the issue and find something: 
<img width="1920" alt="Screenshot 2023-09-06 at 15 27 44 (2)" src="https://github.com/bluenviron/mediamtx/assets/8351732/e7ee5bd2-6e21-42d4-8b9b-6322a33583f8">
<img width="1920" alt="Screenshot 2023-09-06 at 15 24 22 (2)" src="https://github.com/bluenviron/mediamtx/assets/8351732/6f3f4be0-0ad2-4374-91a2-506a2116b747">
<img width="1920" alt="Screenshot 2023-09-06 at 15 23 03 (2)" src="https://github.com/bluenviron/mediamtx/assets/8351732/57f999e8-772b-48ed-8420-f83cf8caa1db">
<img width="1920" alt="Screenshot 2023-09-06 at 15 22 57 (2)" src="https://github.com/bluenviron/mediamtx/assets/8351732/085576ea-c7a5-44b9-a233-5dfcf556b893">
check the images above

part2856.mp4  is  preload  in the first m3u8
but in the second m3u8 it is gone. 
and browser report part2856.mp4  404 error
this may cause the video freeze on ios or native safari. 

ios or native safari always download several seg.mp4 before part.mp4 and push it into play buffer, that cause latency very long.

how to resolve above 2 issues?

## Did you attach the server logs?
no, it is easy to replicate

## Did you attach a network dump?
no, it is easy to replicate

**Comment by aler9** [comment]
Hello, thank you very much for reporting and debugging this bug, i found out that when `hlsSegmentDuration` is an exact multiple of `hlsPartDuration`, and IDR frames are sent out at an interval equal to `hlsSegmentDuration`, there are gaps in parts IDs that causes the URL in EXT-X-PRELOAD-HINT to return 404.

In your case, the setup was

```
hlsSegmentDuration: 6s
hlsPartDuration: 1s
IDR interval = 6s
```

This is fixed by https://github.com/bluenviron/gohlslib/pull/107
