### ISSUE TITLE
write queue is full

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#2320]
## Which version are you using?

v1.0.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

When I pull 32 video streams, warning write queue is full,Video playback may experience delays
![image](https://github.com/bluenviron/mediamtx/assets/86584277/0b60b266-909d-4742-b05b-891216fec1fd)

## Did you attach the server logs?

 no

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
i don't see any bugs here. This is expected.

**Comment by liusuyi2021** [comment]
But after I adjusted the size to 8192, there was a delay and there was an automatic shutdown of the stream, which prevented the program from starting beyond 8192

**Comment by kanehekili** [comment]
I encounter this problem after a connection has been closed:
```
Oct 04 17:26:25 hubicam mediamtx[966]: 2023/10/04 17:26:25 INF [RTSP] [conn 185.180.143.142:35180] closed: EOF
Oct 04 17:39:25 hubicam mediamtx[966]: 2023/10/04 17:39:25 WAR [RTSP] [session 07658b8b] write queue is full
Oct 04 17:39:26 hubicam mediamtx[966]: 2023/10/04 17:39:26 WAR [RTSP] [session 07658b8b] write queue is full
Oct 04 17:39:27 hubicam mediamtx[966]: 2023/10/04 17:39:27 WAR [RTSP] [session 07658b8b] write queue is full
```
Currently no client is attached, but the error messages continue.
Can be reproduced with a VLC client. FFPlay behaves differently, no problems there

**Comment by liusuyi2021** [comment]
> 关闭最后一个连接后，我遇到此问题：（MediaMtx 1.1.1）
> 
> ```
> Oct 04 17:26:25 hubicam mediamtx[966]: 2023/10/04 17:26:25 INF [RTSP] [conn 185.180.143.142:35180] closed: EOF
> Oct 04 17:39:25 hubicam mediamtx[966]: 2023/10/04 17:39:25 WAR [RTSP] [session 07658b8b] write queue is full
> Oct 04 17:39:26 hubicam mediamtx[966]: 2023/10/04 17:39:26 WAR [RTSP] [session 07658b8b] write queue is full
> Oct 04 17:39:27 hubicam mediamtx[966]: 2023/10/04 17:39:27 WAR [RTSP] [session 07658b8b] write queue is full
> ```
> 
> 附上一个RPI凸轮。为什么在 13 分钟没有连接后会发生这种情况？

The stream will not immediately close, and it is obvious that the queue is full and automatically closes

**Comment by kanehekili** [comment]
The log continues for > 2 hours. Looks like the stream never closes...
