### ISSUE TITLE
None of the video shows in browser of OBS by webRTC

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#2324]
## Which version are you using?

v1.0.3

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
![image](https://github.com/bluenviron/mediamtx/assets/16969250/cf3d3034-c550-4df9-ae1c-e108bf71daa3)

## Describe how to replicate the issue

1. start the server
2. publish with chrome by webrtc: https://192.168.100.10/ty/publish
3. read with of browser of OBS: [https://19](https://192.168.100.10/ty
4. none of the video shows in OBS but only chrome.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
The server has nothing to do with the fact that the OBS web view is unable to handle WebRTC streams, this is evidently a OBS limitation that should be reported in the OBS bug tracker.
