### ISSUE TITLE
API Definition/Implementation Discrepancy with Path MaxReaders Property

### ISSUE THREAD

**Issue by Tim-Rasmussen** [bluenviron/mediamtx#2331]
## Which version are you using?

v1.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

An API call to add or edit a path fails with HTTP status code 400 - bad request.  The JSON included in the HTTP POST API call was based on the MediatMTX OpenAPI JSON definition (version 1.0.0).  When the posted JSON is amended so that the path maxReaders property is set to 0 instead of 0.0, the API call succeeds.  It looks like the OpenAPI JSON definition should define maxReaders as an integer instead of a number.

## Describe how to replicate the issue

1. Start the server.
2. Add or edit a path using the OpenAPI interface.  This was done using a C# proxy generated in Visual Studio from the downloaded OpenAPI definition JSON file (version 1.0.0) but can be replicated using Postman with the path maxReaders property set to 0.0.
3. The API returns 400 - Bad Request.
4. Perform step 2 again but set the path maxReaders property to 0.
5. The API returns 200 - OK.

## Did you attach the server logs?

No.

## Did you attach a network dump?

No.

**Comment by aler9** [comment]
fixed in v1.1.0
