### ISSUE TITLE
It DOESNOT works when I set to 0 to disable automatic deletion. 

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#2361]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

It DOESNOT works when I set to 0 to disable automatic deletion.

recordDeleteAfter: 0

ERR: json: cannot unmarshal number into Go struct field alias.recordDeleteAfter of type string

## Describe how to replicate the issue

1. start the server
2. publish with obs
3. read with chrome

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, use `0s` instead of `0`.

**Comment by iesv** [comment]
Thanks!
