### ISSUE TITLE
unable to decode AVCC - invalid NALU 

### ISSUE THREAD

**Issue by BasemHamad** [bluenviron/mediamtx#2375]
## Which version are you using?

v1.1.0 ( main branch ) 

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When starting DJI Drone ( M350 , Mavic 3 E ) live stream . its start streaming but it keep doping , the live stream played and everything seems to be ok until the crash happens .   
```
2023/09/19 13:09:52 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/09/19 13:09:52 INF [RTMP] listener opened on :1935
2023/09/19 13:09:52 INF [HLS] listener opened on :8888
2023/09/19 13:09:52 INF [WebRTC] listener opened on :8889 (HTTP)
2023/09/19 13:09:52 INF [SRT] listener opened on :8890 (UDP)
2023/09/19 13:09:52 INF [API] listener opened on 0.0.0.0:9997
2023/09/19 13:09:53 INF [RTMP] [conn xx.xx.xx.xx:35816] opened
2023/09/19 13:09:55 INF [RTMP] [conn xx.xx.xx.xx:35816] is publishing to path 'basem', 1 track (H264)
2023/09/19 13:09:58 INF [WebRTC] [session 497921fb] created by xx.xx.xx.xx:40248
2023/09/19 13:10:08 INF [WebRTC] [session 497921fb] closed: deadline exceeded while waiting connection
2023/09/19 13:10:20 INF [RTMP] [conn xx.xx.xx.xx:35816] closed: **unable to decode AVCC: invalid NALU**
2023/09/19 13:10:20 INF [RTMP] [conn xx.xx.xx.xx:35818] opened
2023/09/19 13:10:22 INF [RTMP] [conn xx.xx.xx.xx:35818] is publishing to path 'basem', 1 track (H264)

```

## Describe how to replicate the issue

1. start the server

2. publish with DJI Drone ( M350 , Mavic 3 E ) live stream

## Did you attach the server logs?

log level is debug : 
```
2023/09/19 13:15:26 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/09/19 13:15:26 INF [RTMP] listener opened on :1935
2023/09/19 13:15:26 INF [HLS] listener opened on :8888
2023/09/19 13:15:26 INF [WebRTC] listener opened on :8889 (HTTP)
2023/09/19 13:15:26 INF [SRT] listener opened on :8890 (UDP)
2023/09/19 13:15:26 INF [API] listener opened on 0.0.0.0:9997
2023/09/19 13:15:27 INF [RTMP] [conn xx.xx.xx.xx:36402] opened
2023/09/19 13:15:27 DEB [path basem] created
2023/09/19 13:15:27 DEB [path basem] destroyed: not in use
2023/09/19 13:15:27 INF [RTMP] [conn xx.xx.xx.xx:36402] closed: EOF
2023/09/19 13:15:27 INF [RTMP] [conn xx.xx.xx.xx:36404] opened
2023/09/19 13:15:27 DEB [path basem] created
2023/09/19 13:15:30 DEB [path basem] destroyed: not in use
2023/09/19 13:15:30 INF [RTMP] [conn xx.xx.xx.xx:36404] closed: EOF
2023/09/19 13:15:45 INF [RTMP] [conn xx.xx.xx.xx:36458] opened
2023/09/19 13:15:45 DEB [path basem] created
2023/09/19 13:15:47 INF [RTMP] [conn xx.xx.xx.xx:36458] is publishing to path 'basem', 1 track (H264)
2023/09/19 13:16:10 INF [RTMP] [conn xx.xx.xx.xx:36458] closed: unable to decode AVCC: invalid NALU
2023/09/19 13:16:10 DEB [path basem] destroyed: not in use
2023/09/19 13:16:10 INF [RTMP] [conn xx.xx.xx.xx:36460] opened
2023/09/19 13:16:10 DEB [path basem] created
2023/09/19 13:16:12 INF [RTMP] [conn xx.xx.xx.xx:36460] is publishing to path 'basem', 1 track (H264)

```

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, this issue can be solved, but we need a network dump, that can be generated in this way:

1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by Globibluk** [comment]
Hi, I have the same problem with the same setup and drone.
Here is the capture I was able to grab.
[pcappng.zip](https://github.com/bluenviron/mediamtx/files/12685975/pcappng.zip)

**Comment by gitrial** [comment]
same here
2023/09/23 21:15:02 INF [RTMP] [conn 192.168.99.1:33442] is publishing to path 'LiveApp/DRONGS4', 1 track (H264)
2023/09/23 21:15:03 INF [RTMP] [conn 192.168.99.1:33442] closed: unable to decode AVCC: invalid NALU

**Comment by aler9** [comment]
please try this nightly release and let me know if it fixes the issue.

[mediamtx_v1.1.0-15-g4e60e5c_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708177/mediamtx_v1.1.0-15-g4e60e5c_darwin_amd64.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708179/mediamtx_v1.1.0-15-g4e60e5c_darwin_arm64.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708180/mediamtx_v1.1.0-15-g4e60e5c_linux_amd64.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12708181/mediamtx_v1.1.0-15-g4e60e5c_linux_arm64v8.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12708182/mediamtx_v1.1.0-15-g4e60e5c_linux_armv6.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12708183/mediamtx_v1.1.0-15-g4e60e5c_linux_armv7.tar.gz)
[mediamtx_v1.1.0-15-g4e60e5c_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12708184/mediamtx_v1.1.0-15-g4e60e5c_windows_amd64.zip)

**Comment by gitrial** [comment]
> please try this nightly release and let me know if it fixes the issue.
> 
> [mediamtx_v1.1.0-15-g4e60e5c_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708177/mediamtx_v1.1.0-15-g4e60e5c_darwin_amd64.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708179/mediamtx_v1.1.0-15-g4e60e5c_darwin_arm64.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12708180/mediamtx_v1.1.0-15-g4e60e5c_linux_amd64.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12708181/mediamtx_v1.1.0-15-g4e60e5c_linux_arm64v8.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12708182/mediamtx_v1.1.0-15-g4e60e5c_linux_armv6.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12708183/mediamtx_v1.1.0-15-g4e60e5c_linux_armv7.tar.gz) [mediamtx_v1.1.0-15-g4e60e5c_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12708184/mediamtx_v1.1.0-15-g4e60e5c_windows_amd64.zip)

it seems work's fine thanks

**Comment by aler9** [comment]
added in v1.2.0
