### ISSUE TITLE
stopped: timed out when pulling from nginx-rtmp

### ISSUE THREAD

**Issue by teowoz** [bluenviron/mediamtx#2383]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

MediaMTX is unable to pull stream from [nginx-rtmp](https://github.com/arut/nginx-rtmp-module), while FFmpeg reads it correctly.

When pulling from a different instance of nginx-rtmp (not on localhost and with different config), other, unrelated error occurs (`unsupported video codec`) which I'll report later.

## Describe how to replicate the issue

1. start nginx-rtmp on a **non-standard port** e.g. with Docker: `docker run -d -p 1936:1935 --name nginx-rtmp tiangolo/nginx-rtmp`
2. transmit to nginx-rtmp: `ffmpeg -re -f lavfi -i testsrc2=r=25 -f lavfi -i anoisesrc=color=brown -c:v libx264 -g 25 -c:a aac -f flv rtmp://127.0.0.1:1936/live/aaaaaa`
3. start MediaMTX: `MTX_API=true MTX_APIADDRESS=:9997 MTX_LOGLEVEL=debug ./mediamtx mediamtx.yml` (config is the default provided with binary release package)
4. add pull stream using the API: `curl -vv -d '{"source":"rtmp://127.0.0.1:1936/live/aaaaaa","sourceOnDemand":true}' -X POST -H 'Content-Type: application/json' http://localhost:9997/v2/config/paths/add/fromnginx`
5. try to probe stream from MediaMTX: `ffprobe rtmp://localhost/fromnginx`, ffprobe will return `Input/output error` and MediaMTX will show `read tcp 127.0.0.1:38714->127.0.0.1:1936: i/o timeout`
6. see that the same stream is readable using ffprobe directly: `ffprobe rtmp://127.0.0.1:1936/live/aaaaaa`

## Did you attach the server logs?

yes, [timeout_bug_mediamtx.log](https://github.com/bluenviron/mediamtx/files/12673935/timeout_bug_mediamtx.log)

## Did you attach a network dump?
yes
* [not_working.pcap.gz](https://github.com/bluenviron/mediamtx/files/12674105/not_working.pcap.gz) - dump of MediaMTX trying to read from nginx-rtmp and failing
* [working_ffprobe.pcap.gz](https://github.com/bluenviron/mediamtx/files/12674106/working_ffprobe.pcap.gz) - dump of ffprobe reading from nginx-rtmp and showing all streams correctly

**Comment by aler9** [comment]
Hello, thanks for reporting the bug and for providing detailed instructions that allowed to replicate everything. This is fixed by #2520

**Comment by aler9** [comment]
added in v1.2.1
