### ISSUE TITLE
Start Stop Record on demand via API

### ISSUE THREAD

**Issue by moo-the-cow** [bluenviron/mediamtx#2387]
## Describe the feature

Hi,
currently the documentation on https://bluenviron.github.io/mediamtx/ is showing all the API commands.
Is there a chance to get a START and STOP to control recordings on demand?
It is a very common usecase in my opinion. I need to be able to control it without having to modifying the configuration. Thank you!

**Comment by moo-the-cow** [comment]
nevermind. I could control it via http://localhost:9997/v2/config/set which is not

**Comment by aler9** [comment]
While it's possible to control control recording through the API, at the moment enabling/disabling recording on a running stream is not possible, since the stream gets restarted. In order to solve the issue, i've created a feature request here: #2395

**Comment by aler9** [comment]
This has been fixed by #2434

**Comment by aler9** [comment]
added in v1.2.0

**Comment by fotosidla** [comment]
Hello i want to know how to enable/disable recording throught api.
I cannot find [v2/config/set](http://localhost:9997/v2/config/set) in documentation which is provided to api.
Can you tell me how to do it in current version?

I want to record stream from my camera only when i make api call and stop recording when i call this api too.
Thank you

**Comment by MasterShi** [comment]
@fotosidla There is a way to implement your demand, use /v3/config/paths/patch/{name} to switch
