### ISSUE TITLE
WHEP - ETag header is E-Tag

### ISSUE THREAD

**Issue by mfchiz** [bluenviron/mediamtx#2396]
I believe the header "E-Tag" is being used for the the WHEP handshake instead of "ETag" per the spec for WHEP.

https://www.ietf.org/id/draft-murillo-whep-02.html

## Which version are you using?

v1.1.0

## Which operating system are you using?

- [ X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I created a Unity api to view WHEP sources. The code failed looking for "ETag" and it works when "E-Tag" is used. I believe the standard is "ETag"

## Describe how to replicate the issue

Request a WHEP url and review the server logs and see what http headers are being returned.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Fixed in v1.1.1

**Comment by jwalton** [comment]
Note that this is a breaking change - players expecting an `E-Tag` will fail to find one.
