### ISSUE TITLE
[webrtc] /v2/webrtcsessions/kick/{id} always returns 404

### ISSUE THREAD

**Issue by tbnguyen1407** [bluenviron/mediamtx#2398]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

`POST /v2/webrtcsessions/kick/{id}` always returns 404 (Page not found)

`GET /v2/webrtcsessions/get/{id}` show the session exists

## Describe how to replicate the issue

1. start the server
2. create any path
3. read webrtc output
4. call API to kick webrtc session

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i tried to replicate the issue but in my case the server returned code 200.

I listed sessions:

```
curl http://localhost:9997/v2/webrtcsessions/list
{"itemCount":1,"pageCount":1,"items":[{"id":"38958c3e-562d-4a05-b120-801c8afb215b","created":"2023-09-23T09:47:07.114920235Z","remoteAddr":"[::1]:32864","peerConnectionEstablished":true,"localCandidate":"host/udp/192.168.3.20/50124","remoteCandidate":"host/udp/2001:1234:a:b::2/44205","state":"read","path":"test","bytesReceived":6206,"bytesSent":2132697}]}
```

and then kicked the session:

```
curl -v -X POST http://localhost:9997/v2/webrtcsessions/kick/38958c3e-562d-4a05-b120-801c8afb215b
*   Trying 127.0.0.1:9997...
* Connected to localhost (127.0.0.1) port 9997 (#0)
> POST /v2/webrtcsessions/kick/38958c3e-562d-4a05-b120-801c8afb215b HTTP/1.1
> Host: localhost:9997
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: mediamtx
< Date: Sat, 23 Sep 2023 09:48:09 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

If you still have problems, attach server logs with `logLevel: debug`, since they contain return codes of server responses.

**Comment by tbnguyen1407** [comment]
@aler9 my bad. It was typo when I type the url manually. Closing this.
