### ISSUE TITLE
Configuring recording per paths

### ISSUE THREAD

**Issue by GiaNTizmO** [bluenviron/mediamtx#2410]
## Describe the feature

Description

It will be convenient if make the recording configuration more flexible by pointing the recording settings to specific paths
(recordPath recordFormat recordPartDuration recordSegmentDuration recordDeleteAfter).

I haven't studied Golang yet (I don't know this programming language), but if I can, I'll try to commit it myself and send a PR.

**Comment by aler9** [comment]
added in v1.2.0
