### ISSUE TITLE
H265 with flag short_term_ref_pic_set_sps_flag cannot play

### ISSUE THREAD

**Issue by bryandario8** [bluenviron/mediamtx#2417]
## Which version are you using?

v1.1.0
## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I consume a camera stream by hls, I get the following error: `destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)`. So the HLS in the browser doesn't play and I get `levelEmptyError: No Segments found in Playlist`

I see this error happening here [https://github.com/bluenviron/mediacommon/blob/main/pkg/codecs/h265/dts_extractor.go#L82](url)

> if shortTermRefPicSetSpsFlag {
    return 0, fmt.Errorf("short_term_ref_pic_set_sps_flag = true is not supported")
}

What does this restriction mean in DST Extractor?

## Describe how to replicate the issue

1. start the rtsp proxy from docker
2. publish camera rtsp on main stream with H265
3. read camera from browser Chrome/Mozilla

## Did you attach the server logs?

> rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:27 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:27 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:29 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:30 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:30 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:32 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:34 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:34 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:34 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:36 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:36 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:37 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:38 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:38 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:39 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:41 INF [HLS] [muxer 10_245_111_122] created (requested by 10.184.32.134)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:41 INF [HLS] [muxer 10_245_111_122] is converting into HLS, 1 track (H265)
rtsp-proxy-dev-rtsp-proxy-1  | 2023/09/25 23:21:42 INF [HLS] [muxer 10_245_111_122] destroyed (muxer error: unable to extract DTS: short_term_ref_pic_set_sps_flag = true is not supported)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the reason why short_term_ref_pic_set_sps_flag is not supported is just that we've never encountered a H265 with that flag yet. Please attach a network dump, that can be generated in this way:

1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by bryandario8** [comment]
Hello, thanks for your answer 👍 

I followed the instructions and generated the .pcap file, which I attach here

[rtsp-proxy.zip](https://github.com/bluenviron/mediamtx/files/12752044/rtsp-proxy.zip)

I hope for your response!

**Comment by bryandario8** [comment]
Hello @aler9, please your help with this review. I need a solution to be able to view the streaming in realtime without error.

**Comment by aler9** [comment]
Hello, i checked the pcap but unfortunately it doesn't contain the RTSP handshake - it was apparently generated when the stream was already running. We need a pcap that contains the full interaction between the server and the camera, from the moment the server is started to the moment the error appears.

**Comment by bryandario8** [comment]
Sorry, I didn't take the logs from the start. This time I followed your recommendation, thank you.
[rtsp-proxy2.zip](https://github.com/bluenviron/mediamtx/files/12852781/rtsp-proxy2.zip)

**Comment by aler9** [comment]
Thanks for providing all the material that allowed to successfully replicate the bug. Please test  this nightly release (that includes https://github.com/bluenviron/mediacommon/pull/95) and let me know whether it fixes the issue.

[mediamtx_v1.1.1-32-g9de6423_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12858176/mediamtx_v1.1.1-32-g9de6423_darwin_amd64.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12858178/mediamtx_v1.1.1-32-g9de6423_darwin_arm64.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12858179/mediamtx_v1.1.1-32-g9de6423_linux_amd64.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12858182/mediamtx_v1.1.1-32-g9de6423_linux_arm64v8.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12858187/mediamtx_v1.1.1-32-g9de6423_linux_armv6.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12858194/mediamtx_v1.1.1-32-g9de6423_linux_armv7.tar.gz)
[mediamtx_v1.1.1-32-g9de6423_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12858196/mediamtx_v1.1.1-32-g9de6423_windows_amd64.zip)

**Comment by aler9** [comment]
added in v1.2.0
