### ISSUE TITLE
There is no audio during webrtc playback after ffmpeg transcoding

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#2419]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

Hello, when I use ffmpeg transcoding rtsp streams, there is no audio, and when I don't use ffmpeg, there is audio.
"ffmpeg -rtsp_transport tcp -i " + sourceUrl + "  -vcodec libx264 -preset:v ultrafast -r 25 -keyint_min 25 -g 25 -sc_threshold 0 -threads 6  -b:v 2048k  -c:a libmp3lame -b:a 128k  -f  rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH";

## Did you attach the server logs?

 no

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
What protocol are you using to read the stream? if you're using HLS, then MP3 is not supported.

**Comment by liusuyi2021** [comment]
I use webrtc
