### ISSUE TITLE
Problems with ETag in whip.js

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#2420]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

After updating to version 1.1.1, the whep class of webrtc was unable to obtain an E-Tag. After testing, I found that you changed the E-Tag to ETag after this update, which caused me to stay at 400

![image](https://github.com/bluenviron/mediamtx/assets/86584277/d93a1a77-78f0-4903-878c-88e7dd4fd379)

## Did you attach the server logs?

 no

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Hello, it turned out that the specification prescribes to use ETag instead of E-Tag:

https://datatracker.ietf.org/doc/draft-murillo-whep/

So the previous implementation was wrong.
