### ISSUE TITLE
Mediamtx mavic 2

### ISSUE THREAD

**Issue by Cypher140** [bluenviron/mediamtx#2422]
Bonjour,

Je n’arrive pas streamer avec le ma ic 2 enterprise) alors que cela fonctionne bien avec le mavic 3 et matrice 300.

J’ai constaté que le taux de fps est de 5 au lieu de 30. Peut être que l’info est erronée ?

Le flux semble partir vers le serveur mais il n’y a pas d’affichage même avec des lag.
Connaissez-vous ce problème ? 

## Which version are you using?

v0.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Please reopen the issue and fill the template correctly or open a discussion. In both cases, provide relevant data that allows to replicate the issue (server logs with logLevel set to debug is a start).
