### ISSUE TITLE
Support the web browser formats compatible with the mpegts.js player library

### ISSUE THREAD

**Issue by rgl** [bluenviron/mediamtx#2424]
## Describe the feature

Currently, mediamtx supports the WHEP protocol; since it seems to still be in development stage, would it possible to support the simpler(?) [web protocols compatible with the mpegts.js player library](https://github.com/xqq/mpegts.js/blob/master/docs/livestream.md)?

For reference, they support:

* MPEG2-TS over HTTP
* HTTP FLV
* MPEG2-TS/FLV over WebSocket

**Comment by aler9** [comment]
Hello, all the protocols you listed are less versatile and slower than Low-latency HLS, which can be played with [hls.js](https://github.com/video-dev/hls.js).

Regarding WebRTC/WHEP, there's a [reference JS implementation](https://github.com/medooze/whip-whep-js) available from the author of the specification.
