### ISSUE TITLE
[RTMP] Fatal panic when calling the RTMP API while starting the stream at the same time

### ISSUE THREAD

**Issue by Paxx-RnD** [bluenviron/mediamtx#2430]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [x] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The application panics and there is no way of avoiding it. This happens when mediamtx receives a stream and in the same moment you ask the get streams api.
I've only tried with RTMP but this could also be the case with also the other protocols (srt, hls, webrtc, rtsp)
I'm guessing it's some kind of concurrency issue.
Please help because this issue is really critical for my use case, I need to get the status of the connections quite often and I can't have this issue in production. Thanks

## Describe how to replicate the issue

1. start the server
2. publish a stream with rtmp
3. call the http://localhost:9997/v2/rtmpconns/list API

## Did you attach the server logs?
[serverlogs.txt](https://github.com/bluenviron/mediamtx/files/12748305/serverlogs.txt)

yes

## Did you attach a network dump?

no

**Comment by Allan-Nava** [comment]
+1

**Comment by aler9** [comment]
fixed by #2431

**Comment by aler9** [comment]
added in v1.2.0
