### ISSUE TITLE
Encode errors cause recordings to stop without retries

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#2439]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Encode errors cause recordings to stop without retries

## Describe how to replicate the issue

1. start the server
2. publish
3. wait for a record error
   ```
    ERR [path 64/high] [record] DTS is not monotonically increasing, was 21h32m36.01s, now is 21h32m36.01s
   ```
4. recording doesn't restart

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by mateothegreat** [comment]
This suggests that within the input file, the timestamps linked to individual samples do not follow a consistent pattern of increasing values.

The best outcome would be to fix the input.

But of course that's a bigger problem for the big wigs to solve! Next could be for the output to attempt to align these values which isn't bullet proof.

I can help tackle hard crash on an effective warning and see what can be enhanced if ya want. Just tap me in @aler9!
