### ISSUE TITLE
Hook for runOnRecordSegmentStart

### ISSUE THREAD

**Issue by itsparth** [bluenviron/mediamtx#2451]
## Describe the feature
Hook for runOnRecordSegmentStart

Description
I am saving recorded segments to database for a timeline view, currently I have to watch the output directory for segments. It would be great if we can have a hook once there is actual segment being created.

**Comment by aler9** [comment]
Hello, `runOnRecordSegmentCreate` is being added with #2451

**Comment by aler9** [comment]
added in v1.2.0
