### ISSUE TITLE
Playback API to serve recorded segments

### ISSUE THREAD

**Issue by itsparth** [bluenviron/mediamtx#2452]
## Describe the feature
Is there any way for playback of recorded fmp4's, maybe we can expose an stream url which converts an fmp4 file to mpeg dash or hls on demand

**Comment by mateothegreat** [comment]
Just transcode it, it's supported out of the box and is in the `README.md` file.
As far as serving fmp4 in your scenario how does dash play in to this (rather than HLS)?

**Comment by aler9** [comment]
An API for serving recording segments is planned and that's one of the reasons why fMP4 was chosen as format, since it can be played by browsers.

**Comment by saket424** [comment]
@aler9 
I have this situation where the HLS h265 feed only plays on Apple Mac Safari and Chrome but not on Linux Chrome
Would this new fMP4 feature allow us to support H265 read in all browsers if it is closer to dash
Thanks
Anand

**Comment by saket424** [comment]
@aler9 
Is this table accurate?
https://github.com/AlexxIT/go2rtc#codecs-madness
So far I am unsuccessful in getting hls working on Linux chrome for example

**Comment by aler9** [comment]
@saket424 H265 is unsupported by Chrome on Linux, independently from MediaMTX. There's a section in the README that provides a tool that allows to find out what codecs are supported by your browser:

https://github.com/bluenviron/mediamtx#hls

DASH doesn't have particular advantages over Low-Latency HLS, they support the same codecs (that are imposed by browsers anyway), so there's not a reason to add support for it yet.

Anyway, this feature request is related to a playback API, so HLS is off topic.

**Comment by aler9** [comment]
Fixed by #2906
