### ISSUE TITLE
Option to change orientation of proxied streams

### ISSUE THREAD

**Issue by kondas** [bluenviron/mediamtx#2462]
## Describe the feature

Hi, I'm using mediamtx to proxy RTSP streams from cameras that only handle 1-2 direct clients. The cameras only offer to rotate the picture 180'. I did not find possibility in mediamtx to rotate 90', but it would be very helpful for my situation. Is it possible to have this feature in mediamtx?

**Comment by pkerney** [comment]
Just use ffmpeg to rotate the stream and publish on another path. This is effectively transcoding. There's an example of scaling to lower resolution in the README.md. Similar process but use different ffmeg options.

**Comment by kondas** [comment]
> ...

Thanks a lot for the eye opening, it's really easy indeed. 


`
paths:
  all:
  original:
    source: rtsp://ipc.lan/stream
    runOnReady: >
      ffmpeg -i rtsp://localhost:8554/original-vf "transpose=1" -f rtsp rtsp://localhost:8554/flipped
    runOnReadyRestart: yes
`
