### ISSUE TITLE
Allow SRT access control syntax

### ISSUE THREAD

**Issue by moschopsuk** [bluenviron/mediamtx#2469]
## Describe the feature
At the moment mediamtx way of handling SRT streams seems to be rather custom approach to using

`(play|publish):(stream-key):[user]:[password]`

As a means to differentiate if it is a client playing or publishing, the stream key/id 

It would be a good idea if mediamtx could also support the access control methods as defined in the SRT feature docs prefixing the streamed with `#!::` then using the standard keys as a means to identify if it is play/publish and the other relevant credentials:
https://github.com/Haivision/srt/blob/master/docs/features/access-control.md

I’ve come across some hardware SRT encoders will only support the such as the Blackmagic Web presenter, that only support the SRT defined access control keys and such are incompatible with mediamtx.

**Comment by aler9** [comment]
Hello, thanks for reporting the documentation and the use case, this is fixed by #2919

**Comment by moschopsuk** [comment]
Thank you!
