### ISSUE TITLE
RTSP source not working

### ISSUE THREAD

**Issue by sharmasulekh87** [bluenviron/mediamtx#2473]
## Which version are you using?

v1.1.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTSP source was working upto version 1.0.0, but gives following error after upgrading to 1.1.0:
2023/10/07 17:41:17 ERR [path test] [RTSP source] invalid SDP: session name not present

## Describe how to replicate the issue

simply start the server with RTSP camera source, and it gives directly error 

1. start the server
2. publish with RTSP Source 
3. read with RTSP

## Did you attach the server logs?

[mediamtx_v1.1.0.log](https://github.com/bluenviron/mediamtx/files/12837737/mediamtx_v1.1.0.log)
[mediamtx_v1.0.0.log](https://github.com/bluenviron/mediamtx/files/12837739/mediamtx_v1.0.0.log)

yes 

The same rtsp url is working in version 1.0.0 . Logs attached.
But not working in version 1.1.0. Logs attached.
## Did you attach a network dump?

 no

**Comment by sealbro** [comment]
Hi, the same problem on Linux with docker mediamtx 1.1.1

<img width="681" alt="image" src="https://github.com/bluenviron/mediamtx/assets/8067559/5ad85503-6f2a-4444-bd04-fd4212d58a83">

**Comment by aler9** [comment]
Thanks for providing all required material (server logs) that allowed to fix the issue. This is fixed by https://github.com/bluenviron/gortsplib/pull/439

**Comment by aler9** [comment]
added in v1.2.0
