### ISSUE TITLE
webrtc play the video, but no sound is received

### ISSUE THREAD

**Issue by 810961186** [bluenviron/mediamtx#2481]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Webrtc webpage plays video but cannot receive sound

## Describe how to replicate the issue

1. start the server
2. The webpage uses the webrtc address to play the video, but no sound is received.

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by liusuyi2021** [comment]
声音格式要匹配 源rtsp流是否有声音，据我所知 这个跟mediaMTX没关系

**Comment by 810961186** [comment]
源rtsp流是有声音的，
![image](https://github.com/bluenviron/mediamtx/assets/30916252/d7303c90-61c1-4406-915d-26a50a33c743)
浏览器播放视频，video获取不到声音流

**Comment by liusuyi2021** [comment]
不知道你用的是不是海康相机，流分复合流和视频流，复合流才有音频

**Comment by liusuyi2021** [comment]
还有不知道你是否使用了ffmpeg转码，转码不做音频转码也是没声音的

**Comment by 810961186** [comment]
通过api添加onvif视频源，使用rtsp,hls，rtmp播放都有声音，只有使用webrtc播放没有声音，不知道是什么原因

**Comment by liusuyi2021** [comment]
rtsp rtmp 你用vlc播放的吧，webrtc的js 你从哪搞的 你直接用mediamtx提供的js试过？

**Comment by 810961186** [comment]
webrtc 直接用mediamtx提供的js试过,没有声音

**Comment by liusuyi2021** [comment]
那就等作者吧 我这都有声音，跟mediamtx没关系
![image](https://github.com/bluenviron/mediamtx/assets/86584277/905ecfc4-f633-47fc-b7a3-23e4bf93ed07)

**Comment by aler9** [comment]
As explicitly mentioned in multiple parts of the README, WebRTC supports only a limited number of audio codecs. Make sure that your audio is encoded with one of the supported codec or switch to HLS.

**Comment by liusuyi2021** [comment]
你可以使用这个来看你浏览器支持的格式：
  console.log(RTCRtpReceiver.getCapabilities('video').codecs)
  console.log(RTCRtpReceiver.getCapabilities('audio').codecs)

**Comment by 810961186** [comment]
谢谢，应该是视频源的声音编码问题，通过Api添加的视频源估计转的是标准aac的编码
