### ISSUE TITLE
VLC changes the path of the stream

### ISSUE THREAD

**Issue by Multistarshoot** [bluenviron/mediamtx#2487]
Hey,

## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I start an rtsp stream on the port 8553 which is detected by the server =>publishing to path '/live/s22ultra', 1 track MPEG-TS
I open vlc and try to open rtsp://[MyIPv6]:8553/live/s22ultra/
vlc gives me an error and when I look at the logs I see that the path has changed to /stream=0 which is not a valid name

## Describe how to replicate the issue

1. Start the mediamtx container on a synology NAS (DS923+)
2. Publish with TakICU to wowza server with an IPv6 and port 8553. No login/pass. Alias = s22ultra
3. Read with vlc rtsp://[IPv6]:8553/live/s22ultra/

## Did you attach the server logs?

2023/10/10 19:18:22 | stdout | [90m2023/10/10 17:18:22 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49206] closed: invalid path name: can contain only alphanumeric characters, underscore, dot, tilde, minus or slash (stream=0)
-- | -- | --
2023/10/10 19:18:22 | stdout | [90m2023/10/10 17:18:22 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49206] opened
2023/10/10 19:18:21 | stdout | [90m2023/10/10 17:18:21 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49204] closed: invalid URL (/stream=0/)
2023/10/10 19:18:21 | stdout | [90m2023/10/10 17:18:21 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49204] opened
2023/10/10 19:17:41 | stdout | [90m2023/10/10 17:17:41 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49066] closed: invalid path name: can't end with a slash (stream=0/)
-- | -- | --
2023/10/10 19:17:41 | stdout | [90m2023/10/10 17:17:41 [0m[32mINF[0m [RTSP] [conn 192.168.0.100:49066] opened
2023/10/10 19:17:33 | stdout | [90m2023/10/10 17:17:33 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:17:18 | stdout | [90m2023/10/10 17:17:18 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:17:16 | stdout | [90m2023/10/10 17:17:16 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:17:11 | stdout | [90m2023/10/10 17:17:11 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:17:00 | stdout | [90m2023/10/10 17:17:00 [0m[32mINF[0m [RTSP] [session 040627dc] destroyed: not in use
2023/10/10 19:17:00 | stdout | [90m2023/10/10 17:17:00 [0m[32mINF[0m [RTSP] [conn [ipv6]:60269] closed: path has changed, was '/live/s22ultra', now is '/stream=0'
2023/10/10 19:17:00 | stdout | [90m2023/10/10 17:17:00 [0m[32mINF[0m [RTSP] [session 040627dc] created by [ipv6]:60269
2023/10/10 19:17:00 | stdout | [90m2023/10/10 17:17:00 [0m[32mINF[0m [RTSP] [conn [ipv6]:60269] opened
2023/10/10 19:17:00 | stdout | [90m2023/10/10 17:17:00 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:16:40 | stdout | [90m2023/10/10 17:16:40 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 2 RTP packets lost
2023/10/10 19:16:34 | stdout | [90m2023/10/10 17:16:34 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 2 RTP packets lost
2023/10/10 19:16:29 | stdout | [90m2023/10/10 17:16:29 [0m[1;33mWAR[0m [RTSP] [session a8c4e0c5] 1 RTP packet lost
2023/10/10 19:15:45 | stdout | [90m2023/10/10 17:15:45 [0m[32mINF[0m [RTSP] [session a8c4e0c5] is publishing to path 'live/s22ultra', 1 track (MPEG-TS)
2023/10/10 19:15:45 | stdout | [90m2023/10/10 17:15:45 [0m[32mINF[0m [RTSP] [session a8c4e0c5] created by [ipv6]:55318
2023/10/10 19:15:45 | stdout | [90m2023/10/10 17:15:45 [0m[32mINF[0m [RTSP] [conn [ipv6]:55318] opened

## Did you attach a network dump?

no

Thanks :)

**Comment by Multistarshoot** [comment]
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [conn 192.168.0.110:52700] closed: EOF
-- | -- | --
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [conn 192.168.0.110:52700] opened
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [session 0000cbc6] destroyed: not in use
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [conn 192.168.0.110:52688] closed: path has changed, was '/live/s22ultra', now is '/stream=0'
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [session 0000cbc6] created by 192.168.0.110:52688
2023/10/11 08:54:53 | stdout | [90m2023/10/11 06:54:53 [0m[32mINF[0m [RTSP] [conn 192.168.0.110:52688] opened
2023/10/11 08:54:05 | stdout | [90m2023/10/11 06:54:05 [0m[32mINF[0m [RTSP] [session 2a664f74] is publishing to path 'live/s22ultra', 1 track (MPEG-TS)
2023/10/11 08:54:05 | stdout | [90m2023/10/11 06:54:05 [0m[32mINF[0m [RTSP] [session 2a664f74] created by 192.168.0.105:57950
2023/10/11 08:54:05 | stdout | [90m2023/10/11 06:54:05 [0m[32mINF[0m [RTSP] [conn 192.168.0.105:57950] opened
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m [SRT] listener opened on :8890 (UDP)
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m [WebRTC] listener opened on :8889 (HTTP)
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m [HLS] listener opened on :8888
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m [RTMP] listener opened on :1935
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/10/11 08:51:29 | stdout | [90m2023/10/11 06:51:29 [0m[32mINF[0m MediaMTX v1.1.1

Just tried it directly inside the LAN without using IPv6 and I get the same results

**Comment by Multistarshoot** [comment]
Found the issue: 

Tried to open with vlc using Windows 10 and it worked. So my guess is that there's an issue with vlc on Linux.

**Comment by Dronakurl** [comment]
Is there anyone, who solved this on linux?

**Comment by aler9** [comment]
The issue with VLC on Ubuntu (and remediation) is fully documented inside the README:

https://github.com/bluenviron/mediamtx?tab=readme-ov-file#ubuntu-bug
