### ISSUE TITLE
Error while loading shared libraries: libcamera.so.0.0:

### ISSUE THREAD

**Issue by HopWorks** [bluenviron/mediamtx#2495]
## Which version are you using?

v1.1.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Error thrown by mediamtx - 

## Describe how to replicate the issue
With the configuration set to rpiCamera, I get this when starting the mediamtx server. 

Linux 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux
MediaMTX v1.1.1

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?
2023/10/11 19:07:20 INF MediaMTX v1.1.1
2023/10/11 19:07:20 DEB [path cam] created
2023/10/11 19:07:20 DEB path manager created
2023/10/11 19:07:20 INF [path cam] [RPI Camera source] started
2023/10/11 19:07:20 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/10/11 19:07:20 INF [RTMP] listener opened on :1935
2023/10/11 19:07:20 INF [HLS] listener opened on :8888
2023/10/11 19:07:20 INF [WebRTC] listener opened on :8889 (HTTP)
2023/10/11 19:07:20 INF [SRT] listener opened on :8890 (UDP)
2023/10/11 19:07:20 ERR [path cam] [RPI Camera source] process exited unexpectedly
2023/10/11 19:07:25 ERR [path cam] [RPI Camera source] process exited unexpectedly
2023/10/11 19:07:27 INF shutting down gracefully
2023/10/11 19:07:27 INF [SRT] listener is closing
2023/10/11 19:07:27 INF [WebRTC] listener is closing
2023/10/11 19:07:27 INF [HLS] listener is closing
2023/10/11 19:07:27 INF [RTMP] listener is closing
2023/10/11 19:07:27 INF [RTSP] listener is closing
2023/10/11 19:07:27 DEB path manager is shutting down
2023/10/11 19:07:27 INF [path cam] [RPI Camera source] stopped: path is closing
2023/10/11 19:07:27 DEB [path cam] destroyed: terminated
2023/10/11 19:07:27 INF waiting for running hooks

...FROM A SEARCH FOR THE FILE NEEDED...
$ sudo find / -type f -name "libcamera*"
/usr/bin/libcamera-vid
/usr/bin/libcamera-jpeg
/usr/bin/libcamera-raw
/usr/bin/libcamera-hello
/usr/bin/libcamera-still
/usr/include/libcamera-apps/core/libcamera_encoder.hpp
/usr/include/libcamera-apps/core/libcamera_app.hpp
/usr/lib/arm-linux-gnueabihf/libcamera_app.so.1.2.1
/usr/lib/arm-linux-gnueabihf/libcamera-base.so.0.1.0
/usr/lib/arm-linux-gnueabihf/libcamera.so.0.1.0
/var/lib/dpkg/info/libcamera0.1:armhf.shlibs
/var/lib/dpkg/info/libcamera0.1:armhf.md5sums
/var/lib/dpkg/info/libcamera-ipa:armhf.list
/var/lib/dpkg/info/libcamera0.1:armhf.triggers
/var/lib/dpkg/info/libcamera-apps-lite.md5sums
/var/lib/dpkg/info/libcamera-apps-lite.triggers
/var/lib/dpkg/info/libcamera-ipa:armhf.md5sums
/var/lib/dpkg/info/libcamera-apps-lite.shlibs
/var/lib/dpkg/info/libcamera0.1:armhf.list
/var/lib/dpkg/info/libcamera-apps-lite.list

no

## Did you attach a network dump?

no

The file I found on my system (DietPi Bookworm) is /usr/lib/arm-linux-gnueabihf/libcamera.so.0.1.0 when it looks like /usr/lib/arm-linux-gnueabihf/libcamera.so.0.0 is what is needed.

Not sure where to go with this. I thought the issue was fixed. Is there something I can do with my configuration to fix this?

Thanks

**Comment by aler9** [comment]
Hello, precompiled binaries are not compatible with DietOS Bookworm but only with Raspberry Pi OS Bullseye, as explicitly mentioned in the README. You can compile the server from source and generate a DietOS-compatible binary by following instructions here:

https://github.com/bluenviron/mediamtx#compile-from-source
