### ISSUE TITLE
On OpenWRT timezone is not used

### ISSUE THREAD

**Issue by Sunvas** [bluenviron/mediamtx#2511]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (please describe) OpenWRT 23.05

## Describe the issue

I'm using recording feature and I've noticed that time variables in `recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f` 
consist UTC+0 time and timezone set in OpenWRT settings is not taken into account.

## Describe how to replicate the issue

0. prepare OpenWRT environment.
1. set up the recording streams to disk feature. You should use time variables for  `recordPath` option.
2. set timezone other than UTC+0.
3. start the server on OpenWRT
4. publish with [doesn't matter]
5. read with [doesn't matter]
6. set recording streams to disk 
7.  you can see that stored filenames consist UTC+0 time.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, make sure that the `zonename` option is set inside `/etc/config/system`:

```
config system
        option hostname 'OpenWrt'
        option zonename 'Africa/Juba'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'
```

then install package `zoneinfo-all`:

```
opkg update && opkg install zoneinfo-all
```

then reload the system:

```
/etc/init.d/system restart
```

Then MediaMTX or any other Golang program will be able to read the time zone correctly.

You can find more details about the issue here: https://stackoverflow.com/questions/54035376/why-running-golangs-time-now-at-openwrt-always-get-utc-time

**Comment by Sunvas** [comment]
That works.
