### ISSUE TITLE
externalAuthenticationURL + OBS causes crash loop when streaming srt

### ISSUE THREAD

**Issue by jbrough** [bluenviron/mediamtx#2516]
## Which version are you using?

trunk

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

when ` overridePublisher: yes` (the default) and `externalAuthenticationURL` is provided, and connecting to an srt stream via OBS, mediamtx will successfully authenticate but then immediately depublish the stream causing OBS to reconnect and there's basically a crash loop where OBS continually disconnects/reconnects to publish to the same streamid.

The issue is here:

https://github.com/bluenviron/mediamtx/blob/c25b51cc7eb2d410332b6d8988236ad9400920ff/internal/core/path.go#L628

And this happens when a *single* stream is being published by a *single* publisher. It may be how OBS handles the connection when there is authentication middleware.

It works fine without `externalAuthenticationURL`

the issue is resolved by changing the default to be ` overridePublisher: no`  - then a stream is authenticated and not dropped. This is satisfactory but something causes mediamtx to think the published stream is being overwritten when  working with an external http auth service.

Description

## Describe how to replicate the issue

see above

## Did you attach the server logs?

no

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Hello, i tested publishing with OBS 30.0, SRT, MediaMTX v1.3.0, external authentication and everything worked flawlessly.

External authentication:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"

	"github.com/gin-gonic/gin"
)

type server struct {
	s *http.Server
}

func newServer() (*server, error) {
	ln, err := net.Listen("tcp", ":9120")
	if err != nil {
		return nil, err
	}

	ts := &server{}

	router := gin.New()
	router.POST("/auth", ts.onAuth)

	ts.s = &http.Server{Handler: router}
	go ts.s.Serve(ln)

	return ts, nil
}

func (ts *server) close() {
	ts.s.Shutdown(context.Background())
}

func (ts *server) onAuth(ctx *gin.Context) {
	var in struct {
		IP       string `json:"ip"`
		User     string `json:"user"`
		Password string `json:"password"`
		Path     string `json:"path"`
		Action   string `json:"action"`
		Query    string `json:"query"`
	}
	err := json.NewDecoder(ctx.Request.Body).Decode(&in)
	if err != nil {
		ctx.AbortWithStatus(http.StatusBadRequest)
		return
	}

	fmt.Printf("%+v\n", in)

	if in.User == "" {
		ctx.AbortWithStatus(http.StatusUnauthorized)
		return
	}

	ctx.Status(http.StatusOK)
}

func main() {
	_, err := newServer()
	if err != nil {
		panic(err)
	}
	select {}
}
```

server configuration:

```yml
externalAuthenticationURL: http://127.0.0.1:9120/auth
```

server logs:

```
2023/12/09 22:45:50 INF MediaMTX v0.0.0
2023/12/09 22:45:50 INF configuration loaded from /home/ale/dev/mediamtx/mediamtx.yml
2023/12/09 22:45:50 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/12/09 22:45:50 INF [RTMP] listener opened on :1935
2023/12/09 22:45:50 INF [HLS] listener opened on :8888
2023/12/09 22:45:50 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2023/12/09 22:45:50 INF [SRT] listener opened on :8890 (UDP)
2023/12/09 22:45:52 INF [SRT] [conn 127.0.0.1:55076] opened
2023/12/09 22:45:52 INF [SRT] [conn 127.0.0.1:55076] is publishing to path 'test', 2 tracks (H264, MPEG-4 Audio)
```

OBS settings:

![Screenshot_20231209_224628](https://github.com/bluenviron/mediamtx/assets/46489434/38ae3ea4-86fe-4f4a-b9e0-8596c52b2243)

If you still have problems, open another issue and provide more details, including server version, OBS version and expecially server logs, otherwise it's not possible to understand what's going on.
