### ISSUE TITLE
Cross domain issues in webrtc

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#2540]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

Webrtc public network access can be played through the js provided by mediaMTX, but there are cross domain issues embedded in the video tag that cannot be played. Do you have any solutions to cross domain issues

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
CORS options are in the configuration file. If you still have problems, open another issue and fill correctly all fields as explicitly told in the instructions.
