### ISSUE TITLE
Recordings are not streamable

### ISSUE THREAD

**Issue by hlacikd** [bluenviron/mediamtx#2543]
## Describe the feature

I am using new recordings feature, where i am storing 5m Long video chunks using fmpeg4 .

Source is h265 encoded rtsp stream (from gstreamer) with keyframes set after 25frames.

When i expose those recordings via nginx as mp4 video,  i expect from media players like vlc to immediately start playback from remote source, which Unfortunately is not case and whole video needs to be downloaded.

When i save this stream to mkv containers (using gstreamer again) i can stream it. So source is not the issue.

Can those recordings have keyframes added so I can stream it ?

**Comment by 0ip** [comment]
Sometimes I have the problem with my records too, but there it's because they have an incorrect duration. See issue #2477 Can you see if this is also the case with you?
