### ISSUE TITLE
not run hook

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#2548]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (LXC)

## Describe the issue

When the mediamtx server is stopped while the file is being written, the "runOnRecordSegmentComplete" hook is not executed, but the file is saved.
## Describe how to replicate the issue

1. start the server
2. add path
3. delay 4 min 30 sec(File recording duration 1 minute)
4. stop server

if you set "runOnRecordSegmentComplete" for example: sh -c 'echo $MTX_PATH" Complete" >> /etc/rss/mtx/$MTX_PATH.log', then the hook will not be executed for the last file.

## Did you attach the server logs?

yes / **no**

## Did you attach a network dump?

yes / **no**

**Comment by aler9** [comment]
Hello, i tried to replicate the issue with MediaMTX v1.3.0, in my case the `runOnRecordSegmentComplete` hook corresponding to the last segment was called correctly during server shutdown.

Configuration:

```yml
pathDefaults:
  record: yes
  runOnRecordSegmentComplete: sh -c 'echo complete'
```

Logs:

```
2023/12/09 23:19:55 INF MediaMTX v0.0.0
2023/12/09 23:19:55 INF configuration loaded from /home/ale/dev/mediamtx/mediamtx.yml
2023/12/09 23:19:55 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/12/09 23:19:55 INF [RTMP] listener opened on :1935
2023/12/09 23:19:55 INF [HLS] listener opened on :8888
2023/12/09 23:19:55 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2023/12/09 23:19:55 INF [SRT] listener opened on :8890 (UDP)
2023/12/09 23:19:56 INF [SRT] [conn 127.0.0.1:58839] opened
2023/12/09 23:19:56 INF [path test] [record] recording 2 tracks
2023/12/09 23:19:56 INF [SRT] [conn 127.0.0.1:58839] is publishing to path 'test', 2 tracks (H264, MPEG-4 Audio)
^C2023/12/09 23:20:08 INF shutting down gracefully
2023/12/09 23:20:08 INF [SRT] listener is closing
2023/12/09 23:20:08 INF [path test] [record] recording stopped
2023/12/09 23:20:08 INF [path test] runOnRecordSegmentComplete command launched
2023/12/09 23:20:08 INF [SRT] [conn 127.0.0.1:58839] closed: terminated
2023/12/09 23:20:08 INF [WebRTC] listener is closing
2023/12/09 23:20:08 INF [HLS] listener is closing
2023/12/09 23:20:08 INF [RTMP] listener is closing
2023/12/09 23:20:08 INF [RTSP] listener is closing
2023/12/09 23:20:08 INF waiting for running hooks
complete
```

If you still have problems, attach server logs, otherwise it's impossible to understand what's going on.
