### ISSUE TITLE
Unable to stream Mavic 2 Enterprise Dual RTMP stream due to unsupported video codec

### ISSUE THREAD

**Issue by blimper123** [bluenviron/mediamtx#2556]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

It's a little unclear as to whether it's the server or the software, but I figured I'd put it in here as well just in case.

When attempting to connect to mediamtx with the DJI Mavic 2 Enterprise Dual's RTMP streaming capabilities, I will receive an error saying, "closed (unsupported video codec: #)". I'm not including a specific number because it has changed several times. I've gotten the numbers 2, 3, 4, and 9 and am still unsure what the significance is for each number.

When using wireshark, I was able to determine that the drone/software is sending H.264 video, so it seems odd that the stream would have an unsupported video codec. My team and I are a little stumped on what the issue could be

## Describe how to replicate the issue

1. start the server
2. start mavic 2 enterprise dual drone + DJI Pilot
3. connect to drone > tap top right corner with three dots > tap three dots on side bar > live stream
4. set up custom RTMP url to mediamtx server
5. server shows multiple errors

## Did you attach the server logs?

yes
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/13126830/mediamtx.log)

## Did you attach a network dump?

yes

[dronecapture.zip](https://github.com/bluenviron/mediamtx/files/13127003/dronecapture.zip)

**Comment by aler9** [comment]
Hello, this should be fixed by #2808. Please test this nightly release and let me know if it works (click on artifacts, binaries):
https://github.com/bluenviron/mediamtx/actions/runs/7207849258
