### ISSUE TITLE
SDP: invalid numeric value

### ISSUE THREAD

**Issue by dmitry-oshurkov** [bluenviron/mediamtx#2558]
## Which version are you using?

v0.21.5
v1.2.0

## Which operating system are you using?

- [x] Linux amd64 Docker

## Describe the issue

RTSP from some cameras not working: ``` [rtsp source] ERR: sdp: invalid numeric value `1698210468.800125` ```.
Same error occurrs at last version too.
ffplay with these cameras working fine.

## Describe how to replicate the issue

1. start the server with RTSP source

## Did you attach the server logs?

[rtsp.log](https://github.com/bluenviron/mediamtx/files/13161715/rtsp.log)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, thanks for posting the log, this is fixed by https://github.com/bluenviron/gortsplib/pull/455

**Comment by aler9** [comment]
added in v1.2.1
