### ISSUE TITLE
RTMP URLs have /appname/streamname

### ISSUE THREAD

**Issue by winkmichael** [bluenviron/mediamtx#2563]
## Describe the feature

By default all RTMP URLs have a /appname/ typically /public/ or /private/ followed by the streamname. However it appears MediaMTX only supports one value after the /mystream /stream etc, if both are included, you get an error "path is not configured." 

It would be ideal to support /appname/streamname

Thanks

**Comment by aler9** [comment]
The server already supports this. Make sure that the "paths" section of the configuration either includes "all_others" or "/appname/streamname".
