### ISSUE TITLE
Unable to stream DJI Mini 4 Pro RTMP stream due to unsupported audio codec

### ISSUE THREAD

**Issue by VALVD77** [bluenviron/mediamtx#2564]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Attempting to connect to MediaMTX with the DJI Mini 4 Pro and RC 331 RTMP streaming capabilities.
I receive an error saying, "closed: unsupported audio codec: 15"

## Describe how to replicate the issue

1. start the server
2. start the DJI Mini 4 Pro
3. start DJI RC 331
4. On RC, tap top right corner with three dots > Live stream
5. publish with custom rtmp url to mediamtx server
6. server shows errors

## Did you attach the server logs?

yes
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/13175772/mediamtx.log)
[mediamtx-debug.log](https://github.com/bluenviron/mediamtx/files/13175773/mediamtx-debug.log)

## Did you attach a network dump?

no

**Comment by moo-the-cow** [comment]
I have the same issue, it's making mediamtx unusable, so I had to replace it with nginx-rtmp (which works)

**Comment by aler9** [comment]
Hello, this should be fixed by #2808. Please test this nightly release and let me know if it works (click on artifacts, binaries):
https://github.com/bluenviron/mediamtx/actions/runs/7207849258
