### ISSUE TITLE
nginx-rtmp push (invalid body size)

### ISSUE THREAD

**Issue by winkmichael** [bluenviron/mediamtx#2568]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When streaming directly from ffmpeg to mediaMTX, everything functions as expected. However, when attempting to push from nginx-rtmp to mediaMTX's, I get an 'invalid body size' error.

## Describe how to replicate the issue

MediaMTX IP = 192.168.1.20
 ffmpeg -re -stream_loop -1 -i avatar.mp4 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -g 30 -f flv rtmp://192.168.1.20/test/test1
 ^ no problem

nginx-rtmp = 192.168.1.22
 ffmpeg -re -stream_loop -1 -i avatar.mp4 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -g 30 -f flv rtmp://192.168.1.22/test/test1 
^ no problem

Add a push command to nginx-rtmp 
push rtmp://192.168.1.20/; Restart nginx-rtmp 

Error message
2023/10/26 12:59:10 INF [RTMP] [conn 192.168.1.20:1073] closed: invalid body size

## Did you attach the server logs?

No, but I can provide ssh login to a test virtual machine to show this setup in action. I can put everyone on a single machine.

## Did you attach a network dump?

No, I've tried going back to the release before the "invalid body size" code was added, but it doesn't work either, no error.

**Comment by aler9** [comment]
Hello, this may be solved by #2808; please test the nightly release available here (click on artifacts, binaries) and let me know if it works:
https://github.com/bluenviron/mediamtx/actions/runs/7207849258

otherwise provide a network dump.

**Comment by aler9** [comment]
assumed solved since no feedback was received.
