### ISSUE TITLE
[BUG] Path fallback no longer works since commit eb97502

### ISSUE THREAD

**Issue by hiruna** [bluenviron/mediamtx#2606]
## Which version are you using?

v0.23.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Migration to v1.2.1 from v1.0.0 failed due to the error `ERR: 'fallback' can only be used when source is 'publisher'`
Source is RTSP, fallback was working in v0.23.2 and earlier (as per docs):

![image](https://github.com/bluenviron/mediamtx/assets/3973928/623879a0-682a-463a-b1d3-86604d38b115)

Root cause: https://github.com/bluenviron/mediamtx/blame/4b4d57f18ee7fe88b5c0c7de6570edd6648d5ac0/internal/conf/path.go#L412

## Describe how to replicate the issue
Use v0.23.2 and define a path with a RTSP url as the source and also define a `fallback` RTSP path inside it. 

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, 'fallback' was never intended to work with static sources, however, since implementing this feature requires little effort, i think that it can be reintroduced and documented. This is fixed by #2706

**Comment by hiruna** [comment]
thanks @aler9! will test this out later
