### ISSUE TITLE
App crashing then publish to RTSP and receive from WebRTC

### ISSUE THREAD

**Issue by doesnmisclown** [bluenviron/mediamtx#2609]
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Server crashing after open webrtc stream 
Description

## Describe how to replicate the issue
1. Publish stream using ffmpeg (`ffmpeg -re -stream_loop -1 -i IMG_1116.MP4_20231023101338.mp4 -c copy -f rtsp rtsp://test:test@localhost:8554/test`)
2. Open /test path using webrtc
3. Get server crashed

## Did you attach the server logs?

https://paste.ee/p/PdHqw

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the crash, this is fixed by #2613
