### ISSUE TITLE
libcamera is 64-bit, you need the 64-bit server version

### ISSUE THREAD

**Issue by war4peace** [bluenviron/mediamtx#2647]
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Error when trying to serve rpi_camera footage via RTSP: libcamera is 64-bit, you need the 64-bit server version

## Describe how to replicate the issue

1. install mediamtx
2. configure mediamtx.yml with two cameras: one USB webcam and the rpi_camera. The USB camera streaming works perfectly. The rpi_camera streaming errors out with `ERR [path cam2] [RPI Camera source] libcamera is 64-bit, you need the 64-bit server version`

## Did you attach the server logs?

no need, there is single error line.

## Did you attach a network dump?

No need, this is a local error. Very similar to this: https://github.com/bluenviron/mediamtx/issues/1940

**Comment by aler9** [comment]
Hello, what part of the error message "you need the 64-bit server version" is not clear? Download the arm64 binary instead of the arm7 one.
