### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by robsumoza** [bluenviron/mediamtx#2659]
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When changing the configuration file nothing is happening, nor logs nor any change on the server.

## Describe how to replicate the issue

1. start the server - docker run --rm -it --network=host -v $PWD/mediamtx.yml:/mediamtx.yml bluenviron/mediamtx  
2.update config file
 
## Did you attach the server logs?

no

It does not shown any logs even in debug mode when the file is updated manually

no

**Comment by pkerney** [comment]
Possibly this?
https://github.com/bluenviron/mediamtx/discussions/672
