### ISSUE TITLE
Allow server wide disabling of recording Cleaner

### ISSUE THREAD

**Issue by svk23** [bluenviron/mediamtx#2670]
## Describe the feature

We are trying out the native recording functionality but we don't need the automatic deletion of recorded files. We have multiple streams that are recorded, each containing many (a couple of million) files. We found that the Cleaner takes up a lot of CPU on startup and periodically afterwards. It also seems to use a bit of memory compared to a server that has the same number of streams, but only a few recording segments. It would be nice to be able to disable the Cleaner, for example, with a global setting (e.g. `recordEnableDelete` that defaults to true). The option to disable automatic deletion by setting the time span to `0s` per stream doesn't seem to have the desired effect, since the Cleaner still runs and uses unnecessary resources.

**Comment by aler9** [comment]
Hello, i took a look at the record cleaning feature, and i found out that when `recordDeleteAfter` was set to zero, there was an infinite loop, that caused the CPU spikes. This is fixed by #2671

**Comment by svk23** [comment]
> Hello, i took a look at the record cleaning feature, and i found out that when `recordDeleteAfter` was set to zero, there was an infinite loop, that caused the CPU spike. This is fixed by #2671

Excellent, thank you very much. I just tried that fix (#2671) on the aforementioned server and I can confirm that this resolves our performance issues!
