### ISSUE TITLE
There is No audio of WebRTC in OBS 27.1.3 when pulling with browser source, but OBS 30.0

### ISSUE THREAD

**Issue by iesv** [bluenviron/mediamtx#2697]
## Which version are you using?

v1.3.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

There is No audio of WebRTC in OBS 27.1.3 when pulling with browser source, but OBS 30.0

## Describe how to replicate the issue

1. start the server
2. publish with chrome (H264+opus): https://192.168.10.200:8889/mystream/publish
3. read with OBS 27.1.3 of browser source: https://192.168.10.200:8889/mystream
4. enable control audio via OBS + unmute
5. audio does't work on OBS 27.1.3
6. but OBS 30.0 works.

## Did you attach the server logs?

2023/11/14 11:12:44 INF [WebRTC] [session 6bccf672] created by 192.168.10.200:52287
2023/11/14 11:12:45 INF [WebRTC] [session 6bccf672] peer connection established, local candidate: host/udp/172.28.96.1/8189, remote candidate: prflx/udp/192.168.10.200/51277
2023/11/14 11:12:45 INF [WebRTC] [session 6bccf672] is reading from path 'mystream', 2 tracks (Opus, H264)

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Hello, as you already mentioned in this issue, OBS 30.0 works without any problem. Furthermore, since audio is present when reading a stream from any browser with WebRTC, and since the browser source of OBS should mimic a web browser, the bug here lied entirely on the OBS side.
