### ISSUE TITLE
Add multiple audio track support in HLS

### ISSUE THREAD

**Issue by dams92210** [bluenviron/mediamtx#2728]
## Describe the feature

HLS is working great in mediamtx but it lacks support for multiple audio tracks when ingesting RTSP or SRT with multiple audio tracks.
As support for audiotracks increase in javascript HLS video players (videojs, flowplayer, radiant, theoplayer,...) would it be possible to add this feature?

**Comment by gargolito** [comment]
Is this feature coming soon-ish?

**Comment by dams92210** [comment]
@gargolito I use ingesting multiple audio tracks audio from SRT with success. But you cannot play it with HLS as only first audio track is recognised.
My trick is to use FFMPEG to remux the SRT feed from Mediamtx, one per audio tack and ingest back in mediamtx without reencoding.
Not optimal but this does work fine.

My request is to be able to have a common HLS js player presenting all audio tracks, as that's not possible with this trick. I need to hock the player and switch from one HLS feed to another.

**Comment by aler9** [comment]
This has been implemented and is in beta here: #3793
