### ISSUE TITLE
invalid rtmp version (22) when chaining two mediamtx servers and using tunneled rtmp transport

### ISSUE THREAD

**Issue by saket424** [bluenviron/mediamtx#2802]
## Which version are you using?

v1.4.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
I have two mediamtx proxys chained back to back. The first proxy pull the rtsp feed from the camera. The second mediamtx proxy pulls the rtmps feed from the first proxy over a tunneled boringproxy tcp connection (similar to cloudflared tunnels). I am able to pull and play the same feed just fine from the first proxy using mpv/ffplay but mediamtx complains that the rtmp version is invalid (22)

## Describe how to replicate the issue

1. start the mediamtx server on server1 with this path

 WQA:
    source: rtsp://username:password@192.168.12.62:554/cam/realmonitor?channel=1&subtype=0
    sourceOnDemand: yes

2. start the mediamtxserver on sever2 with this path

 WQA:
    source: rtmps://server1/WQA
    sourceOnDemand: yes

2023/12/12 00:25:19 INF [WebRTC] [session bbd68b72] created by 12.59.190.254:1354
2023/12/12 00:25:19 INF [path WQA225] [RTMP source] started on demand
2023/12/12 00:25:19 INF [RTMP] [conn 12.245.82.105:33608] opened
2023/12/12 00:25:19 INF [RTMP] [conn 12.245.82.105:33608] closed: invalid rtmp version (22)
2023/12/12 00:25:19 ERR [path WQA225] [RTMP source] read tcp 12.245.82.105:33608->12.245.82.105:1935: read: connection reset by peer
2023/12/12 00:25:24 INF [RTMP] [conn 12.245.82.105:50602] opened
2023/12/12 00:25:24 INF [RTMP] [conn 12.245.82.105:50602] closed: invalid rtmp version (22)
2023/12/12 00:25:24 ERR [path WQA225] [RTMP source] read tcp 12.245.82.105:50602->12.245.82.105:1935: read: connection reset by peer

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by saket424** [comment]
Instead of rtmps, if I use HLS, then it works (albeit with an 8 second latency)

  WQA:
    source: https://server1/WQA/index.m3u8
    sourceOnDemand: yes

**Comment by aler9** [comment]
Hello, that error is raised when you try to connect to a RTMP listener with RTMPS. Use `rtmp://server1/QWA` or enable RTMPS in the first server (`rtmpEncryption: strict`, then use `rtmps://server1:1936/WQA`).
