### ISSUE TITLE
Cannot set rpiCamera Custom AWB values

### ISSUE THREAD

**Issue by jdonley** [bluenviron/mediamtx#2858]
## Which version are you using?

v1.4.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I do not see a way to set a custom white balance value for raspberry pi cameras. The AwbMode config parameter can be set to AwbCustom, however, there is no way to set color gains. (I think the libcamera "controls" parameters might not be exposed).

## Describe how to replicate the issue

1. start the server with a Raspi Camera
2. Set the AWB mode to Custom
3. Notice that there is nowhere to set color gains

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
hello, i've added `rpiCameraAWBGains`. All parameters are intended to reflect libcamera-vid / rpicam-vid options.
