### ISSUE TITLE
query on Digest vrs Basic authentication comment in .yml file

### ISSUE THREAD

**Issue by RogerHardiman** [bluenviron/mediamtx#2883]
## Describe the feature

I want to check if the advice that Digest doesn't provide any additional security in the YML config file.
My understanding is Digest is much better than Basic due to hashing in a changing nonce value which prevents replay attacks and means you can only recover the plaintext password with brute force.
With Basic, you just pass the sting through a Base64 converter and there is your plaintext password. Very easy to do.

The YML config file has this text

_Authentication methods. Available are "basic" and "digest".
"digest" doesn't provide any additional security and is available for compatibility reasons only._

Does anyone else believe that this should tell you to use Digest as it offers better security over Basic
Or use Basic with HTTPS/TLS

Thanks
Roger Hardiman

**Comment by aler9** [comment]
Hello, the reason why digest is currently not better than basic is that the hashing algorithm behind digest, that is MD5, has been broken many years ago, thus sending a MD5-hashed password is the same as sending a plain password.

In order to prevent MITM attacks, you can either use RTSPS or a VPN.

**Comment by twvacek** [comment]
I think this overstates the vulnerability of md5. Md5 is vulnerable to collision attacks, in that it is easy to manipulate a malicious file to have a desired md5 checksum. However, recovering the preimage is still a brute-force attack, so unless the pre-image is a very short string, this will require serious time investment. It seems to me that for rtsp, digest authentication with a sufficiently long password offers about the same security as rtsps with udp rtp. I would be interested to hear counterexamples.

**Comment by twvacek** [comment]
If you're worried about a third party snooping on a stream you're watching (replay attack), you need both rtsps and srtp. If the worry is a MITM/sniffer being able gain credentials for your hardware, I think digest does defeat this, though not as strongly as rtsps/rtp.

**Comment by aler9** [comment]
> If you're worried about a third party snooping on a stream you're watching (replay attack), you need both rtsps and srtp

It's enough to use the TCP transport protocol and everything will be routed through RTSPS. SRTP is needed only when the transport protocol is UDP, and you're right, this is not implemented yet, but is planned, see https://github.com/bluenviron/gortsplib/issues/520

Regarding digest authentication, recently it has been improved to support the SHA-256 algorithm (see https://github.com/bluenviron/gortsplib/pull/524), but i can't enable it in the server since too few players support it.
