### ISSUE TITLE
publish to WebRTC and read from LL-HLS still has mono opus audio

### ISSUE THREAD

**Issue by null4n** [bluenviron/mediamtx#2902]
- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Using lasted chrome to publish webcam and mic on http://localhost:8889/stream/publish
Video codec choose AV1 and audio is Opus, uncheck "optimize for voice"
When I read read from ffmpeg using HLS, it shows audio is mono.
Using default .yml config file
in ffprobe
```Stream #0:1: Audio: opus (Opus / 0x7375704F), 48000 Hz, mono, fltp, 0 kb/s (default)```

## Describe how to replicate the issue

1. start the server
2. publish with chrome
3. read with ffprobe http://localhost:8888/stream/index.m3u8

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by zapf2000** [comment]
It is also possible to stream to the server with vdo.ninja. There you have a lot more parameters you can choose from. 
https://vdo.ninja/whip

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed with #3263
