### ISSUE TITLE
When plugin multiple usb casmeras only one streams RTSP

### ISSUE THREAD

**Issue by titusito** [bluenviron/mediamtx#2946]
## Which version are you using?

v1.5.0
## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have a raspberry pi with 3 cameras, one rpi camera on the spi port and two identical usb cameras, for some reason only one of the usb cameras works and the other one just does not transmit, the first camera on the usb port list (1.1 vs 1.2 or 1.2 vs 1.4) is the one that works, the  one after does not.

## Describe how to replicate the issue

1. start the server
2. publish with ...

  noir:
    source: rpiCamera
    rpiCameraWidth: 1080
    rpiCameraHeight: 720
  left_hd:
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video1 -s:v 1080x720 -r 30 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://127.0.0.1:8554/left_hd
    runOnInitRestart: yes
  right_hd:
    runOnInit: ffmpeg -pix_fmt yuv420p -i /dev/video3 -s:v 1080x720 -r 30 -c:v h264 -preset ultrafast -tune zerolatency -f rtsp rtsp://127.0.0.1:8554/right_hd
    runOnInitRestart: yes

3. read with ...

rtsp://server.ip:8554/right_hd

## Did you attach the server logs?

 no

## Did you attach a network dump?

 no

**Comment by titusito** [comment]
ok, I can see that if I try to access both cameras with ffmpeg, I have the same issue, the first that is initialized disallows the other one from capturing images.

**Comment by aler9** [comment]
Hello, your configuration seems right to me, but if you're having trouble accessing both USB cameras with FFmpeg, without involving the server, then the problem is somewhere else.

Maybe you can try to decode them both at the same time, without performing any encoding:

```
ffmpeg -pix_fmt yuv420p -i /dev/video1 -s:v 1080x720 -r 30 -f null -
ffmpeg -pix_fmt yuv420p -i /dev/video3 -s:v 1080x720 -r 30 -f null -
```

If these commands don't work, then the problem lies in the camera driver.
If these commands work, then the problem lies in the H264 encoder, that probably requires too much CPU for your Raspberry.
