### ISSUE TITLE
SRT metrics

### ISSUE THREAD

**Issue by nerdbaggy** [bluenviron/mediamtx#2950]
If I start working on a merge request to get SRT metrics into the metrics endpoint would you accept the merge? 

https://github.com/datarhei/gosrt/blob/739ea9cf91e6e105f630675118a8ab593d29ee2f/statistics.go

**Comment by chinbhat** [comment]
This could be very helpful

**Comment by aler9** [comment]
Hello, yes, we can expose SRT-specific metrics through both metrics server and API. This is already implemented with WebRTC. Send a patch and it will be considered.

**Comment by nerdbaggy** [comment]
Added in 1.6.0 https://github.com/bluenviron/mediamtx/releases/tag/v1.6.0
