### ISSUE TITLE
Compile Source error (gohlslib)

### ISSUE THREAD

**Issue by SniffRx** [bluenviron/mediamtx#2961]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

module requires 1.19 (but in readme.md go version 1.21+)
![image](https://github.com/bluenviron/mediamtx/assets/37187657/602c4e4f-dee0-4acc-ab57-2b8ed8a91cb4)

## Describe how to replicate the issue

1. git clone repo
2. run command: go build (see in readme.md)

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Make sure that you are using the minimum supported Go version (which is currently 1.21, always check the README for that).
