### ISSUE TITLE
Stream Aliases

### ISSUE THREAD

**Issue by Warr1024** [bluenviron/mediamtx#2966]
## Describe the feature

I would like to be able to have multiple paths access the exact same stream.

Currently, you can have multiple paths share the same configuration, but accessing both of them will duplicate the stream; for streams using e.g. runOnDemand to realtime reencode a source stream, this will incur additional processing load and/or split the budgeted CPU time between mulitple copies of the same stream.

Currently, it's possible to use sourceOnDemand to have additional aliases proxy an "original" path to ensure that encoding work is not duplicated, but this introduces an added latency to the stream caused by the proxying.

**Comment by aler9** [comment]
Hello, it's true that a single stream corresponds to a single path, but you can use queries to create multiple URLs for the same stream:

```
rtsp://localhost:8554/my_stream?q=my_variant_1
rtsp://localhost:8554/my_stream?q=my_variant_2
```

Queries are also sent to the external authentication server (if you have any) so they can be used to track individual users or implement a custom authentication logic.

If you're using a HTTP-based protocol like HLS or WebRTC, you can alternatively add a reverse proxy in front of the server and translate requests from different paths to a single path.

Adding this feature natively is not worth the effort.
