### ISSUE TITLE
DURATION param for `runOnRecordSegmentComplete` hook

### ISSUE THREAD

**Issue by neutralvibes** [bluenviron/mediamtx#2983]
## Describe the feature

Description

Duration parameter for `runOnRecordSegmentComplete` hook

Wondering if it is possible to provide some meta data params or at least segment `duration` passed to the `runOnRecordSegmentComplete` hook.

How would this help? Calling ffprobe to discern it, adds to processing time and, supplying it via the hook would make it relatively trivial to store the info in either a database or meta data file via a routine called by the hook.

Thanks for considering.

**Comment by t3therdev** [comment]
@aler9 anyway to bump this? what are your thoughts? it would definitely be helpful for us as well as we want to put this into a db on our side as @neutralvibes suggests.

**Comment by moenodedev** [comment]
This would also be useful when converting segments for HLS playback served by nginx
