### ISSUE TITLE
OBS Software x264 encoder tune zerolatancy 

### ISSUE THREAD

**Issue by Grimonja** [bluenviron/mediamtx#2985]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Trying to stream to mediamtx with OBS x264 tune: zerolatancy results in
> unable to decode AVCC: NALU count (22) exceeds maximum allowed (21)

## Describe how to replicate the issue

Streaming with following settings:
https://dl.dropboxusercontent.com/scl/fi//cmmd3mdoqb0x5ztesadd3/obs64_QdhsH1t9JS.png?rlkey=3k7ycz4fjvca3edxnk7t64dsu

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by Grimonja** [comment]
After some further testing this only happens if streaming at resolutions higher than 1080p
So streaming at 1440p will with tune: zerolatency will cause this

**Comment by isometriq** [comment]
There are constants in `bluenviron/mediacommon` to set arbitrary restrictions. In that case the H264 slicing limits.
https://github.com/bluenviron/mediacommon/blob/main/pkg/codecs/h264/h264.go

Is there a chance to allow configuration entries (mediamtx.yml) to override these?
Or are these constants for some reason (some spec or protocol limitation) ?

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by https://github.com/bluenviron/mediamtx/issues/2985
