### ISSUE TITLE
OBS Twitch VOD Track AMFParseError(41)

### ISSUE THREAD

**Issue by Grimonja** [bluenviron/mediamtx#2986]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Trying to stream to the server with OBS and Twitch VOD Track enabled results in:
> closed: AMFParseError(41)

## Describe how to replicate the issue

1. To even have an ability to send 2nd audio track with custom server in OBS you need to modify global.ini of OBS and add the following in the [General] options
EnableCustomServerVodTrack=true
2. Now select the Twitch VOD Track in encoding settings
3. Start Streaming

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the ability to send a 2nd audio track is not present into the RTMP specifications and is probably a custom feature introduced to improve integration with Twitch.
However, this could be a nice enhancement.

**Comment by krakow10** [comment]
You don't need to be able to ingest the twitch VOD audio RTMP protocol extension since you can stream with multiple audio tracks using SRT on the latest version of OBS, but being able to publish VOD audio to twitch from mediamtx would be useful.

**Comment by aler9** [comment]
Summing up:
* The SRT protocol natively supports streaming multiple audio tracks to Twitch - this is implemented by both MediaMTX and OBS
* The RTMP protocol requires a custom hack to stream multiple audio tracks to Twitch. MediaMTX currently doesn't support this hack

Since the RTMP hack would benefit only OBS and Twitch, and is not supported by anything else, there are not enough reason to implement it inside MediaMTX.

**Comment by krakow10** [comment]
> * The SRT protocol natively supports streaming multiple audio tracks to Twitch

This is not correct.  Twitch can only ingest RTMP, and optionally their VOD track protocol extension.  There is no other way to stream multiple audio tracks to Twitch to use their VOD audio feature.

**Comment by aler9** [comment]
I was testing the VOD track feature on OBS 31.0.0, and i discovered that it is now implemented through the Enhanced RTMP protocol. Therefore, supporting E-RTMP v2 means implementing this feature too. This is tracked in #3685
