### ISSUE TITLE
Decryption error using CONFKEY

### ISSUE THREAD

**Issue by sharmasulekh87** [bluenviron/mediamtx#2992]
## Which version are you using?

v1.2.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am running the server exe using the commands ./mediamtx. While using the encrypted configuration (as suggested) , I am getting decryption error.

## Describe how to replicate the issue

1. To use the encrypted configuration, I have set the environment variable MTX_CONFKEY in windows environment variable as shown below
![image](https://github.com/bluenviron/mediamtx/assets/78798753/58ef7756-8eea-4061-8bf3-5c93c0b52433)

2. Generated the encrypted configuration using the link provided 
https://go.dev/play/p/rX29jwObNe4
3. Using this configuration
[mediamtx.txt](https://github.com/bluenviron/mediamtx/files/14161225/mediamtx.txt)

5.  code to encrypt this configuration (from the link above)
[enc_code.txt](https://github.com/bluenviron/mediamtx/files/14161235/enc_code.txt)
6. Paste the encrypted configuration in yml
7. run the server , getting decryption error
![image](https://github.com/bluenviron/mediamtx/assets/78798753/087d83f3-b79b-45ee-8910-fa980f432e3a)

## Did you attach the server logs?

yes

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Hello, i tested your setup but in my case everything worked flawlessly. The code in enc_code.txt results in this encrypted configuration:

```
ALSSabWnmN3uX5jrGRMKd9Etp7GrjvnOW4YxhSpeNgovxiPrRse0NkcNFQNuut3GjR8tjUKE1QEaQ/I6kvFDJGvE/+s9DWBdIDKOZxEsAEKsQ6sUQf4xCZVOvP9txcSj1GkRpUvHH5pu9JO2dNh7Y+1Vv5+EfHwoEF28UdfKr8aBq3Oxa30XDSntWl9of6EfwNekrPvs0X79XCpunr6Fc51jMKWcCPBrqH2Vr71lwoa24EbRgDU5lzyy7mGj8IVnLY8UJpeUY2LhzQp3leHqpokaBiq1F9+IKkX4sJbfbTpro4Iy/4uSBHaZJYCux5NgfXaM5oJdgPeKhBO63WNswmygt7gU7Jkn0hGxh6ILRocyqamWU/aO8aMZk9hFkxufVnmtTBBPWIOgUk4WcJ99/LNdBRUoVYUhKODyNe8LdzEjPudd33P0wHO3VrivpURsN5YjOkPVJbANruF7S1ezist2gmBAcotQOBLdOWSc2iKT+oC30nx00MIWtQ3HdYFXlANJNkNDt+FFMTTqh0ut1Dd72uR55FPf6gZyEOJapcRqV33OR1vE9z4LtYxCoe7gyL/FPucivuBw7oq5F6cRXi79Zhgdb5Pk3XNyqsI631pLxZ5DgX33BkdNzqXQDytaxgyVjEaVALghvT7Eq0m2GdSrpSDOiXswOlT+Tni142sCZcfzvKJtcBHUkwb71YNWyF+RQHtgn0ZQ4E2siSclynx2FHa5Cqo7ccNMlISBysjweGvvM7gnb+QzwF9E8M0FDqiXJw6Y251eYq2xSAwkOGcbCfcFzsOEKp3axu1cKvaGelYXqCw6OJYW90WJkpLGOFYWF73f4gZLL471iWF1fcFNaWBVySCm8iX2vGiQp8tg4/LvuLp1WSqPCZLYlktvYtcONtXWcJ2yQfcSjlU1yA5dZnuyU5kPzt1BU5SFufg52aG1o5c0nSYzmBSLDqgC/9xSEFoJAAuG/AqfRKnpl1O+TMllOwnaiIKX8wM0ZjTD6bU24wsDAbqc/RLUs2bmOot3borHdN6lqcTAhVgav17+DH0TH9RtRjSe9eo9aDC0j+lQtyXyYq6xxDvRWASzddMiIID5+yuNZ1amL2DB7u+ynMflDBA7v7w19hU95k/4jOoa52k+XDJ8sF9vFYAQh0mxoVzszJDzByG6ekyQfg+gOi1+Q2pbAOzAKcmkYMCljZr7+uH4tuiKq0oLHxEvczMogs2D7xA1D2CutmF9wLQwEYO2FTt2ZtOT10k9kLFiT/0tEh5or8VJP7C0BDwm46D/4lWslTXITUO00mPI+z/ADf2NJ7O/Xh9cF14t9nUx3Fs9Cd5Zpv0s/fW9o3wlIhPrhJFbkp4ZgP1hkvKohIv2seVyeXsmGi3cHQohaiJOQUtKuzdlF9n9JgyXSAEC9hZB8DYEV+4gAsFV8E2xvhGHvvkZlea7fQSDNbThSTxc4Xur62ARXMYpIoUNYmXX58qmGydbnybgMHkMIxiCqrA1hkUkwoG2Wbsr6cOqoZnNyNTB1U2Izo89IlXnGHqKiQLOa6CVgdXF+W82DygDeh8PwP+1r91nRZ9Kv8JpCma3SvbH6kS76zltSXbiTGOt1+iCayrBVKFS2zkZYUh15JxPCrcKH2nEiNoxe4WtWat2I0G3lWVy0Npm7tlLoW7mDnl2tqQzHn+igAEELObrNUIEbFN/yPm5xRkcmamn3dYnT33slPWgJRnIgk8rRTbPt7qbu8tzLqvhqLD8xDQhL/7p/j4Gdy8j5A6P/jhYZQ+PsqhA0HjgxncHcMLf/rRtF2ny+H23wO7Jqu5GBN/QXNXF8kFT1+uPgxqAt4s0pl92lmg2apXFgkuOm9tu0UQs37o6A2UGVjKs96D4aaIy0imqwPvwE5rRmGWF/HjA/Rv8UsZ7pTnHQtoYVY/G6E/Y
```

I wrote it in `mediamtx.yml`, replacing existing content.

Then i opened the Windows terminal and set the `MTX_CONFKEY` variable:

```
C:\Users\xxx\Downloads\mediamtx> set MTX_CONFKEY=testing123
```

Then, in the same terminal, i started the server:

```
C:\Users\xxx\Downloads\mediamtx> mediamtx.exe
2024/04/20 11:51:32 INF MediaMTX v0.0.0
2024/04/20 11:51:32 INF configuration loaded from /home/ale/dev/mediamtx/mediamtx.yml
2024/04/20 11:51:32 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2024/04/20 11:51:32 INF [RTMP] listener opened on :1935
2024/04/20 11:51:32 INF [HLS] listener opened on :8888
2024/04/20 11:51:32 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2024/04/20 11:51:32 INF [SRT] listener opened on :8890 (UDP)
```

Make sure that the `MTX_CONFKEY` variable is set correctly. You can list environment variables and their content by using the `set` command.
