### ISSUE TITLE
RTSP|av_interleaved_write_frame(): Broken pipe

### ISSUE THREAD

**Issue by edisionnano** [bluenviron/mediamtx#2994]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have a jellyfin server and I decided to create channels from my movie folders. I have setup 37 channels, 8 of them crash with

```
av_interleaved_write_frame(): Broken pipe
Error writing trailer of rtsp://127.0.0.1:8554/movies5: Broken pipe
```
Could be hours later or minutes later

## Describe how to replicate the issue

The command I'm using is
```
ffmpeg -hide_banner -loglevel error -re -f concat -safe 0 -i "$playlist" -c copy -f rtsp -rtsp_transport tcp "rtsp://127.0.0.1:8554/$channel_id" >> /root/.ffmpeg_log.txt 2>&1 &
```
The playlist is a concat playlist containg avi, mkv and mp4 files all with h264/mpeg4 video and aac/ac3 audio

MediaMTX, FFMpeg and the script run as root

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the information you posted don't provide any clue about where the error is, or whether there is any error in the server. Please reopen the issue and include a way to replicate the issue and full server logs as explicitly indicated in the issue instructions.
