### ISSUE TITLE
now NACK support for udp packet lose？

### ISSUE THREAD

**Issue by wangjintianya** [bluenviron/mediamtx#2996]
## Describe the feature

[Description](https://github.com/bluenviron/mediamtx/issues/1)

now NACK support for udp packet lose？If supported, how to config?

**Comment by aler9** [comment]
Hello,
NACKs in WebRTC are implemented and fully working.
NACKs in RTSP are not not implemented since no client supports them.

**Comment by wangjintianya** [comment]
> Hello, NACKs in WebRTC are implemented and fully working. NACKs in RTSP are not not implemented since no client supports them.
Our own client supports nack, can the server support nack?
