### ISSUE TITLE
#3008 breaks windows build

### ISSUE THREAD

**Issue by Grimonja** [bluenviron/mediamtx#3010]
## Which version are you using?

latest-9eb97ad3a0e1bf3e6b5f4db461c2934f0b17edf3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Build on Windows fails with invalid control character in URL when downloading hls.js during go generate. 

`2024/02/12 13:40:44 downloading hls.js...
2024/02/12 13:40:44 ERR: parse "https://cdn.jsdelivr.net/npm/hls.js@v1.5.4\r/dist/hls.min.js": net/url: invalid control character in URL
exit status 1
internal\servers\hls\http_server.go:26: running "go": exit status 1`

There is a rogue `\r` inserted in the URL due to carriage return differences between Linux and Windows.

Fix that would work for both Windows and Linux is to remove carriage return from the VERSION file and not truncating the last character in the download process

## Describe how to replicate the issue

Try to build on Windows. 

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #3011
