### ISSUE TITLE
rtsp read says invalid bits

### ISSUE THREAD

**Issue by pankajsaini1987** [bluenviron/mediamtx#3023]
## Which version are you using?

v1.5.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- **[yes ] Windows amd64 standard**
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

after running the server it says invalid bit, but if i am playing that rtsp in vlc or ffmpeg it plays smoothly

## Describe how to replicate the issue

1. start the server
2. publish with rtsp
3. read with rtsp

## Did you attach the server logs?

yes 

## Did you attach a network dump?
no
[mediamtx.log](https://github.com/bluenviron/mediamtx/files/14292165/mediamtx.log)

**Comment by aler9** [comment]
Hello, this can be fixed in a very short time, but can you write the name of the camera or server that is generating the stream?

**Comment by aler9** [comment]
closed since author did not provide feedback.
