### ISSUE TITLE
WHEP AV1 not playing on Android Chrome

### ISSUE THREAD

**Issue by zapf2000** [bluenviron/mediamtx#3050]
## Which version are you using?

v1.5.1

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

WHEP playback on Android Chrome doesn't work. But it plays LL-HLS AV1 without problems.
When I try broadcast box, it plays AV1 WHEP.
On Windows and Linux it all works fine, only Android fails.
I set up a temporary teststream on https://media.zapf2000.de:8889/test (mediamtx WHEP player)
Works on Win/Lin, but not on Android. If you use the vdo.ninja player it works on all plattforms.
https://vdo.ninja/alpha/?&hidemenu&whepplay=https%3A%2F%2Fmedia.zapf2000.de%3A8889%2Ftest%2Fwhep&stereo=2&whepwait=0
Be careful, it's a 4K UHD 50fps teststream with approx. 10MBit/s.

## Describe how to replicate the issue

1. start the server
2. publish with OBS WHIP AV1 on Windows
3. read with Chrome on Android

## Did you attach the server logs?

2024/02/20 21:08:15 INF [WebRTC] [session 970091e4] created by [2003:e3:7f4c:a600:79c6:1900:d21c:4022]:47818
2024/02/20 21:08:15 INF [WebRTC] [session 970091e4] closed: unable to start track, codec is not supported by remote

yes 

## Did you attach a network dump?

no

**Comment by bronze1man** [comment]
whep vp9 not work on ios 15.6 . 
But whip vp9 works on ios 15.6.

**Comment by aler9** [comment]
Hello, in my opinion this is cause by some sort of filtering that the server applies between the SDP of the WHIP publisher and the SDP that is sent to the WHEP reader. Please attack full server logs with `logLevel: debug`, as mentioned in the Issue instructions, since they contain both incoming and outgoing SDP.

**Comment by zapf2000** [comment]
I think this issue is obsolete. I'm using 1.9.3 now and it works without problems.
