### ISSUE TITLE
runOnDemand: for videowriter() 

### ISSUE THREAD

**Issue by Samjith888** [bluenviron/mediamtx#3066]
## Which version are you using?

v1.5.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [x] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Publishing to the server by using opencv videowirter(). I need to run the videowriter() for 10 mins in each 1 hour, hence the mediamtx server need not active when the publishing is not happening, should run only 1o mins in each hour. 
In the docs its mentioned that, how to publish on demand for ffmpge,gstreamer commands. But not for the opencv videowriter(). 

![image](https://github.com/bluenviron/mediamtx/assets/39676803/b157ca5e-a933-43ec-bea8-1260b7329d2b)

## Describe how to replicate the issue
```

from datetime import datetime
from time import sleep, time

import cv2
import numpy as np

fps = 15
width = 800
height = 600
colors = [
    (0, 0, 255),
    (255, 0, 0),
    (0, 255, 0),
]

out = cv2.VideoWriter('appsrc ! videoconvert' + \
    ' ! video/x-raw,format=I420' + \
    ' ! x264enc speed-preset=ultrafast bitrate=600 key-int-max=' + str(fps * 2) + \
    ' ! video/x-h264,profile=baseline' + \
    ' ! rtspclientsink location=rtsp://localhost:8554/mystream',
    cv2.CAP_GSTREAMER, 0, fps, (width, height), True)
if not out.isOpened():
    raise Exception("can't open video writer")

curcolor = 0
start = time()

while True:
    frame = np.zeros((height, width, 3), np.uint8)

    # create a rectangle
    color = colors[curcolor]
    curcolor += 1
    curcolor %= len(colors)
    for y in range(0, int(frame.shape[0] / 2)):
        for x in range(0, int(frame.shape[1] / 2)):
            frame[y][x] = color

    out.write(frame)
    print("%s frame written to the server" % datetime.now())

    now = time()
    diff = (1 / fps) - now - start
    if diff > 0:
        sleep(diff)
    start = now


```
## Did you attach the server logs?
no
## Did you attach a network dump?
 no

**Comment by aler9** [comment]
Hello, this is not a MediaMTX bug but a OpenCV question. If you search a little you will find that `cv2.VideoWriter` has a `release()` method that allows to close the writer:

https://stackoverflow.com/questions/17076091/release-videowriter-in-python-opencv
