### ISSUE TITLE
Playback Controls

### ISSUE THREAD

**Issue by mohankumar-dev-2002** [bluenviron/mediamtx#3067]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description 
The playback server is working but cannot control the video in vlc and browser(except firefox)
Discussion:-https://github.com/bluenviron/mediamtx/discussions/3068#discussion-6263370
## Describe how to replicate the issue

1. start the server
2. publish with RTSP stream
3. I am publishing with ptz camera and started recording with default fs and enabled the playback server
4. started req for playback with this url http://localhost:9996/get?path=camera9&start=2024-02-24T17%3A50%3A00%2B05%3A30&duration=60
5. read with playback in vlc 
6. Playback is playing in the vlc without any controls it is playing like a live 

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by mohankumar-dev-2002** [comment]
And also I tried an nodejs server to serve the recorded files using "streams" it is working in vlc (seek forward or backward)

**Comment by aler9** [comment]
This is fixed by using the "standard MP4" format of the playback server, documented in the README: 

https://github.com/bluenviron/mediamtx?tab=readme-ov-file#playback-recorded-streams
