### ISSUE TITLE
paths: section in seperate dynamically reloaded YAML file

### ISSUE THREAD

**Issue by winkmichael** [bluenviron/mediamtx#3080]
## Describe the feature

Allow the paths: section of the main YAML configuration file to be dynamically generated from a separate YAML file. This separate file would be periodically refreshed, enabling updates to paths without requiring a server restart / reload.
I don't believe any other section of the configuration would benefit from including or breaking into sections other than the paths section at this time.

Thanks for your time and consideration

**Comment by aler9** [comment]
Hello, the "paths" and "pathDefaults" section of the current configuration file is already monitored for changes, and changes are applied immediately without requiring a server restart / reload. This is documented in the [README](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#configuration).
