### ISSUE TITLE
Golang compilation error with a go:embed instruction on 1.6.0

### ISSUE THREAD

**Issue by isometriq** [bluenviron/mediamtx#3097]
## Which version are you using?

v1.6.0

```
go version go1.21.0 darwin/amd64
```

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [X] macOS amd64 standard
- [X] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When attempting to run or build the project, there is an golang compilation error
```
internal/servers/hls/http_server.go:29:12: pattern hls.min.js: no matching files found
```
[//go:embed hls.min.js](https://github.com/bluenviron/mediamtx/blob/dec395cce8eef8fdc05db85c06148450f92641e4/internal/servers/hls/http_server.go#L29)

## Describe how to replicate the issue

```
go run main.go
```
or
```
go build
```

## Did you attach the server logs?

no (server does not run)

## Did you attach a network dump?

no (server does not run)

**Comment by aler9** [comment]
Please take a look at the "Compile from source" section of the README.
