### ISSUE TITLE
Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections, retrying in some seconds

### ISSUE THREAD

**Issue by miquelmassot** [bluenviron/mediamtx#3123]
## Which version are you using?

v1.5.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

After a disconnection and reconnection of a stream (SDP through ffmpeg), MediaMTX crashes and we see the error "Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections, retrying in some seconds" in the browser page.

## Describe how to replicate the issue

1. Start the server
2. Publish with SDP files over ffmpeg and check that it works. Stop the SDP streaming for 1h but leave MediaMTX on.
3. Re-enable the SDP streams and the webpage with the streams does not reconnect and displays the error "Failed to construct 'RTCPeerConnection': Cannot create so many PeerConnections, retrying in some seconds" and it does not recover.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

## Example snippet from mediamtx.yml

```
MY-CAMERA:
    runOnInit: ffmpeg -protocol_whitelist "file,http,https,tcp,tls,rtp,udp" -i /opt/contoso/config_files/sdp_files/MY-CAMERA.sdp -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
```

Contents of the `MY-CAMERA.sdp` file:

```
v=0
c=IN IP4 239.255.80.4
m=video 50040 RTP/AVP 96 
a=rtpmap:96 H264/90000
```

**Comment by nihil-pro** [comment]
This is not a mediamtx error. You did not close old connection before opening new one. 
go to chrome://webrtc-internals and you’ll see all connections that you were created. 
After closing connection, you need to nullify it, and GC will be able to remove it. 
const pc = new RTCPeerConnection()
//…. close way
pc.close()
pc = null

**Comment by aler9** [comment]
Hello, the stream content and how it is sent to the server has nothing to do with this bug, that lies inside the WebRTC read page. This page has been rewritten multiple times since this topic has been opened, so i'm almost certain that this bug is gone.
If this is not the case, feel free to reply to this bug report or open a new one, providing also the name and version of the browser that you are using to read the stream.
