### ISSUE TITLE
hlsDirectory parameter - Hls directory doesn't created per stream in 1.6.0 when it worked properly in 1.5.1

### ISSUE THREAD

**Issue by EvgIL74** [bluenviron/mediamtx#3135]
## Which version are you using?

v1.6.0
v1.5.1

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
Ask to create ts files on disk instead of in memory by add directory in hlsDirectory  in yml file.
The server doesn't create directory path and not created ts files on disk.
It was properly in 1.5.1 and stopped work in 1.6.0.

## Describe how to replicate the issue

Ask to create ts files on disk instead of in memory by add directory in hlsDirectory  in yml file.
The server doesn't create directory path and not created ts files on disk.

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by tschettervictor** [comment]
Same issue here.

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #3150 and #3151
