### ISSUE TITLE
HLS streaming playback speed is 1.5x for mobile devices with no option to change

### ISSUE THREAD

**Issue by tschettervictor** [bluenviron/mediamtx#3155]
## Which version are you using?

v1.6.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (please describe) FreeBSD 13.2

## Describe the issue

When viewing a stream via HLS from mobile devices (ios ipados safari,brave,chrome etc) the playback speed will default to 1.5x and cannot be changed for it seems the first 10 seconds of most recent playback. If you skip back 10 seconds, or pause until there is a 10 second gap, the speed will go back to 1x also without the ability to change.
The HLS stream works fine for desktop using brave browser. Other browsers are not tested

This is with all three variants of HLS, and storing in RAM or directory.

## Describe how to replicate the issue

1. start the server
2. publish with rtmp any stream with user that has publish permissions
3. read with hls from mobile devices (ios, android not tested) ios version 17.3.1 and 17.4

## Did you attach the server logs?

no.
There are no related logs. Logs all show properly...stream started and is muxing to HLS

## Did you attach a network dump?

no

**Comment by tschettervictor** [comment]
Just tested with the latest docker image. Same issue.

**Comment by tschettervictor** [comment]
@aler9 Do you think this is an issue with the HLS player, or the devices themselves. I read that you can set “playbackrate” for HLS but haven’t been able to solve the issue yet.

**Comment by tschettervictor** [comment]
Any thoughts on this. Its fairly important to get this functioning properly, otherwise I’ll look elsewhere for a streaming solution.

**Comment by jwetzell** [comment]
This is reproducible still in 1.8.3. I can reproduce it in some very specific scenarios (navigate away and back quickly or start/stopping the player quickly) on both mobile and desktop. This has to do with this line [here](https://github.com/bluenviron/mediamtx/blob/afec0cd86cd07375284cdac9c330743e2d58f667/internal/servers/hls/index.html#L72) as I can tweak the playback speed that the HLS player bumps to by changing that line.

**Comment by therysin** [comment]
> This is reproducible still in 1.8.3. I can reproduce it in some very specific scenarios (navigate away and back quickly or start/stopping the player quickly) on both mobile and desktop. This has to do with this line [here](https://github.com/bluenviron/mediamtx/blob/afec0cd86cd07375284cdac9c330743e2d58f667/internal/servers/hls/index.html#L72) as I can tweak the playback speed that the HLS player bumps to by changing that line.

A heads up that I built an image based on that fix, and it works great. I don't have the skill to maintain, so here's a fix until this is incorporated in the actual images. 

https://hub.docker.com/r/therysin/mediamtx/

**Comment by tschettervictor** [comment]
I am still experiencing this issue with the current build version.
