### ISSUE TITLE
RTP packet is too big to be read with UDP

### ISSUE THREAD

**Issue by Tabarane** [bluenviron/mediamtx#3158]
## Which version are you using?

v16.0.0

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [X] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [X] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Trying to get video feed from camera with proxy and get the error
```
2022/09/15 23:06:42 WAR [path glass] [rtsp source] RTP packet is too big to be read with UDP
2022/09/15 23:06:42 WAR [path glass] [rtsp source] RTP packet is too big to be read with UDP
2022/09/15 23:06:42 WAR [path glass] [rtsp source] 66 RTP packet(s) lost
2022/09/15 23:06:42 WAR [path glass] [rtsp source] RTP packet is too big to be read with UDP
```

## Describe how to replicate the issue

<!--
simple as added the stream and try to view it, when i try to use TCP method, stream work for 5-10 second then gets
```
ERR TCP TIMEOUT
~~~
-->

1. start the server
2. publish with ...
3. read with vlc

## Did you attach the server logs?

<!--
Server logs are sometimes useful to identify the issue.
If you think this is the case, set the parameter 'logLevel' to 'debug' and attach the server logs.
-->

no

## Did you attach a network dump?

no

**Comment by yelodevopsi** [comment]
Just a longshot since I just read this thread.. 

* Check with Wireshark and with the filter `udp`. What are the sized of the of the incoming RTSP packages? Over MTU? (1500)
* Check MTU value in router
* What are the package size from the RTSP-source? Check the camera-configuration/web-interface.

**Comment by aler9** [comment]
Hello, as clearly mentioned in the error, the server explicitly discards RTP packets that are bigger than the UDP MTU. These packets are sent fragmented, therefore in a really inefficient way, and furthermore it's impossible to detect whether they have been truncated by any NAT / gateway in between. Decrease the MTU of your camera in order for it to be less than the UDP MTU, otherwise switch to TCP.
