### ISSUE TITLE
webrtc 

### ISSUE THREAD

**Issue by lonely-z** [bluenviron/mediamtx#3166]
## Which version are you using?

v1.4.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue
Armv7 version usage environment: rv1126 pushes RTSP streams to mediamtx, allowing mediamtx to forward webrtc. After power is supplied, the webrtc stream keeps disconnecting and reconnecting，which lasts for several seconds, and then disconnects for about 30 seconds

1. start the server
2. publish with RTSP
3. read with WEBRTC

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by einaraglen** [comment]
Hi, having the same behavior on my part, publishing a test stream with RTSP, i can read it from the server with RTSP using VLC, but i if i open brower to view stream via WebRTC it keeps dropping and retrying, and all the server is spitting out is

`
2024/04/25 11:40:11 DEB [WebRTC] [conn MY-IP] [s->c] HTTP/1.1 204 No Content
`

i am streaming to /mystream, can view on this path via RTSP but not on the same with WebRTC

**Comment by aler9** [comment]
Without server logs  or network dumps it's impossible to understand what the problem is. If you still have problems, reopen the issue and attach full server logs as instructed to.

**Comment by richervip** [comment]
I have the same issue.
I push stream by rtsp and read stream from 8888 is ok.
This is dubug log from mediamtx.
2024/09/04 22:28:36 INF [WebRTC] [session 65a05feb] created by _my_server_IP_:48367
2024/09/04 22:28:36 DEB [path verkadacam01] created
2024/09/04 22:28:36 INF [WebRTC] [session 65a05feb] closed: no one is publishing to path 'verkadacam01'
2024/09/04 22:28:36 DEB [path verkadacam01] destroyed: not in use
2024/09/04 22:28:36 DEB [WebRTC] [conn _my_server_IP_:48367] [s->c] HTTP/1.1 404 Not Found
