### ISSUE TITLE
Unable to stream with RTMP and codec H265/VP9/AV1

### ISSUE THREAD

**Issue by pedroSG94** [bluenviron/mediamtx#3188]
## Which version are you using?

v1.6.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Due to new AMF0 parser in RTMP . AMF0 Strict Array type is not supported producing this error:
```
closed: unsupported marker 0x0a
```
AMF0 documentation to implement Strict Array:
https://rtmp.veriskope.com/pdf/amf0-file-format-specification.pdf

According with RTMP enhanced in connect command you need include a property called fourCcList which is a Strict Array:
https://veovera.org/docs/enhanced/enhanced-rtmp-v1#extending-netconnection-connect-command

This was working on version 1.5.1 so I think the error is in the new AMF0 parser.
Also, I checked that if you send AMF0 types not implemented in [this method](https://github.com/bluenviron/mediamtx/blob/main/internal/protocols/rtmp/amf0/unmarshal.go#L49), the connection fail. I think that the server should at least ignore not implemented types instead of refuse connection if it is a valid type.

I did a PR to fix this error:
https://github.com/bluenviron/mediamtx/pull/3189

## Describe how to replicate the issue

1. Download the Android apk attached (this apk is a compilation of [this project](https://github.com/pedroSG94/RootEncoder) modified to work with H265 codec as default in rotation example)

[app-debug.zip](https://github.com/bluenviron/mediamtx/files/14859243/app-debug.zip)
...
2. Unzip and install the apk in an Android device
3. Open app
4. Open Rotation (include filters) example
5. Type a rtmp url in the textbox
6. Press center button to start stream
7. The connection fail and the app try reconnect.

## Did you attach the server logs?

Yes

## Did you attach a network dump?

No

**Comment by aler9** [comment]
fixed by #3189
