### ISSUE TITLE
record mpegts bad files

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#3206]
## Which version are you using?

v1.1.0 and later
## Which operating system are you using?

- [X] Linux amd64 standard
- [X] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [X] Other (LXC)

## Describe the issue

An incorrect file is generated when recording in mpegts format([record](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#record-streams-to-disk) server function). There is no way to play it <s>in chrome/safari/</s> quick time player.
However, if you take a file in mpegts format generated by the hls server, everything plays perfectly.

## Describe how to replicate the issue

1. enable the HLS server in the configuration file and allow it to save segments in mpegts format to a folder.
2. enable saving of published streams in the configuration file.
3. start the server
4. publish with rtsp any stream
5. read with HLS the published stream
6. <s>copy files generated by the hls server and make playlist1 in m3u8 format
7. copy files generated by the server's built-in recording function and make playlist2 in m3u8 format
8. play received playlists via chrome/safari</s>
9. copy files generated by the hls server and play mpegts files in quick time player
10. copy files generated by the server's built-in recording function and play mpegts files in quick time player

## Did you attach the server logs?

yes / **no**

## Did you attach a network dump?

yes / **no**
GOOD FILES GENERATED HLS SERVER [408608627_good_ts.tar.gz](https://github.com/bluenviron/mediamtx/files/14902036/408608627_good_ts.tar.gz)
BAD FILES GENERATED RECORD FUNCTION [408608627_bad_ts.tar.gz](https://github.com/bluenviron/mediamtx/files/14902037/408608627_bad_ts.tar.gz)

**Comment by pikachu937** [comment]
UPD.
I rechecked the playlist generation in my service and found an error.
I apologize for misleading you. 

However, one of the problems still remains: the files ts generated by the server's built-in recording function cannot be read by the native player(Quick Time Player) in iOS/MacOS.

**Comment by aler9** [comment]
Thanks for reporting the QuickTime compatibility issue with recording segments, this is fixed by https://github.com/bluenviron/mediacommon/pull/131

**Comment by moenodedev** [comment]
Could fix #3350 and #3313

**Comment by aler9** [comment]
@moenodedev absolutely yes, but I don't want to examine issues that do not follow rules (for instance reporting two problems at once or not attaching any useful info), otherwise I would go crazy.

**Comment by moenodedev** [comment]
Thanks for all your work. It's a game changer for my organization
