### ISSUE TITLE
Adjustable bitrate and fps on the fly

### ISSUE THREAD

**Issue by pankajsaini1987** [bluenviron/mediamtx#3234]
Adaptive Bitrate and FPS on the fly

## Describe the feature

Description
it will be good if you can provide Adaptive bitrate and fps without restarting the stream,
if i want to downgrade or upgrade the fps or bitrate to save hardware and resources, it will be really helpful.

**Comment by aler9** [comment]
Hello, unfortunately inside the server we cannot re-encode the streams natively, for both performance and legal reasons. If you want to create some low resolution streams for each incoming stream, you can use FFmpeg inside `runOnReady` as described in the README:

https://github.com/bluenviron/mediamtx?tab=readme-ov-file#remuxing-re-encoding-compression
