### ISSUE TITLE
Regarding the issue of video recording

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#3268]
## Which version are you using?

v1.5.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

I configured the recording through an API and found that even after I started recording, there was still no record file generated. I had to preview it before it could be generated. How can I achieve heating in the background recording without pulling the stream,Thanks

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by aler9** [comment]
This issue cannot be replicated without configuration, server logs and the sequence of API calls. Reopen the issue and provide such data.
