### ISSUE TITLE
Empty "query" if action="playback"

### ISSUE THREAD

**Issue by gurzhy** [bluenviron/mediamtx#3270]
## Which version are you using?

v1.7.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Hello.
We use "authMethod: http"
If action="playback" then "query" field come empty.
If action="read" everything is OK:

**"read":**
https://localhost:8889/proxied1/?token=15d2d2d9-4436-4a3b-ab46-5f904c4b859e
```
{
    "ip": "127.0.0.1", 
    "user": "", 
    "password": "", 
    "action": "read", 
    "path": "proxied1", 
    "id": null, 
    "query":  "token=15d2d2d9-4436-4a3b-ab46-5f904c4b859e"
}
```

**"playback":**
http://localhost:9996/list?path=proxied1&token=15d2d2d9-4436-4a3b-ab46-5f904c4b859e

```
{
    "ip": "127.0.0.1", 
    "user": "", 
    "password": "", 
    "action": "playback", 
    "path": "proxied1", 
    "id": null, 
    "query": ""
}
```

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
BTW this was fixed by #3253
