### ISSUE TITLE
fmp4 recordings don't play in Safari

### ISSUE THREAD

**Issue by moenodedev** [bluenviron/mediamtx#3313]
## Which version are you using?

v1.8.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. Enable recordings for a path
2. List recordings for a path with the `/list` endpoint
3. Try to display a recording from the `/get` endpoint

The video doesn't load or display in Safari
```html
<video controls>
  <source src="https://example.com:9996/get?path=outdoor&amp;start=2024-05-03T11%3A46%3A53.141439Z&amp;duration=337.247275"
    type="video/mp4" />
</video>
```

Adding the `format=mp4` query param also doesn't work
```html
<video controls>
  <source src="https://example.com:9996/get?path=outdoor&amp;start=2024-05-03T11%3A46%3A53.141439Z&amp;duration=337.247275&amp;format=mp4"
    type="video/mp4" />
</video>
```

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
you are url-encoding the entire path of the URL instead of url-encoding just the start date. This is the right URL:

```html
<video controls>
  <source src="https://example.com:9996/get?path=outdoor&start=2024-01-14T16%3A33%3A17%2B00%3A00&duration=337.247275"
    type="video/mp4" />
</video>
```

for more informations and examples, take a look at the [README](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#playback-recorded-streams).

**Comment by moenodedev** [comment]
How is `start` supposed to be encoded? `/list` shows `2024-05-06T11:32:34.935427Z` but your example has
```
2024-01-14T16:33:17     +00:00
2024-01-14T16%3A33%3A17 %2B00%3A00
```

```
https://mediamtx.ngrok.io:9996/list?path=outdoor
[{"start":"2024-05-06T11:32:34.935427Z","duration":2375.209548}]
```

**Comment by moenodedev** [comment]
With Firefox, if I open the URL directly or as the src of a <video/> element the video loads.

https://mediamtx.ngrok.io:9996/get?path=619&start=2024-05-06T11%3A32%3A34.935427Z&duration=10.0&format=mp4

But Safari says
Failed to load resource: Plug-in handled load

**Comment by moenodedev** [comment]
With Firefox, if I open the URL directly or as the src of a <video/> element the video loads.

https://mediamtx.ngrok.io:9996/get?path=outdoor&start=2024-05-06T11%3A32%3A34.935427Z&duration=10.0&format=mp4

But Safari says
Failed to load resource: Plug-in handled load

**Comment by moenodedev** [comment]
`/list` returns `2024-05-06T11:32:34.935427Z` but your example has `+00:00` at the end without the microseconds.  Both `Z` and `+00:00` work in Firefox.

```
https://mediamtx.ngrok.io:9996/list?path=outdoor
[{"start":"2024-05-06T11:32:34.935427Z","duration":2375.209548}]
```

```
2024-05-06T11:32:34.935427Z
2024-05-06T11%3A32%3A34.935427%2B00%3A00
```

**Comment by volk234** [comment]
Same problem. IPhone can't play recorded video. Tried with Safari and Chrome.
Android and windows works fine with same url.
