### ISSUE TITLE
JWT authentication does not work with auth0 provider

### ISSUE THREAD

**Issue by miguelaeh** [bluenviron/mediamtx#3324]
## Which version are you using?

v1.8.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

Using the JWT authentication method does not seem to be able to authorize users when the token comes from auth0.

## Describe how to replicate the issue

1. start the server with `authMethod: jwt` and `authJWTJWKS: https://your-auth0-domain/.well-known/jwks.json`
2. try to publish a stream using an `accessToken` from auth0
3. see the 401 error

## Did you attach the server logs?

There are no hints on the logs, even with debug enabled.

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, requirements on the JWT format are listed in the README. Further assessment on the issue are not possible since  you didn't attach a sample JWT or server logs. If you still have problems, create a bug and attach the JWT and server logs.

**Comment by miguelaeh** [comment]
@aler9  As I mentioned in the original issue, no messages appear on the logs related to authentication, even using the debug mode.
With the steps I provided it is easily replicated. The requirements listed on the README are either wrong or something is missing for the auth0 provider.
