### ISSUE TITLE
Allow reading Multichannel Opus streams with WebRTC

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#3371]
## Describe the feature

Follows #3355

**Comment by aler9** [comment]
Hello @ditogam, for your tests did you use the latest release (v1.8.2) or a nightly binary that includes #3355?

Anyway, streaming multichannel Opus with WebRTC is still a work-in-progress and #3355 is yet to be fully tested and merged, in particular, the error you reported

> 2024/05/20 18:03:49 WAR [SRT] [conn 127.0.0.1:41095] frame is too big

is not covered by the patch yet and is due to an excessive size of the audio packets. I'll see what i can do about it before merging the patch.

**Comment by ditogam** [comment]
Hi @aler9 . 
I tested against PR [3375](https://github.com/bluenviron/mediamtx/pull/3375), `feature/webrtc-multiopus` branch

about `frame is too big` I just included in logs

**Comment by ditogam** [comment]
This is fantastic news, thank you so much. I tested, everything works perfectly. I run server from this branch and I can hear all the channels

**Comment by ditogam** [comment]
Even 7.1 works perfectly

**Comment by ditogam** [comment]
I tested locally and it worked perfectly on 5.1 and 7.1 (Downloaded from same source `AAC 7.1.mp4` [Google Drive folder](https://drive.google.com/drive/folders/1JxmeedtAtgmoafXv9rroiDOS2vEX7N4b))
Then I deployed it on external server with public IP.
5.1 worked as expected, but on 7.1 with WebRTC got `deadline exceeded while waiting connection`, even thought I put `webrtcAdditionalHosts`.
here is debug log (Masked IPs)
[debug.txt](https://github.com/bluenviron/mediamtx/files/15445413/debug.txt)

Publish command 
`ffmpeg -re -stream_loop 100 -i "/home/dito/Downloads/AAC 7.1.mp4" -c:v libx264  -bf 0  -c:a libopus -b:a 256k  -f mpegts "srt://35.83.58.196:8890?streamid=publish:mystream"`

output 
```
 Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    encoder         : Lavf60.16.100
  Stream #0:0(und): Audio: opus, 48000 Hz, 7.1, flt, 256 kb/s (default)
    Metadata:
      creation_time   : 2013-05-09T11:31:26.000000Z
      handler_name    : soun
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 libopus

```

srt reciever 

`ffplay  "srt://35.83.58.196:8890?streamid=read:mystream"`

output 
```
Input #0, mpegts, from 'srt://35.83.58.196:8890?streamid=read:mystream':
  Duration: N/A, start: 58.325322, bitrate: N/A
  Program 1 
  Stream #0:0[0x100]: Audio: opus (Opus / 0x7375704F), 48000 Hz, 7.1, fltp

```

works.


Then I downloaded [dolby-demo-trailers-hd](https://www.demolandia.net/cinema/dolby-demo-trailers-hd/page-8.html) 
And it worked with WebRTC as well
`ffmpeg -re -stream_loop 100 -i "/home/dito/Downloads/7.1.mkv" -c:v libx264  -bf 0  -c:a libopus -b:a 256k  -f mpegts "srt://35.83.58.196:8890?streamid=publish:mystream"`

output
 ```
 Stream #0:0(eng): Video: h264, yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 90k tbn (default)
    Metadata:
      encoder         : Lavc60.31.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: opus, 48000 Hz, 7.1, flt, 256 kb/s (default)
    Metadata:
      encoder         : Lavc60.31.102 libopus

```

So it seams working
Thank you very much

**Comment by ditogam** [comment]
I tested locally and it worked perfectly on 5.1 and 7.1 (Downloaded from same source `AAC 7.1.mp4` [Google Drive folder](https://drive.google.com/drive/folders/1JxmeedtAtgmoafXv9rroiDOS2vEX7N4b))
Then I deployed it on external server with public IP.
5.1 worked as expected, but on 7.1 with WebRTC got `deadline exceeded while waiting connection`, even thought I put `webrtcAdditionalHosts`.
here is debug log (Masked IPs)
[debug.txt](https://github.com/bluenviron/mediamtx/files/15445413/debug.txt)

Publish command 
`ffmpeg -re -stream_loop 100 -i "/home/dito/Downloads/AAC 7.1.mp4" -c:v libx264  -bf 0  -c:a libopus -b:a 256k  -f mpegts "srt://MEDIAMTX_PUBLIC_IP:8890?streamid=publish:mystream"`

output 
```
 Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    encoder         : Lavf60.16.100
  Stream #0:0(und): Audio: opus, 48000 Hz, 7.1, flt, 256 kb/s (default)
    Metadata:
      creation_time   : 2013-05-09T11:31:26.000000Z
      handler_name    : soun
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 libopus

```

srt reciever 

`ffplay  "srt://MEDIAMTX_PUBLIC_IP:8890?streamid=read:mystream"`

output 
```
Input #0, mpegts, from 'srt://MEDIAMTX_PUBLIC_IP:8890?streamid=read:mystream':
  Duration: N/A, start: 58.325322, bitrate: N/A
  Program 1 
  Stream #0:0[0x100]: Audio: opus (Opus / 0x7375704F), 48000 Hz, 7.1, fltp

```

works.


Then I downloaded [dolby-demo-trailers-hd](https://www.demolandia.net/cinema/dolby-demo-trailers-hd/page-8.html) 
And it worked with WebRTC as well
`ffmpeg -re -stream_loop 100 -i "/home/dito/Downloads/7.1.mkv" -c:v libx264  -bf 0  -c:a libopus -b:a 256k  -f mpegts "srt://MEDIAMTX_PUBLIC_IP:8890?streamid=publish:mystream"`

output
 ```
 Stream #0:0(eng): Video: h264, yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 90k tbn (default)
    Metadata:
      encoder         : Lavc60.31.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: opus, 48000 Hz, 7.1, flt, 256 kb/s (default)
    Metadata:
      encoder         : Lavc60.31.102 libopus

```

So it seams working
Thank you very much
