### ISSUE TITLE
Support streaming H265 over WebRTC

### ISSUE THREAD

**Issue by bouk** [bluenviron/mediamtx#3386]
## Describe the feature

Currently trying to stream H265 over WebRTC leads to `the stream doesn't contain any supported codec, which are currently AV1, VP9, VP8, H264, Opus, G722, G711`. `go2rtc` [supports streaming H265](https://github.com/AlexxIT/Blog/issues/5) over WebRTC for Safari (with some caveats) and it would be cool if mediamtx also supported it!

**Comment by aler9** [comment]
This won't be done as it would benefit less than 5% of users and cause the remaining 95% to open issues in order to find out why H265 is advertised as supported but they cannot use it.

My advice is to switch as most as possible to a patent-free code like AV1 or VP9.

**Comment by aler9** [comment]
Streaming H265 with WebRTC is now supported with #4003
