### ISSUE TITLE
docker image has no tzdata so files are saved with incorect timestamps

### ISSUE THREAD

**Issue by dariuskt** [bluenviron/mediamtx#3390]
## Which version are you using?

docker image latest-ffmpeg
v1.8.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

files saved in UTC while should be saved in provided timezone

## Describe how to replicate the issue

1. setting filenames to contain time
```
recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
```

2. starting container with timezone set:
```
    environment:
      TZ: "Europe/Vilnius"
```
3. observe filename time is in UTC

## Did you attach the server logs?

no

## Did you attach a network dump?

no

## Solution

installing tzdata inside container fixes the problem for this run
```
apk update
apk add tzdata
```

hope image will contain tzdata by default so timezones will work out of the box

**Comment by aler9** [comment]
Hello, just mount `/etc/timezone` and `/etc/localtime` from the host:

```
docker run --rm -it -v /etc/timezone:/etc/timezone:ro /etc/localtime:/etc/localtime:ro bluenviron/mediamtx
```

we cannot add `tzdata` or any other packet to the base image since it's not based on any Operative System, while the `-ffmpeg` image is based on Alpine and the `-rpi` image is based on Raspbian.
