### ISSUE TITLE
Make webrtcHandshakeTimeout and webrtcTrackGatherTimeout configurable

### ISSUE THREAD

**Issue by jwalton** [bluenviron/mediamtx#3404]
## Describe the feature

I'm running into an issue where my WebRTC client is taking a little too long to complete the timeout.  We end up hitting the `webrtcHandshakeTimeout`, which kills the connection, then my client tries again, but fails again, and we end up in this loop of doom never playing video, but it could be solved if we could bump up the timeout a little.

So I'd like to raise a PR to make this configurable, but I'm wondering if you would prefer to see these added to the `Path` struct (so they could be configured per-path) or to the top level `Conf` struct?  I'm inclined towards the `Conf` struct, as it seems unlikely anyone would ever want to configure these path-by-path.

**Comment by aler9** [comment]
fixed by #3406
