### ISSUE TITLE
New webrtc configurations not recognized

### ISSUE THREAD

**Issue by MichaelRegan** [bluenviron/mediamtx#3418]
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Mediamtx will not start with the webrtcHandshakeTimeout and webrtcTrackGatherTimeout.
See #3404

## Describe how to replicate the issue

1. Copy over the new config file (pull from github)
2. start the server

## Did you attach the server logs?

 No. The issue is fixed by commenting out the two new configuration entries.

## Did you attach a network dump?

 No. The issue is fixed by commenting out the two new configuration entries.

**Comment by aler9** [comment]
webrtcHandshakeTimeout and webrtcTrackGatherTimeout are not present in v1.8.2 but they are in v1.8.3.
