### ISSUE TITLE
API 404 page not found  add patch delete

### ISSUE THREAD

**Issue by Fred14000** [bluenviron/mediamtx#3481]
## Which version are you using?

v1.8.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

API 404 page not found  when i make an add patch delete but ok with get...

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

curl -u user:pass -X DELETE http://127.0.0.1:9997/v3/paths/get/hik01

return
404 page not found

curl -u user:pass http://127.0.0.1:9997/v3/paths/get/hik01
work

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by moenodedev** [comment]
The delete url is `/v3/config/paths/delete/{name}`

https://github.com/bluenviron/mediamtx/blob/main/apidocs/openapi.yaml#L1246C3-L1259

**Comment by aler9** [comment]
Exactly as @moenodedev said.
