### ISSUE TITLE
Playback across segments

### ISSUE THREAD

**Issue by MengLi619** [bluenviron/mediamtx#3510]
## Describe the feature

Description

There is a requirement for us to playback near a time point (+/- 30s), but sometimes the stream will break, and multiple segments are created, the mediamtx only playback the first segment, which may not contain the desired time point. I don't know if there is any possibility to play all segments in the time range, regardless of any break in the middle.

Thanks a lot and appreciate your excellent work.

Mediamtx 1.5.1

**Comment by moenodedev** [comment]
Discussion #3243

**Comment by aler9** [comment]
Hello, we provide the `/list` endpoint that allows to list available time spans and allows users to build their own player around them and to manage gaps between segments in a personalized way.

If you want to skip gaps, then as mentioned by @moenodedev there's #3243

If you want to fill gaps, this is unimplemented but tracked in #2214 

If you want to fill gaps without waiting for the new feature, build a custom player that shows a blank screen during gaps.
