### ISSUE TITLE
Extra forward slash in RTSP SETUP

### ISSUE THREAD

**Issue by JoshDave** [bluenviron/mediamtx#3517]
## Which version are you using?

v1.8.3

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm having an issue with opening an RTSP stream on a Verint Nextiva S1816e. mediamtx is sending an extra forward slash during SETUP (rtsp://192.168.101.22//media/1/video/1), so the older Verint unit sends a 404 response. If I modify the SETUP packet so it doesn't have the extra forward slash (rtsp://192.168.101.22/media/1/video/1), then everything works properly.

## Describe how to replicate the issue

1. Start mediamtx with a config that has an RTSP link to a Verint Nextiva S1816e device.

## Did you attach the server logs?

yes: [mediamtx.log](https://github.com/user-attachments/files/16041665/mediamtx.log)

## Did you attach a network dump?

yes: [network-dump.zip](https://github.com/user-attachments/files/16041673/network-dump.zip)

**Comment by aler9** [comment]
fixed by https://github.com/bluenviron/gortsplib/pull/625
