### ISSUE TITLE
Due to the inability to batch insert paths, the interface timed out

### ISSUE THREAD

**Issue by liusuyi2021** [bluenviron/mediamtx#3541]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have two questions:
Firstly, when a large number of paths need to be added, multi-threaded path addition may experience a timeout
Secondly, it is not possible to restrict the UDP port range for web rtc local area network push pull streams

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
This is not a bug report. If you have questions, create a discussion for each question as mentioned in instructions.
