### ISSUE TITLE
regression: impossible to play/download recording segments using the start string provided from api

### ISSUE THREAD

**Issue by dottgonzo** [bluenviron/mediamtx#3553]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [x ] Linux amd64 standard
- [x ] Linux amd64 Docker
- [x ] Linux arm64 standard
- [x ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

Description

1) Try to get a recording from api and receive something like this (with italian timezone):

GET /v3/recordings/get/aaaa
```

[
    {
        "start": "2024-07-14T11:47:09.486344+02:00",
    }
]

```
2) try to use "2024-07-14T11:47:09.486344+02:00" for start time on the recordings

invalid start: parsing time "2024-07-14T11:47:09.486344+02:00" as "2006-01-02T15:04:05Z07:00": cannot parse " 02:00" as "Z07:00"

it answer that the date is wrong, because of golang time format. This cause to me to change manually the format of the date received from the api, and DELETE api is more hard to fix because of the nanoseconds.

**Comment by moenodedev** [comment]
Does https://github.com/bluenviron/mediamtx/issues/3313#issuecomment-2096176297 work for you?

**Comment by dottgonzo** [comment]
> Does [#3313 (comment)](https://github.com/bluenviron/mediamtx/issues/3313#issuecomment-2096176297) work for you?

No, it seems that +02:00 for timezone is invalid, only using zulu timezone with letter z works

**Comment by aler9** [comment]
As clearly written in the README, when using the `/get` endpoint of the playback server, the start date must be url-encoded, therefore this is the right way to call it:

```
http://localhost:9996/get?path=stream&start=2024-07-14T11%3A47%3A09.486344%2B02%3A00&duration=60
```

You are not url-encoding the start date and are instead using this url:

```
http://localhost:9996/get?path=stream&start=2024-07-14T11:47:09.486344+02:00&duration=60
```

The "+" sign in any URL gets interpreted as a space, therefore this is what the server sees:

```
2024-07-14T11:47:09.486344 02:00
```

resulting in an error.
