### ISSUE TITLE
Automatically reload when SSL certs change

### ISSUE THREAD

**Issue by dbason** [bluenviron/mediamtx#3570]
## Describe the feature
We have a system that automatically rotates SSL certs that are used in our RTMPS endpoint, however when the certs get updated they are not updated in mediamtx without restarting the service.  It would be a big QoL feature for the service to automatically reload these when they change.

**Comment by dottgonzo** [comment]
support let's encrypt pls!

**Comment by dbason** [comment]
I don't think we should bundle an ACME solver into the project; there is other software that does that better.  But we should definitely support the outcome of auto generate Lets Encrypt certs.
