### ISSUE TITLE
[WebRTC] Gstreamer sample code not working, server never gets the stream.

### ISSUE THREAD

**Issue by VanderBieu** [bluenviron/mediamtx#3573]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] Other (please describe) macOS arm64 standard

## Describe the issue

The gstreamer command cannot properly stream video to the server. The log shows nothing publishing to the server.

## Describe how to replicate the issue

1. start the server with default setting
2. publish with gstreamer command line `gst-launch-1.0 videotestsrc \
! video/x-raw,width=1920,height=1080,format=I420 \
! x264enc speed-preset=ultrafast bitrate=2000 \
! video/x-h264,profile=baseline \
! whipclientsink signaller::whip-endpoint=http://localhost:8889/mystream/whip`
3. read with browser

## Did you attach the server logs?

yes.
2024/07/24 19:43:56 INF MediaMTX v1.8.4
2024/07/24 19:43:56 INF configuration loaded from C:\Users\xwh\Projects\mediamtx_v1.8.4_windows_amd64\mediamtx.yml
2024/07/24 19:43:56 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2024/07/24 19:43:56 INF [RTMP] listener opened on :1935
2024/07/24 19:43:56 INF [HLS] listener opened on :8888
2024/07/24 19:43:56 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2024/07/24 19:43:56 INF [SRT] listener opened on :8890 (UDP)

Nothing happened.

## Did you attach a network dump?

 no. I tested on localhost.

**Comment by VanderBieu** [comment]
OBS and browser worked fine, so it seems this has nothing to do with my platform.

**Comment by aler9** [comment]
Hello, the command you posted:

```
videotestsrc ! video/x-raw,width=1920,height=1080,format=I420 ! x264enc speed-preset=ultrafast bitrate=2000 ! video/x-h264,profile=baseline ! whipclientsink signaller::whip-endpoint=http://localhost:8889/mystream/whip
```

works perfectly:

```
2024/09/15 22:26:58 INF [WebRTC] [session d2fc0db6] created by 127.0.0.1:60154
2024/09/15 22:26:58 INF [WebRTC] [session d2fc0db6] peer connection established, local candidate: host/udp/192.168.3.26/8189, remote candidate: host/udp/192.168.3.26/35399
2024/09/15 22:26:59 INF [WebRTC] [session d2fc0db6] is publishing to path 'mystream', 1 track (H264)
```

In your server logs there's no trace of incoming connections. Make sure that GStreamer and the server can communicate correctly, otherwise adjust the IP address accordingly.

**Comment by airfield20** [comment]
I can confirm this command does **not** work on my system. Running mediamtx in a docker container in host networking mode on localhost.
