### ISSUE TITLE
invalid SDP: sdp: invalid value `text`

### ISSUE THREAD

**Issue by prakritish** [bluenviron/mediamtx#3583]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [x] macOS arm64 standard

## Describe the issue

Mediamtx is not able to read RTSP Streams from Wisenet NVR

## Describe how to replicate the issue

The `mediamtx.yml` is configured with source as follows:
```
paths:
  camera/1:
    source: 'rtsp://XXXXX:XXXXXX@10.1.10.178:7001/d9578fe4-a8f4-ceab-7276-94aff8cb1fe1'

```
Start the mediamtx server
## Did you attach the server logs?
yes 

```
2024/07/29 17:33:40 DEB [path camera/1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 3
Content-Base: rtsp://10.1.10.178:7001/d9578fe4-a8f4-ceab-7276-94aff8cb1fe1
Content-Length: 347
Content-Type: application/sdp
Date: Tue, 30 Jul 2024 00:34:12 GMT
Range: clock=20240712T143958.84Z-19700120T222459.652822Z
Server: Wisenet WAVE/5.1.1.37512 (Hanwha) Apache/2.4.16 (MSWin)
Session: 24175057766081730192684;timeout=60

v=0
s=DWC-MV94WiAT
c=IN IP4 10.1.10.178
m=video 0 RTP/AVP 96
a=control:trackID=0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z00AMpY1QFEBf03AQEBAgA==,aO4xsg==; profile-level-id=4D0032
m=audio 0 RTP/AVP 14
a=control:trackID=1
m=text 0 RTP/AVP 103
a=control:trackID=2
a=rtpmap:103 object-detection/1000


2024/07/29 17:33:40 ERR [path camera/1] [RTSP source] invalid SDP: sdp: invalid value `text`
2024/07/29 17:33:45 DEB [path camera/1] [RTSP source] connecting
2024/07/29 17:33:45 DEB [path camera/1] [RTSP source] [c->s] OPTIONS rtsp://10.1.10.178:7001/d9578fe4-a8f4-ceab-7276-94aff8cb1fe1 RTSP/1.0
CSeq: 1
User-Agent: gortsplib

```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the issue and providing the SDP, this is fixed by https://github.com/bluenviron/gortsplib/pull/615
