### ISSUE TITLE
RTP packet lost 

### ISSUE THREAD

**Issue by MubashirWaheed** [bluenviron/mediamtx#3602]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I want to stream the video from the camera to the browser. I have the stream working using the rtsp url in the vlc but after running the server I am getting black screen in browser. 

## Describe how to replicate the issue

1. Downloaded the exe from here: https://github.com/bluenviron/mediamtx/releases
2. make necessary changes in the yml file
3. run the executable
4. Check browser

## Did you attach the server logs?

yes 

```js
2024/08/03 13:36:21 INF [path proxied1] [RTSP source] ready: 2 tracks (H265, G711)
2024/08/03 13:36:24 INF [WebRTC] [session 7265d875] created by [::1]:50361
2024/08/03 13:36:24 INF [WebRTC] [session 7265d875] peer connection established, local candidate: host/udp/192.168.0.44/8189, remote candidate: prflx/udp/192.168.56.1/51525
2024/08/03 13:36:24 INF [WebRTC] [session 7265d875] is reading from path 'proxied1', 1 track (G711)
2024/08/03 13:36:30 WAR [path proxied2] [RTSP source] 7 RTP packets lost
2024/08/03 13:36:48 WAR [path proxied2] [RTSP source] 16 RTP packets lost
2024/08/03 13:36:58 WAR [path proxied2] [RTSP source] 3 RTP packets lost
2024/08/03 13:37:22 WAR [path proxied2] [RTSP source] 1 RTP packet lost
```

## Did you attach a network dump?

no

## mediamtx.yml
I made following changes
```
paths:
  proxied1:
    source: rtsp://<username>:<password>@192.168.0.126:554/Streaming/Channels/1201
    rtspTransport: tcp
  proxied2:
    source: rtsp:/<username>:<password>@192.168.0.126:554/Streaming/Channels/1101

protocols: [tcp,udp, multicast]
writeQueueSize: 1024 # 512  (increased the size)
```
What is the possible issue?

**Comment by aler9** [comment]
please read here: https://github.com/bluenviron/mediamtx?tab=readme-ov-file#corrupted-frames

in particular:

> The stream throughput is too big to be handled by the network between server and readers. Upgrade the network or decrease the stream bitrate by re-encoding it.
