### ISSUE TITLE
InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by qibao07** [bluenviron/mediamtx#3662]
## Which version are you using?

v1.8.5

## Which operating system are you using?

- [x] Linux arm64 Docker

## Describe the issue

Android Google Chrome cannot play live broadcast.

## Describe how to replicate the issue

1. Start service
```
NAME=mediamtx
IMAGE=bluenviron/mediamtx:1.8.5

docker run -d --restart unless-stopped --name $NAME \
  -e MTX_PROTOCOLS=tcp \
  -e MTX_WEBRTCADDITIONALHOSTS=192.168.x.x \
  -p 8554:8554 \
  -p 1935:1935 \
  -p 8888:8888 \
  -p 8889:8889 \
  -p 8890:8890/udp \
  -p 8189:8189/udp \
  $IMAGE
```
2. push video
```
ffmpeg -f v4l2 -video_size 1360x768 -framerate 50 -pix_fmt mjpeg -i /dev/video0 -f alsa -i hw:$HW_NO -c:v libx264 -preset ultrafast -tune zerolatency -rtsp_transport tcp -async 1 -vsync 1 -f rtsp rtsp://192.168.x.x:8554/live/tv
```
3. Open the browser http://192.168.x.x:8888/live/tv/

Windows computers can play live broadcasts, but Android phones and pad cannot play live broadcasts using Google Chrome.

![image](https://github.com/user-attachments/assets/b32d3184-45ed-4375-81fd-fd176e5bbcbf)

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by felder** [comment]
For what it's worth I just had a customer report this error as well with mediamtx 1.8.5 running (undockerized) on ubuntu jammy.  Prior to upgrading from 1.8.1 to 1.8.5, this had never been reported.

**Comment by felder** [comment]
Additional info, the customer that reported this indicated they were using chrome on a macbook air.

**Comment by felder** [comment]
Config attached:

[mediamtx.yml.v1.8.5.txt](https://github.com/user-attachments/files/16715587/mediamtx.yml.v1.8.5.txt)

One other thing that we do is use apache as a proxy, but no changes have been made there.

**Comment by aler9** [comment]
Hello, this error is triggered inside the hls.js library, which is an external component that is updated automatically throughout releases. No other changes have been performed in the HLS muxing system between v1.8.1 and v1.8.5. Recently, hls.js has been updated again, therefore, please test this nightly release and let me know if it fixes the issue (click on "Artifacts", "binaries"):

https://github.com/bluenviron/mediamtx/actions/runs/10526351735

**Comment by qibao07** [comment]
@aler9 
I used the program you provided and the problem persists.

**Comment by qibao07** [comment]
```
ffmpeg -re -i input.mp4 -c:v copy -c:a aac -f rtsp rtsp://192.168.x.x:8554/live/tv
```
So strange, When I use the above command to push the stream, both mobile phones and PC browsers can play it.

Only the camera video and audio are pushed and cannot be played on the mobile phone.

**Comment by jwetzell** [comment]
I experience this same error if the camera is configured with H.265 as the encoding method. The same camera set to H.264 works just fine.

**Comment by aler9** [comment]
i took another look at the command initially posted by @qibao07:

```
ffmpeg \
-f v4l2 -video_size 1360x768 -framerate 50 -pix_fmt mjpeg -i /dev/video0 \
-f alsa -i hw:$HW_NO -c:v libx264 -preset ultrafast -tune zerolatency \
-rtsp_transport tcp -async 1 -vsync 1 -f rtsp rtsp://192.168.x.x:8554/live/tv
```

the reason why this problem happens is that you forgot to set the output pixel format to YUV420:

```
ffmpeg \
-f v4l2 -video_size 1360x768 -framerate 50 -pix_fmt mjpeg -i /dev/video0 \
-f alsa -i hw:$HW_NO -c:v libx264 -pix_fmt yuv420p -preset ultrafast -tune zerolatency \
-rtsp_transport tcp -async 1 -vsync 1 -f rtsp rtsp://192.168.x.x:8554/live/tv
```

If pix_fmt is not set, ffmpeg uses yuv422 which has limited compatibility.

@jwetzell your issue is unrelated from this one. Keep in mind that most browsers cannot play H265 (except the Windows+Chrome+GPU combination). You can check whether your browser supports H265 by using the tool available in [this section of the README](https://github.com/bluenviron/mediamtx?tab=readme-ov-file#hls). If you still have issues, open a dedicated bug report.

**Comment by jwetzell** [comment]
I just saw the same exact error message as reported in this issue and the setup I am using does support h265 as verified by multiple tools including that one you linked.

**Comment by aler9** [comment]
@jwetzell yes, open a dedicated issue since your bug it's related to H265 and therefore to a different set of codec and parameters. Also provide server logs with `logLevel: debug` that allows to see codec parameters.

**Comment by felder** [comment]
Noting that we're now testing v1.11.0.  Hopefully the issue is gone.  Since this issue is closed, I'll open another if we're still seeing this.
