### ISSUE TITLE
mediamtx get a “not in use“ error

### ISSUE THREAD

**Issue by WorstCodeWay** [bluenviron/mediamtx#3711]
## Which version are you using?

v1.8.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm new to `ffmpeg` and `NVENC` and developing a application based on them.  When I create a new stream(not put any packets to stream yet) within ffmpeg and mediamtx do print the log, which indicating stream is created.

```
2024/08/25 03:24:55 INF [RTSP] [session ba987311] created by 127.0.0.1:60348
2024/08/25 03:24:55 INF [RTSP] [session ba987311] is publishing to path '1716994691793829/1716994698048844/OrignalStream', 1 track (H264)
```

However, mediamtx log shows me that the created session is destroyed after about 10s, as following log:
```
2024/08/25 03:25:05 INF [RTSP] [conn 127.0.0.1:60348] closed: read tcp 127.0.0.1:8554->127.0.0.1:60348: i/o timeout
2024/08/25 03:25:05 INF [RTSP] [session ba987311] destroyed: not in use
```
I'm wondering what the i/o timeout means? It seems to me has something to do with `readTimeout`? And if there is a timeout, how can I set it to 'Never' meaning never timeout? 

## Describe how to replicate the issue

1. start the server
2. create new stream within [ffmpeg]([server.log](https://github.com/user-attachments/files/16811936/server.log))

## Did you attach the server logs?

yes
[server.log](https://github.com/user-attachments/files/16811943/server.log)

## Did you attach a network dump?

yes / no

**Comment by secit** [comment]
In the configuration file, there's a variable `readTimeout` you can change.
According to the net library, if you set it to a zero value when the operation will not time out.

**Comment by WorstCodeWay** [comment]
> In the configuration file, there's a variable `readTimeout` you can change.
> According to the net library, if you set it to a zero value when the operation will not time out.

@secit  Set `readTimeout` to '0s' will get a error after mediamtx startup:

> ERR listen: invalid config: ConnectionTimeout must be greater than 0

**Comment by WorstCodeWay** [comment]
> > @secit Set `readTimeout` to '0s' will get an error after `mediamtx` starts up:
> 
> @WorstCodeWay sorry, I forgot ALL services use the same value. It seems that the SRT server doesn't handle the zero value very well. You can set `srt: no` in the config if you don't need it and then it should work.

Thanks for quickly reply. But where to find `srt` parameter, is it within `mediamtx.yml`, or do I just add that parameter into `mediamtx.yml`?

**Comment by aler9** [comment]
Hello, this error happens because you're not publishing anything, and the server expects packets within a timespan. This timespan can be set with `readTimeout` inside the configuration file. Setting `readTimeout` to zero is not supported.
Be careful that most RTSP clients will expect some data within a short timespan any way, and will close the connection otherwise. RTSP in general is not fit for creating a session and not using it.

**Comment by secit** [comment]
> Thanks for quickly reply. But where to find `srt` parameter, is it within `mediamtx.yml`, or do I just add that parameter into `mediamtx.yml`?

Yes, it's in the `mediamtx.yml` file. It's set to `srt: yes` as default, just change it to `no`.
But I agree with aler9. You should increase the timeout rather than set it to never timeout if you're unable to start sending packets within the 10s frame.
