### ISSUE TITLE
Docker says all is well, but every method to stream to server fails. From Discussion #3346

### ISSUE THREAD

**Issue by darkshoxx** [bluenviron/mediamtx#3740]
## Which version are you using?

v1.8.5
I run Win 11 with a clean install of Docker Desktop (yes I have rebooted), I have WSL 2.1.5.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [x] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

My goal is to stream to and from the server using OBS, I'm trying everything in my power to stream to my server, but each method  (OBS, python + OpenCV, FFMPEG, VLC, WebRTC) gives me an error or does nothing. I have followed the instructions on docker hub and github.

## Describe how to replicate the issue

1. docker pull bluenviron/mediamtx
2. docker run --rm -it --network=host bluenviron/mediamtx
3. several Options, will list one by one as sub-points:
3a. ffmpeg -re -stream_loop -1 -i room.ts -c copy -f rtsp rtsp://localhost:8554/mystream
3b. OBS stream to rtmp://localhost with (and without) streamkey mystream 
3c. using a python 3.10 venv with opencv-python 4.10.0.84 and the exact script from the readme file
3d. Attempting to use WebRTC with http://localhost:8889/mystream/publish
3e. start VLC,  Ctrl+S, I choose a file to stream, add an RTSP server with port 8554
4. See Discussion https://github.com/bluenviron/mediamtx/discussions/3664 for the individual consequences

## Did you attach the server logs?

yes, but all it gives is this status on bootup
```
2024/08/16 18:02:20 INF MediaMTX v1.8.5
2024/08/16 18:02:20 INF configuration loaded from /mediamtx.yml
2024/08/16 18:02:20 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2024/08/16 18:02:20 INF [RTMP] listener opened on :1935
2024/08/16 18:02:20 INF [HLS] listener opened on :8888
2024/08/16 18:02:20 INF [WebRTC] listener opened on :8889 (HTTP), :8189 (ICE/UDP)
2024/08/16 18:02:20 INF [SRT] listener opened on :8890 (UDP)
```

The server does not change or print any new lines in any of the attempts. More details see original discussion: https://github.com/bluenviron/mediamtx/discussions/3664

## Did you attach a network dump?

no

**Comment by aler9** [comment]
unrelated from MediaMTX, see https://github.com/bluenviron/mediamtx/discussions/3664#discussioncomment-10557303
