### ISSUE TITLE
QUIC protocol for RTP 

### ISSUE THREAD

**Issue by erikherz** [bluenviron/mediamtx#3742]
Description

QUIC (Quick UDP Internet Connection) is a standard protocol (HTTP 3.0) that offers significant improvements in terms of speed, reliability, and security over TCP. I propose that MediaMTX implemets support of QUIC protocol (Datagrams and Streams) for being possible to read live streams from the server via RTP (SDP, SIP, RTSP, etc).

https://datatracker.ietf.org/doc/draft-ietf-avtcore-rtp-over-quic/
https://github.com/mengelbart/roq
https://github.com/bbc/gst-roq
https://www.meetecho.com/blog/moq-webrtc/
https://www.meetecho.com/blog/roq-n-roll/

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
