### ISSUE TITLE
RecordSegmentDuration operating range

### ISSUE THREAD

**Issue by GagaKor** [bluenviron/mediamtx#3765]
Recorded in mpegts format and had option RecordSegmentDuration: 1s.
However, the saving is not done in 1 second increments, but in 6-7 second increments.
Even if it is longer than 1 minute, it is not saved in that time unit.

## Which version are you using?

v1.9.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Hello, video segments cannot be cut randomly but they can only be cut in the presence of an I-frame, that in case of you stream, is present once every 6-7 seconds. If you want to change this, re-encode the stream with FFMpeg or change the "I-frame interval" setting inside your camera.
