### ISSUE TITLE
RTMP push from OpenIPC web camera doesn't work (while RTSP pull with the same audio/video settings works)

### ISSUE THREAD

**Issue by MalgathThelamin** [bluenviron/mediamtx#3783]
## Which version are you using?

v1.8.5

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I push an RTMP stream from my camera (102.168.0.188, running OpenIPC) to MediaMTX (192.168.0.2). It says:
```
INF [RTMP] [conn 192.168.0.188:51916] is publishing to path 'mystream', 2 tracks (H264, MPEG-4 Audio)
```
However, http://192.168.0.2:8888/mystream and http://192.168.0.2:8889/mystream show black video player.

If I stop the video pushing from the camera and configure MediaMTX to pull the video from the camera via RTSP protocol, both players show video normally.

## Describe how to replicate the issue

1. Configure an OpenIPC camera to push RTMP stream to rtmp://**[MediaMTX IP]**/mystream (Majestic > Settings > Outgoing)
2. Run MediaMTX.
3. Open http://**[MediaMTX IP]**/mystream with your browser.

## Did you attach the server logs?

yes

[mediamtx.log](https://github.com/user-attachments/files/17009770/mediamtx.log)

## Did you attach a network dump?

no

**Comment by pstemporowski-prenode** [comment]
We have similar issue with RTSP #3563
