### ISSUE TITLE
Latency is higher than 4 seconds when streaming a video with WebRTC in firefox browser

### ISSUE THREAD

**Issue by Martayugui** [bluenviron/mediamtx#3789]
## Which version are you using?

v1.9.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am reading video stream packets from the server with a web browser (firefox) and WebRTC to minimize latency (ultra low latency application). The publisher is sending UDP video stream packets via 5546 port like:

#!/usr/bin/env bash

ffmpeg -stream_loop -1 -i Big_Buck_Bunny_1080_10s_10MB.mp4 -vf "scale=720:480,  fps=10" \
-c:v libx264   -b:v 500k \
-bf 0 \
-f mpegts udp://0.0.0.0:5546?pkt_size=1316

## Describe how to replicate the issue

1. Configure mediamtx.yml
paths:
   mypath:
     source: udp://127.0.0.1:5546
     
2. Start the server
./mediamtx

3. Publish video stream:
    #!/usr/bin/env bash
    
    ffmpeg -stream_loop -1 -i Big_Buck_Bunny_1080_10s_10MB.mp4 -vf "scale=720:480,  fps=10" \
    -c:v libx264   -b:v 500k \
    -bf 0 \
    -f mpegts udp://0.0.0.0:5546?pkt_size=1316

4. Read with browser:
http://localhost:8889

## Did you attach the server logs?

2024/09/19 10:36:42 INF [WebRTC] [session 2e67113b] created by 127.0.0.1:44764
2024/09/19 10:36:42 INF [WebRTC] [session 2e67113b] closed: no one is publishing to path 'mypath'
2024/09/19 10:36:42 DEB [WebRTC] [conn 127.0.0.1:44764] [s->c] HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 49 bytes)
2024/09/19 10:36:42 DEB [path mypath] [UDP source] connecting
2024/09/19 10:36:42 INF [path mypath] [UDP source] ready: 1 track (H264)
2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [c->s] OPTIONS /mypath/whep HTTP/1.1
Host: localhost:8889
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Origin: http://localhost:8889
Priority: u=4
Referer: http://localhost:8889/mypath/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0

2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [s->c] HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization, Content-Type, If-Match
Access-Control-Allow-Methods: OPTIONS, GET, POST, PATCH, DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link
Server: mediamtx

2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [c->s] POST /mypath/whep HTTP/1.1
Host: localhost:8889
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Content-Length: 3013
Content-Type: application/sdp
Origin: http://localhost:8889
Priority: u=4
Referer: http://localhost:8889/mypath/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0

v=0
o=mozilla...THIS_IS_SDPARTA-99.0 816393163097770547 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 F9:28:41:14:9D:35:11:73:29:62:2F:E3:A7:7E:AD:92:98:0C:ED:28:D1:E7:30:E4:2F:B5:0E:00:C6:B5:CC:CD
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98 123 122 119
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:124 apt=120
a=fmtp:121 max-fs=12288;max-fr=60
a=fmtp:125 apt=121
a=fmtp:127 apt=126
a=fmtp:98 apt=97
a=fmtp:119 apt=122
a=ice-pwd:0679c5a23d322452259912112eeddc53
a=ice-ufrag:60ec4a7f
a=mid:0
a=msid:- {c02bbbcd-8978-43aa-9170-0e9d10b8aa83}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 transport-cc
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:122 nack
a=rtcp-fb:122 nack pli
a=rtcp-fb:122 ccm fir
a=rtcp-fb:122 goog-remb
a=rtcp-fb:122 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=rtpmap:126 H264/90000
a=rtpmap:127 rtx/90000
a=rtpmap:97 H264/90000
a=rtpmap:98 rtx/90000
a=rtpmap:123 ulpfec/90000
a=rtpmap:122 red/90000
a=rtpmap:119 rtx/90000
a=setup:actpass
a=ssrc:104098234 cname:{0209fd6d-9e50-44e3-b32c-1331d0eb041f}
a=ssrc:3488881265 cname:{0209fd6d-9e50-44e3-b32c-1331d0eb041f}
a=ssrc-group:FID 104098234 3488881265
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1;sprop-stereo=1
a=fmtp:101 0-15
a=ice-pwd:0679c5a23d322452259912112eeddc53
a=ice-ufrag:60ec4a7f
a=mid:1
a=msid:- {62a5a70b-be97-4aad-ab23-8f76d0fd7eba}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=setup:actpass
a=ssrc:4038042488 cname:{0209fd6d-9e50-44e3-b32c-1331d0eb041f}

2024/09/19 10:36:44 INF [WebRTC] [session 6af21246] created by 127.0.0.1:44764
2024/09/19 10:36:44 DEB [WebRTC] [session 6af21246] peer connection state: connecting
2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [s->c] HTTP/1.1 201 Created
Accept-Patch: application/trickle-ice-sdpfrag
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, ID, Accept-Patch, Link, Location
Content-Type: application/sdp
Etag: *
Id: 6af21246-186e-4ad6-8b70-dd239acbda91
Location: /mypath/whep/32a449bd-5c34-4df5-9c61-e6e8dc5d13b9
Server: mediamtx

(body of 1668 bytes)
2024/09/19 10:36:44 DEB [WebRTC] [session 6af21246] peer connection state: connected
2024/09/19 10:36:44 INF [WebRTC] [session 6af21246] peer connection established, local candidate: host/udp/172.16.222.112/8189, remote candidate: prflx/udp/50.100.2.112/47163
2024/09/19 10:36:44 INF [WebRTC] [session 6af21246] is reading from path 'mypath', 1 track (H264)
2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [c->s] PATCH /mypath/whep/32a449bd-5c34-4df5-9c61-e6e8dc5d13b9 HTTP/1.1
Host: localhost:8889
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 970
Content-Type: application/trickle-ice-sdpfrag
If-Match: *
Origin: http://localhost:8889
Pragma: no-cache
Priority: u=4
Referer: http://localhost:8889/mypath/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0

a=ice-ufrag:60ec4a7f
a=ice-pwd:0679c5a23d322452259912112eeddc53
m=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98 123 122 119
a=mid:0
a=candidate:0 1 UDP 2122252543 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 47163 typ host
a=candidate:1 1 TCP 2105524479 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 36073 typ host
a=candidate:1 2 TCP 2105524478 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 9 typ host tcptype active
a=
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
a=mid:1
a=candidate:0 1 UDP 2122252543 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 58703 typ host
a=candidate:1 1 TCP 2105524479 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 33387 typ host
a=candidate:1 2 TCP 2105524478 cba01261-ab4c-49ba-97c1-cc5c425f43cc.local 9 typ host tcptype active
a=

2024/09/19 10:36:44 DEB [WebRTC] [conn 127.0.0.1:44764] [s->c] HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Server: mediamtx

## Did you attach a network dump?

yes / no

**Comment by RedShift1** [comment]
The latency is from ffmpeg, not MediaMTX. Read more about it here: https://trac.ffmpeg.org/wiki/StreamingGuide#Latency. At the very least, add `-tune lowlatency` for h264.

**Comment by aler9** [comment]
Exactly. A sample FFmpeg command which introduces minimal latency is available in the README:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#remuxing-re-encoding-compression
