### ISSUE TITLE
missing "srtSource" in srtlist

### ISSUE THREAD

**Issue by gre2gor** [bluenviron/mediamtx#3792]
## Which version are you using?

v1.9.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I want to see stats of the srtSource, only SrtConn stats are available. 

## Describe how to replicate the issue

http://localhost:9997/v3/srtconns/list where no srtSource paths/sources are visible

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the `/srtconn/list` endpoint is meant for providing data about SRT publishers and readers, not SRT sources.
Regarding sources, currently the only available statistics are the number of incoming and outgoing bytes, available in `/paths/list`. I've created a feature request for adding protocol-specific source: statistics #4086
