### ISSUE TITLE
WebRTC closing connection when It's still able to recover

### ISSUE THREAD

**Issue by Clemens-E** [bluenviron/mediamtx#3820]
### Which version are you using?

1.9.1

### Which operating system are you using?

Linux arm64 standard

### Describe how to replicate the issue

I'm streaming 6 Cameras using WebRTC over a TURN server. Every 1-2 Minutes, each stream displays "peer connection closed", then it loads for 5 Seconds until it has been reconnected. The connection was running over LTE so I expected some connection issues, but not this frequent.

My observation:
The Javascript in [read_index.html](https://github.com/bluenviron/mediamtx/blob/main/internal/servers/webrtc/read_index.html#L489) terminates a connection when its state changes to "disconnected".

However [RTCPeerConnection/iceConnectionState#disconnected](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState#disconnected) says:
> This is a less stringent test than failed and may trigger intermittently and resolve just as spontaneously on less reliable networks, or during temporary disconnections. When the problem resolves, the connection may return to the connected state. 

I removed the above-mentioned code that triggers a full reconnect when the state changes to "disconnected", and instead added a console.log with Date.now and the iceConnectionState.
After waiting for a bit, I got following log:
```
1727778552340 disconnected
1727778552394 connected
```
Showing it took about 54ms before the connection resumed
My proposal would be using the "failed" state, or re-checking if the connection returns to "connected" within a certain time frame.

Steps to reproduce:
1. configure any camera & enable WebRTC
2. start server
3. open ip:8889/camera_xyz
4. wait until peer is disconnected

**Comment by Clemens-E** [comment]
I had good results with this logic: 
If the connection has not recovered within 2 seconds I issue a full reconnect.

In most cases the connection recovers in less than 100ms, this handles the edge cases where it does not.

**Comment by alexunderboots** [comment]
same problem

**Comment by aler9** [comment]
this was fixed by #3899, even though we will probably need to perform a half rollback due to #4022
