### ISSUE TITLE
1. RTMP source not works , 2. udp multicast output 224.2.2.26:2226

### ISSUE THREAD

**Issue by jitutrivedi** [bluenviron/mediamtx#3838]
### Describe the feature

1. when i try to give RTMP source always gives invalid body size..
2.  how can i get udp multicast output e.g 224.2.2.26:2226
![ssh](https://github.com/user-attachments/assets/ff942a0b-c7b9-44ab-9078-802691fe0c63)

**Comment by aler9** [comment]
This is not a feature request. Please follow instructions in order to ask questions or fill bug reports.
