### ISSUE TITLE
Error 404 when using pprof

### ISSUE THREAD

**Issue by Gubka595** [bluenviron/mediamtx#3848]
### Which version are you using?

1.9.2

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

1. In the configuration file, specify the pprof field: yes
2. Start servis
3. Execute the command go tool pprof -text http://localhost:9999/debug/pprof/goroutine
4. we received an error: Fetching profile over HTTP from http://localhost:9999/debug/pprof/goroutine
http://localhost:9999/debug/pprof/goroutine: server response: 404 Not Found
failed to fetch any source profiles
5. At the same time, if you go to the page http://localhost:9999/debug/pprof / an interface opens in which nothing happens when you select profile, and an error is output to the log file 404 NOT FOUND

### Server logs

[mediamtx.log](https://github.com/user-attachments/files/17293010/mediamtx.log)

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #3851
