### ISSUE TITLE
OBS RTMP doesn't seem to be able to publish to the server

### ISSUE THREAD

**Issue by killerbigpoint** [bluenviron/mediamtx#3879]
### Which version are you using?

1.9.2

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

Streaming via RTMP using OBS doesn't seem to work when authentication is being used

- Literally just change the authentication to be anything but 'any'
- Enable authentication when using RTMP inside of OBS, at the time of writing I am using v30.2.3
- Press stream and watch as the authentication fails

As a sidenote, when using http as authentication and sending it to a request catcher shows that both the username and password only has ":" in them

{"ip":"*.*.*.*","user":"","password":"","action":"publish","path":"live","protocol":"rtmp","id":"e7076706-fdb7-4e7c-af6f-6803d9a9484d","query":""}

### Server logs

2024/10/15 14:58:10 INF MediaMTX v1.9.2
2024/10/15 14:58:10 INF configuration loaded from /root/mediamtx.yml
2024/10/15 14:58:10 DEB path manager created
2024/10/15 14:58:10 INF [RTSP] listener opened on :554 (TCP)
2024/10/15 14:58:10 INF [RTMP] listener opened on :1935
2024/10/15 14:58:10 INF [HLS] listener opened on :443
2024/10/15 14:58:12 INF [RTMP] [conn *.*.*.*:58656] opened
2024/10/15 14:58:15 INF [RTMP] [conn *.*.*.*:58656] closed: authentication failed: authentication failed

**Comment by aler9** [comment]
please read here, in particular the part regarding authentication:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#obs-studio
