### ISSUE TITLE
run ./mediamtx & ，but exit ，log have no panic

### ISSUE THREAD

**Issue by hotwinters** [bluenviron/mediamtx#3882]
### Which version are you using?

1.9

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

I don't know how to find the reason for the background automatic exit, because the total memory remaining in the system is low, only 1G, so I suspect that the system has been killed, but it doesn't appear in the system message. I opened the log of mediamtx, but there is nothing in the log, and there is even no stream using this service. I request the help of experts to help newcomers

**Comment by aler9** [comment]
Sorry but this is impossible to understand.
