### ISSUE TITLE
HLS don't work with AMD HW AV1 

### ISSUE THREAD

**Issue by DoM1niC** [bluenviron/mediamtx#3902]
### Which version are you using?

main

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

Publish a Stream in RTMP or WHEP with AMD HW AV1 failed to get a valid HLS Stream, e.g. switch to CPU based Codec SVT-AV1 or NVENC HLS will work fine by this Codecs / Encoder.

### Server logs

`ERR [HLS] [muxer dom1nic] muxer error: unable to parse AV1 sequence header: timing_info_present_flag is not supported yet`

**Comment by DoM1niC** [comment]
I tested it with a person who have NVENC (Nvidia), this works fine here !

**Comment by aler9** [comment]
As written inside instructions, please provide a network dump that contains the stream. It can be generated in this way:

1. Download wireshark (https://www.wireshark.org/)
2. Start capturing on the interface used for exchanging packets
    * If the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card.
3. Start the server, publish the AV1 stream to the server with RTMP
4. Stop capturing, save the result in .pcap format
5. Attach

**Comment by DoM1niC** [comment]
> As written inside instructions, please provide a network dump that contains the stream. It can be generated in this way:
> 
> 1. Download wireshark (https://www.wireshark.org/)
> 2. Start capturing on the interface used for exchanging packets
>    
>    * If the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card.
> 3. Start the server, publish the AV1 stream to the server with RTMP
> 4. Stop capturing, save the result in .pcap format
> 5. Attach

No Problem :) und THX for your Support 💯 

[Mediamtx RTMP (AV1) Publish.zip](https://github.com/user-attachments/files/18219130/Mediamtx.RTMP.AV1.Publish.zip)

**Comment by aler9** [comment]
Thank you very much for providing the network dump that allowed to replicate the issue.
This should be fixed by https://github.com/bluenviron/mediacommon/pull/162
Please test this nightly release and let me know if it works (click on "artifacts", "Binaries"):
https://github.com/bluenviron/mediamtx/actions/runs/12447857225

**Comment by DoM1niC** [comment]
> Thank you very much for providing the network dump that allowed to replicate the issue. This should be fixed by [bluenviron/mediacommon#162](https://github.com/bluenviron/mediacommon/pull/162) Please test this nightly release and let me know if it works (click on "artifacts", "Binaries"): https://github.com/bluenviron/mediamtx/actions/runs/12447857225

THX YOU SOOOO MUCH 💯  seems to work fine so far !!!

**Comment by DoM1niC** [comment]
I have to reopen after some Tests I notice the Audio Codec is missing on AV1 Stream, in the first I though my OBS Studio is misconfigured but after I switch to other Encoders the Audio was back without any changes on my Sources. 

![image](https://github.com/user-attachments/assets/dac36031-c25d-42aa-abf8-2769d8dbd6f2)

**Comment by DoM1niC** [comment]
on WHIP with Opus the WebRTC based Stream have Audio but no Codec in HLS Stream and RTMP to WebRTC the Audio is missing too.
