### ISSUE TITLE
UNV XVR

### ISSUE THREAD

**Issue by BharadwajManne** [bluenviron/mediamtx#3932]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux arm64 standard

### Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

Problem with UNV XVR , live and record are stopping after 5 -10 mins.

**Comment by aler9** [comment]
No data that allows to replicate the issue was provided. If you still have problems, create another issue and provide instructions on how to replicate, server configuration and server logs at least.
