### ISSUE TITLE
After streaming for hours  getting error "no one is publishing to 'cam1'

### ISSUE THREAD

**Issue by enisertdev** [bluenviron/mediamtx#3961]
### Which version are you using?

mediamtx_v1.9.3

### Which operating system are you using?

Linux arm64 standard

### Describe how to replicate the issue

I am using mediamtx on RPi 5 and using camera module 3 to stream, i can stream the camera for hours with no problem but after 8-10 hours i get "no one is publishing to 'cam1' error out of nowhere, on the logs it says connection problem with camera but when i restart the stream it starts working again.

### Server logs

![image](https://github.com/user-attachments/assets/54c23850-1043-4af6-9091-b326a379a2df)

**Comment by marksutheran** [comment]
FYI: I have consistently seen similar behaviour on RPi4 cameras. It may be some issue with the underlying libcamera however, I never got to the bottom of it - just monitored the bytes received and restarted when necessary

**Comment by aler9** [comment]
Hello, i noticed too that the server is currently unable to restart the camera when a driver error happens (for instance, "camera frontend has timed out"). This is fixed by #3988
