### ISSUE TITLE
RTSP conn API should also have path property, like RTMP does

### ISSUE THREAD

**Issue by terion-name** [bluenviron/mediamtx#3974]
### Describe the feature

RTMP:
https://bluenviron.github.io/mediamtx/#operation/rtmpConnectionsGet
```json
{
  "id": "string",
  "created": "string",
  "remoteAddr": "string",
  "state": "idle",
  "path": "string",
  "query": "string",
  "bytesReceived": 0,
  "bytesSent": 0
}
```

RTSP:
https://bluenviron.github.io/mediamtx/#operation/rtspConnsGet
```json
{
  "id": "string",
  "created": "string",
  "remoteAddr": "string",
  "bytesReceived": 0,
  "bytesSent": 0
}
```

Absence of state, path, query fields makes rtsp api literally useless

**Comment by aler9** [comment]
You are confusing RTSP connections with RTSP sessions.
A RTSP connection is used to initialize a RTSP session.
A RTSP session can be controlled by multiple RTSP connections.
The RTSP session is associated with a path and has all the fields you need.

**Comment by terion-name** [comment]
oh... sorry, confused because rtmp api uses connections

**Comment by terion-name** [comment]
@aler9 but it dosn't help in reallity.
in `runOnConnect` hook I get rtsp connection id. and with current apis I have no way to get session associated with this connection

**Comment by aler9** [comment]
@terion-name in #4074 i added an additional field called "session" to RTSP connections that allows to retrieve the session associated with the connection, if any.
