### ISSUE TITLE
RTMP publishing fails with "invalid body size"/"invalid message type: 255"

### ISSUE THREAD

**Issue by pannal** [bluenviron/mediamtx#4006]
### Which version are you using?

1.10.0

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

1. start the server
2. publish with FFMPEG `-c:v h264_vaapi -b:v 14M -rc_mode CBR -map 0:0 -map 0:1 -c:a aac -b:a 128k -v verbose -f mpegts rtmp://ip:port/path`
3. stream starts but closes after a few seconds and FFmpeg receives a broken pipe

This happens with either `h264_vaapi` `hevc_vaapi` and `libx264`.

### Server logs

```
mediamtx  | 2024/12/03 13:43:37 INF [RTMP] [conn xxxxxxx:41666] is publishing to path 'panni', 2 tracks (H264, MPEG-4 Audio)
mediamtx  | 2024/12/03 13:43:37 DEB [path panni] destroyed: not in use
mediamtx  | 2024/12/03 13:43:37 INF [RTMP] [conn xxxxxxx:41666] closed: invalid body size
mediamtx  | 2024/12/03 13:43:59 INF [RTMP] [conn xxxxxxx:43598] opened
```

```
mediamtx  | 2024/12/03 13:44:33 INF [RTMP] [conn xxxxxxx:56878] opened
mediamtx  | 2024/12/03 13:44:33 DEB [path panni] created
mediamtx  | 2024/12/03 13:44:33 DEB [path panni] destroyed: not in use
mediamtx  | 2024/12/03 13:44:33 INF [RTMP] [conn xxxxxxx:56878] closed: invalid message type: 255
```

**Comment by aler9** [comment]
Thanks for reporting the RTMP issue, this is fixed by #4018.
Regarding the HLS issue, it's unrelated, open another issue and provide a network dump or a way to replicate.

**Comment by aler9** [comment]
> is it possible to remux ERTMP containing AV1 to mpegts/HTTP-FLV with this software, already?

AV1 cannot be muxed into MPEG-TS since the [specification to do it](https://aomediacodec.github.io/av1-mpeg2-ts/) is currently not implemented by any player, therefore implementing it inside the server would be useless. It can be muxed into fMP4 though, so you can mux AV1 into HLS+fMP4.

**Comment by aler9** [comment]
@pannal glad to hear that something is moving in the right direction, unfortunately FFmpeg, GStreamer and VLC are still missing this ability. We can evaluate the situation again in some months.

Anyway, when player support improves, we will add the ability to carry AV1 tracks with SRT+MPEG-TS, not with HTTP+MPEG-TS. We already support shipping AV1 to browsers through HLS+fMP4 and through WebRTC, and HTTP or FLV have no advantages over them.

**Comment by aler9** [comment]
We already support shipping AV1 with enhanced RTMP :D I know that the specification was recently updated and we are missing the last bits but they will be added.,

**Comment by aler9** [comment]
@pannal publishing AV1 with RTMP has been possible since some versions, here's a sample command (make sure you are using the latest version of both MediaMTX and ffmpeg):

```
ffmpeg -re -f lavfi -i testsrc=size=1920x1080:rate=30 -pix_fmt yuv420p -c:v libsvtav1 -g 120 -minrate:v 3000k -maxrate:v 3000k -preset 8 -f flv rtmp://localhost:1935/test
```

**Comment by aler9** [comment]
moved in #4551
