### ISSUE TITLE
panic: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by nassiharel** [bluenviron/mediamtx#4025]
### Which version are you using?

1.10.0

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

1. start the server
2. publish with RTSP
3. read with VLC

```
panic: runtime error: slice bounds out of range [1:0]
goroutine 81 [running]:
github.com/bluenviron/gortsplib/v4.getPathAndQueryAndTrackID(0xc0006b02d0)
```

**Comment by aler9** [comment]
Thank you very much for reporting the crash, this is fixed by bluenviron/mediamtx#4025
