### ISSUE TITLE
RTSP source] received RTP packet with unknown payload type: 50

### ISSUE THREAD

**Issue by BharadwajManne** [bluenviron/mediamtx#4036]
### Which version are you using?

v1.10.0

### Which operating system are you using?

Other (please describe)

### Describe how to replicate the issue

Hello Team MTX,

Thank you for the excellent product.

Used Device Jetson Nano (arm64v8)

During testing with a white-labeled Univew dome camera (IPC3618SB-ADF28KMC-I0), Univew XVR (XVR302-16Q3) with analog cameras, and the Uniarx XVR (Uniarch XVR 108G3) and Uniarx analog cameras, we encountered the error "[RTSP source] received RTP packet with unknown payload type: 50." Payload Type 50 specifically refers to the H.263 codec in RTP contexts, which aligns with the RTP/AVP (Audio-Visual Profile), where payload type 50 is commonly used for H.263 video. However, when I checked the settings on these XVRs and cameras, the video compression was set to H.264. We also updated the firmware, but the issue persists.

Please investigate this issue and provide guidance on how to resolve it. I appreciate your support and assistance.

### Server logs

2024/12/12 16:42:02 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:02 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:02 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:03 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:03 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:03 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:03 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:04 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:04 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:04 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:05 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:05 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:05 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:06 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:06 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:06 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:06 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:07 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:07 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:08 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:08 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:08 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:08 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:09 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:09 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:09 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:09 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:10 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:10 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:10 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:10 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:11 WAR [path GISIN9999C2] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:11 WAR [path GISIN9999C3] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:11 WAR [path GISIN9999C1] [RTSP source] received RTP packet with unknown payload type: 50
2024/12/12 16:42:11 WAR [path GISIN9999C4] [RTSP source] received RTP packet with unknown payload type: 50

**Comment by aler9** [comment]
Hello, this can be solved but you need to provide a network dump, that can be generated in this way:

* Download wireshark (https://www.wireshark.org/)
* Start capturing on the interface used for exchanging packets
    * If the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card.
* Start the server and replicate the issue
* Stop capturing, save the result in .pcap format
* Attach

**Comment by BharadwajManne** [comment]
[RTP 50 Error.docx](https://github.com/user-attachments/files/18250938/RTP.50.Error.docx)

**Comment by aler9** [comment]
The packet dump was needed so it can be put into a simulator in order to replicate the issue.
Without packet dump this compatibility issue cannot be solved.

**Comment by BharadwajManne** [comment]
[Here is the .pcap file link](https://drive.google.com/file/d/13LhjJBilINYmuey5ppwYX7HSqyFo5hG7/view?usp=sharing)and also attached the zip [RTP 50 Error.pcap.gz](https://github.com/user-attachments/files/18254409/RTP.50.Error.pcap.gz)

When trying to attach the .pcap file, I was encountering with this error,

_We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP._

Please let me know, if you need anything.



Thankyou.

**Comment by aler9** [comment]
@BharadwajManne the dump is still useless since it was not recorded from the moment the server was started but from a random moment later. Instructions on what is needed when reporting these kind of issues are pretty simple and were shown to when you created the bug report and again when you did not attach anything.
I won't provide any further help.
