### ISSUE TITLE
hello can you make the reader of webrtc html , css dynamic

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [bluenviron/mediamtx#4053]
### Describe the feature

instead of hard coded in the repository itself , is it possible to provide custom html and css to override the current ui ?

**Comment by asturl** [comment]
There's nothing stopping you from making a completely custom html frontend that just connects a video element to the webrtc endpoint (using the javascript from the reader page as a guide)

Or do you explicitly want to restyle the page that opens when you go to a MediaMTX stream's webrtc webpage, without hosting anything else?

**Comment by MohamedKHALILRouissi** [comment]
yes i want to use the base image for mediamtx , then use the ui ( html,css,js) as folder or link

**Comment by aler9** [comment]
duplicate of #1229
