### ISSUE TITLE
Add Storage Provider Support for Recordings (S3, GCP, Azure)

### ISSUE THREAD

**Issue by usama-liaqat** [bluenviron/mediamtx#4056]
### Describe the feature

Add the ability to select cloud storage providers (e.g., S3, GCP, Azure) for storing recordings. This would allow users to configure their preferred storage location when saving recordings

This feature would be similar to how LiveKit uses a storage provider configuration for egress, enabling users to select and configure a storage provider (e.g., AWS S3, Google Cloud Storage, Azure Blob Storage) for recording files

**Comment by aler9** [comment]
This is already available and documented in the README:
https://github.com/bluenviron/mediamtx?tab=readme-ov-file#record-streams-to-disk

**Comment by usama-liaqat** [comment]
Thanks
