### ISSUE TITLE
WebRTC/RTMP -> RTSP loses AV1 video

### ISSUE THREAD

**Issue by Bleuzen** [bluenviron/mediamtx#4060]
### Which version are you using?

v1.10.0

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

1. start the server
2. publish with WebRTC or RTMP with the AV1 codec
3. read with rtsp using ffmpeg

### Server logs

```
2024/12/20 20:41:14 INF [WebRTC] [session xxxses01] created by xxx.xxx.xxx.xxx:xxx
2024/12/20 20:41:17 INF [WebRTC] [session xxxses01] peer connection established, local candidate: host/udp/xxx.xxx.xxx.xxx/xxx, remote candidate: prflx/udp/xxx.xxx.xxx.xxx/xxx
2024/12/20 20:41:17 INF [WebRTC] [session xxxses01] is publishing to path 'xxx', 2 tracks (Opus, AV1)
2024/12/20 20:41:18 INF [RTSP] [conn xxx.xxx.xxx.xxx:xxx] opened
2024/12/20 20:41:18 INF [RTSP] [session xxxses02] created by xxx.xxx.xxx.xxx:xxx
2024/12/20 20:41:18 INF [RTSP] [session xxxses02] is reading from path 'xxx', with TCP, 2 tracks (Opus, AV1)
```

### FFmpeg log

```
Input #0, rtsp, from 'rtsp://xxx:xxx/xxx':
  Metadata:
    title           :  
  Duration: N/A, start: 0.104844, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
  Stream #0:1: Video: none, none, 30 fps, 30 tbr, 90k tbn
No decoder could be found for codec none
```

It does not detect the codec of the video stream so it fails playing it.
Switching the video codec to H264 makes it work. Only AV1 is broken.

**Comment by tmatth** [comment]
Note that ffmpeg doesn't support AV1 in RTP yet, there's a patchset being reviewed on the mailing list that you can test with:
https://patchwork.ffmpeg.org/project/ffmpeg/patch/0b3c803d-06cf-48b7-a6cc-5c89718d33e9@axis.com/

**Comment by Bleuzen** [comment]
> Note that ffmpeg doesn't support AV1 in RTP yet, there's a patchset being reviewed on the mailing list that you can test with: https://patchwork.ffmpeg.org/project/ffmpeg/patch/0b3c803d-06cf-48b7-a6cc-5c89718d33e9@axis.com/

Okay thanks for the info.
