### ISSUE TITLE
AV1 Streams lose Audio Codec ( WebRTC / HLS (AAC) )

### ISSUE THREAD

**Issue by DoM1niC** [bluenviron/mediamtx#4065]
### Which version are you using?

main

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

1. Start a Stream with a AV1 Encoder in e.g. RTMP with AAC Audio
![image](https://github.com/user-attachments/assets/3b5ca004-b537-4234-897c-5e56e0b17abe)

Another Codecs are fine like H264/H265 and AV1 with Opus in WHIP the WebRTC based Stream have Audio too but HLS still lose. 

Can this issue caused by https://github.com/bluenviron/mediamtx/issues/3902 ? 

Previously its seems the Audio was OK in my mind but I'm not sure rightnow.

### Network dump
[Mediamtx Wireshark Dump.zip](https://github.com/user-attachments/files/18223028/Mediamtx.Wireshark.Dump.zip)

**Comment by aler9** [comment]
There was a compatibility issue that prevented VLC from reading audio tracks with HLS. This is fixed by https://github.com/bluenviron/gohlslib/pull/204

**Comment by DoM1niC** [comment]
ok strange but I have no sound in HTML5 Player too....

**Comment by aler9** [comment]
@DoM1niC you mentioned too many use technologies in the same bug report (HLS, WebRTC, Opus, AAC, VLC) without providing server logs or infos about how you are generating the stream.
If you still have problems, open a bug report for each use case and describe explicitly how to replicate the specific bug.
Also remember that reading/publishing AAC with WebRTC is not supported.
