### ISSUE TITLE
Do not support AV1 for RTSP

### ISSUE THREAD

**Issue by Jerryho2020** [bluenviron/mediamtx#4066]
### Which version are you using?

v1.9.3

### Which operating system are you using?

Windows amd64 standard

### Describe how to replicate the issue

[out#0/rtsp @ 000002064560ea40] Codec AVOption preset (Encoding preset) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> av1 (libaom-av1))
Press [q] to stop, [?] for help
[libaom-av1 @ 00000206476cea00] v3.10.0
[out#0/rtsp @ 000002064560ea40] Could not write header (incorrect codec parameters ?): Server returned 400 Bad Request
[vf#0:0 @ 00000206455e59c0] Error sending frames to consumers: Server returned 400 Bad Request
[vf#0:0 @ 00000206455e59c0] Task finished with error code: -808465656 (Server returned 400 Bad Request)
[vf#0:0 @ 00000206455e59c0] Terminating thread with return code -808465656 (Server returned 400 Bad Request)
[out#0/rtsp @ 000002064560ea40] Nothing was written into output file, because at least one of its streams received no packets.
/

### Server logs

2024/12/23 17:16:37 INF [RTSP] [conn 127.0.0.1:6585] opened
2024/12/23 17:16:37 INF [RTSP] [session 628f77e6] created by 127.0.0.1:6585
2024/12/23 17:16:37 INF [RTSP] [conn 127.0.0.1:6585] closed: invalid SDP: media 1 is invalid: clock rate not found
2024/12/23 17:16:37 INF [RTSP] [session 628f77e6] destroyed: not in use

**Comment by aler9** [comment]
https://github.com/bluenviron/mediamtx/issues/2261#issuecomment-1696410937
