### ISSUE TITLE
Support SRT

### ISSUE THREAD

**Issue by aler9** [bluenviron/mediamtx#563]
## Describe the feature

SRT is the newer protocol in the family of video/audio streaming, and it's the protocol of choice of 4k/8k professional cameras.

Supporting it would make the server future-proof.

A couple of implementation exists, none of them in native Go:
* https://github.com/Haivision/srt
* https://github.com/russelltg/srt-rs

**Comment by Kiwa21** [comment]
Here you go : https://github.com/Haivision/srtgo

It would be great to have this :)

**Comment by TUISTERa** [comment]
+1 for this

**Comment by OscarParzon** [comment]
+1 I am also interested.
today i am forwarding "ffmpeg srt: copy rtmp: rtsp-simple" and I have errors from the rtsp-simple side. I still do not clear anything concrete.
I keep trying.

**Comment by aler9** [comment]
This feature is being implemented here: #2068

**Comment by aler9** [comment]
all done and merged into main.
