### ISSUE TITLE
RTSP-Simple-Server stops sending RTP packets to Janus Gateway

### ISSUE THREAD

**Issue by mgrLMMV** [bluenviron/mediamtx#647]
## Which version are you using?

v0.17.6

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I am currently using rtsp-simple-server to ingest a RTSP stream (VP8)  and I am using Janus-gateway to read the stream from rtsp-simple server to send it to WebRTC clients. Everything works right, but after 1 or 2 minutes rtsp-simple-server stops sending RTP packets (over UDP) to Janus. After 5 seconds without media, Janus sends a FIN, ACK and restarts the connection.

I don't understand why rtsp-simple-server stops sending RTP packets to Janus, but will continue to send them to VLC

## Describe how to replicate the issue

1. Start RTSP-Simple-Server
2. publish an RTSP(VP8) to it
3. clone [https://github.com/meetecho/janus-gateway](url)
4. Follow the installation guide to be able to run the streaming demo on localhost
5. add this field in janus.plugin.streaming.jcfg:
 `rtsp-test: {
        type = "rtsp"
        id = "test"
        description = "test"
        audio = false
        video = true
        rtsp_failcheck = "false"
        url = "­<rtsp url of the rtsp-simple-server stream eg: rtsp://localhost:8554/mystream>"
}`
Janus and RTSP-Simple-Server must be on the same LAN because of UDP
6. Start Janus and watch the video under [http://localhost/janusDemo/streamingtest.html](url). Press start and watch video
7. Video should play and after a minute or so, the stream will stop and restart. 

## Did you attach a network dump?

[pcap.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7332713/pcap.tar.gz)
- 10.10.100.113 is Janus
- 10.10.100.133 is RTSP-Simple-Server

You can see after packet no. 8322 that rtsp-simple-server (10.10.100.133) stops sending RTPs  before Janus(10.10.100.113) restarts the connection at packet no. 8327

In this pcap, a colleague was watching the WebRTC steram on another machine so it was easier to isolate the communication between janus and rtsp-simple-server
Note: there is no VLC in this capture, but when rtsp-server stops sending to janus, it still sends to VLC

**Comment by eLvErDe** [comment]
In case someone find this ticket with the same issue, the answer is here:

https://janus.conf.meetecho.com/docs/streaming.html

```
rtsp_session_timeout = by default the streaming plugin will check the RTSP connection with an OPTIONS query,
        the value of the timeout comes from the RTSP session initializer and by default
        this session timeout is the half of this value In some cases this value can be too high (for example more than one minute)
        because of the media server. In that case this plugin will calculate the timeout with this
        formula: timeout = min(session_timeout, rtsp_session_timeout / 2). (default=0s)
```

So I'm not sure how it works exactly but this option seems to override delay between two OPTIONS calls in case default value computed (from what ?) is to high.
From my understanding, it should be set to 60 to ensure a maximum delay of 30s between two OPTIONS calls but it did not work.
However setting rtsp_session_timeout = 30 fixed the issue with RTSP Simple Server.
