### ISSUE TITLE
Feature Request: Expose client IP variable for runOnRead

### ISSUE THREAD

**Issue by gluedots** [bluenviron/mediamtx#687]
## Describe the feature

Expose a `client_IP` variable to `runOnRead` when a clients starts reading.

Could be useful for debugging, logging, or security.

**Comment by Warr1024** [comment]
Ideally, for HLS, this could also inspect X-Forwarded-For or X-Real-IP (though knowing how far along a proxy chain to trust is not a trivial problem)

**Comment by aler9** [comment]
moved to #1414
