### ISSUE TITLE
Amazon Echo devices fail to play stream

### ISSUE THREAD

**Issue by billsimon** [bluenviron/mediamtx#984]
## Which version are you using?

v17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I have configured rtsp-simple-server with RTSPS to allow connections from Amazon Echo video device (RTSPS reader)

This works fine with version 0.17.17.

I tried upgrading to the latest version 0.19.1 and the Amazon device initiates the connection but will not play the stream (says Buffering... forever).

The breaking change is somewhere in version 0.18.0. The Amazon device doesn't provide any logs so I don't know what it doesn't like. Could you speculate about differences between 17.17 and 18.0 that might cause failure?

## Describe how to replicate the issue

1. start the server
2. publish with on demand ffmpeg source
3. read with Amazon Echo video device using RTSPS

**Comment by aler9** [comment]
Hello, the main different between v0.17.17 and v0.18.0 is that the latter parses all incoming RTP/RTCP packets and re-encodes them. Anyway, please post a sample configuration and a server log with `logLevel: debug`, maybe it contains something useful.

**Comment by aler9** [comment]
this can't be solved without help from the author.
